/-
Generated by `generate_connectivity_instances.py` from the live `surface.py`
connectivity stream.  Source indices h41312--h41315.
-/
import AggregateConnectivityPacking

/-!
# Generated connectivity assertion chunk 017

Exact source assertions h41312--h41315 from the audited connectivity
block.  Regenerate this file; do not edit it by hand.
-/

namespace Problem97
namespace ExactFiveCard13DistinctRadiusSourceIngressScratch

open ATailCriticalPairFrontier
open ATailBiApexRobustCapBounds
open ATailExactFiveCard13CnfIngressScratch
open ATailExactFiveCard13CommonLabelTransportScratch
open ATailExactFiveGlobalCrossDeletionPair
open ATailExactFiveGlobalCoverStarGeometry
open ATailExactFiveMutualOneHitGeometry
open ATailFirstApexShellRole
open ATailLargeCapUniqueFive
open ATailLargeCapUniqueFivePhysicalOmissionCycle
open ATailLargeCapUniqueFivePhysicalOmissionTransitionGlobal
open ATailOrientedPhysicalApexIngress
open ATailParentExactFiveSecondCap
open ATailPhysicalSecondApexCommonDeletion
open CanonicalAsymmetricSemanticRowTable

attribute [local instance] Classical.propDecidable

noncomputable section

/-- Exact source assertions h41312--h41315. -/
structure ConnectivityAssertionsChunk017
    (edge : Fin 3 → Label → Label → Bool) (bits : ConnectivityBits) : Prop where
  h41312 : connectivityBit bits 2 0 12 11 = true
  h41313 : connectivityBit bits 2 1 12 11 = true
  h41314 : connectivityBit bits 2 0 12 12 = true
  h41315 : connectivityBit bits 2 1 12 12 = true

variable
    {D : CounterexampleData} {S : SurplusCapPacket D.A} {radius : ℝ}
    {H : CriticalShellSystem D.A}
    {F : CriticalPairFrontier D S radius H}
    {R : FrontierCommonDeletionParentResidual F}
    {B : FrontierBiApexRobustResidual R}
    {Q : FrontierBiApexRobustExactFiveSecondCapResidual B}
    {profile : LargeCapUniqueFiveSecondApexRadius D S}
    {M : PhysicalActualCriticalMutualOmissionPair H profile}
    {N : SourceTwoHitNormalForm Q profile M}
    {P : CanonicalAsymmetricRolePrepacket N}
    {star : PhysicalGlobalCrossDeletionStar profile}
    {first : FirstApexShellRolePacket F R}
    {T : CanonicalAsymmetricSemanticRowTable P star first}

/-- The structured semantic packets prove this entire bounded source chunk. -/
theorem canonicalConnectivityAssertionsChunk017
    (C : CanonicalCoverFamilies T)
    (packets : CanonicalThreeFamilyReachabilityPacket C) :
    ConnectivityAssertionsChunk017 (directSourceRowMember C)
      (packCanonicalConnectivity packets) := by
  exact {
    h41312 := by
      simpa [connectivityFinBit] using packedConnectivity_terminal_sourceAssertion packets (2 : Fin 3) (0 : Fin 2) (11 : Label)
    h41313 := by
      simpa [connectivityFinBit] using packedConnectivity_terminal_sourceAssertion packets (2 : Fin 3) (1 : Fin 2) (11 : Label)
    h41314 := by
      simpa [connectivityFinBit] using packedConnectivity_terminal_sourceAssertion packets (2 : Fin 3) (0 : Fin 2) (12 : Label)
    h41315 := by
      simpa [connectivityFinBit] using packedConnectivity_terminal_sourceAssertion packets (2 : Fin 3) (1 : Fin 2) (12 : Label)
  }

end

end ExactFiveCard13DistinctRadiusSourceIngressScratch
end Problem97
