import Erdos9796Proof.P97.ATail.BlockerVExactSeventeenFortySixthModelRefinements
import Erdos9796Proof.P97.ATail.BlockerVExactSeventeenFortySixthModelRefinementsExport

#print axioms Problem97.ATailBlockerVExactSeventeenFortySixthModelRefinements.sourceAssign_extendedFortySixthModelRefinementsCnf
#print axioms Problem97.ATailBlockerVExactSeventeenFortySixthModelRefinements.false_of_sourceRealization_of_extendedFortySixthModelRefinementsCnf_unsat
#print axioms Problem97.ATailBlockerVExactSeventeenFortySixthModelRefinementsExport.extendedFortySixthModelRefinementsDimacsString
