import Erdos9796Proof.P97.ATail.CardElevenUniqueFourCertificate.Support.ExactFiveCommonShellV7.G3PerpendicularBisectorSliceLedger

#print axioms Problem97.ExactFiveCommonShellV7.PerpendicularBisectorClauseIndex
#print axioms Problem97.ExactFiveCommonShellV7.g3RetainedPerpendicularBisectorIndices
#print axioms Problem97.ExactFiveCommonShellV7.PerpendicularBisectorOccurrence
#print axioms Problem97.ExactFiveCommonShellV7.renderPerpendicularBisectorOccurrence
#print axioms Problem97.ExactFiveCommonShellV7.g3PerpendicularBisectorSlice
#print axioms Problem97.ExactFiveCommonShellV7.g3PerpendicularBisectorSliceClauses
#print axioms Problem97.ExactFiveCommonShellV7.g3PerpendicularBisectorSlice_size
#print axioms Problem97.ExactFiveCommonShellV7.g3PerpendicularBisectorSlice_perm_checkpoint
#print axioms Problem97.ExactFiveCommonShellV7.CanonicalPacket.renderPerpendicularBisectorOccurrence_sat
#print axioms Problem97.ExactFiveCommonShellV7.CanonicalPacket.g3PerpendicularBisectorSlice_sat
#print axioms Problem97.ExactFiveCommonShellV7.CanonicalPacket.g3Checkpoint0_perpendicularBisectorSlice_signed_sat
