/- Generated by generate_bv_circuit.py. -/
import ExactFiveCard13BVCircuitChunks.Base

namespace Problem97.ATailExactFiveCard13BVCircuit

set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false

def common213 (rows : RowBits) (blockers : BlockerBits) (shell : ShellBits) (q w : RoleBits) (b1 : FirstRowBits) (ranks : RankBits) : Bool :=
  !(rowBit rows 0 2 0 && rowBit rows 0 2 10 && rowBit rows 1 4 0 && rowBit rows 1 4 10) &&
    !(rowBit rows 0 2 0 && rowBit rows 0 2 11 && rowBit rows 1 4 0 && rowBit rows 1 4 11) &&
    !(rowBit rows 0 2 0 && rowBit rows 0 2 12 && rowBit rows 1 4 0 && rowBit rows 1 4 12) &&
    !(rowBit rows 0 2 1 && rowBit rows 0 2 5 && rowBit rows 1 4 1 && rowBit rows 1 4 5) &&
    !(rowBit rows 0 2 1 && rowBit rows 0 2 6 && rowBit rows 1 4 1 && rowBit rows 1 4 6) &&
    !(rowBit rows 0 2 1 && rowBit rows 0 2 7 && rowBit rows 1 4 1 && rowBit rows 1 4 7) &&
    !(rowBit rows 0 2 1 && rowBit rows 0 2 8 && rowBit rows 1 4 1 && rowBit rows 1 4 8) &&
    !(rowBit rows 0 2 1 && rowBit rows 0 2 9 && rowBit rows 1 4 1 && rowBit rows 1 4 9) &&
    !(rowBit rows 0 2 1 && rowBit rows 0 2 10 && rowBit rows 1 4 1 && rowBit rows 1 4 10) &&
    !(rowBit rows 0 2 1 && rowBit rows 0 2 11 && rowBit rows 1 4 1 && rowBit rows 1 4 11) &&
    !(rowBit rows 0 2 1 && rowBit rows 0 2 12 && rowBit rows 1 4 1 && rowBit rows 1 4 12) &&
    !(rowBit rows 0 2 5 && rowBit rows 0 2 6 && rowBit rows 1 4 5 && rowBit rows 1 4 6) &&
    !(rowBit rows 0 2 5 && rowBit rows 0 2 7 && rowBit rows 1 4 5 && rowBit rows 1 4 7) &&
    !(rowBit rows 0 2 5 && rowBit rows 0 2 8 && rowBit rows 1 4 5 && rowBit rows 1 4 8) &&
    !(rowBit rows 0 2 5 && rowBit rows 0 2 9 && rowBit rows 1 4 5 && rowBit rows 1 4 9) &&
    !(rowBit rows 0 2 5 && rowBit rows 0 2 10 && rowBit rows 1 4 5 && rowBit rows 1 4 10) &&
    !(rowBit rows 0 2 5 && rowBit rows 0 2 11 && rowBit rows 1 4 5 && rowBit rows 1 4 11) &&
    !(rowBit rows 0 2 5 && rowBit rows 0 2 12 && rowBit rows 1 4 5 && rowBit rows 1 4 12) &&
    !(rowBit rows 0 2 6 && rowBit rows 0 2 7 && rowBit rows 1 4 6 && rowBit rows 1 4 7) &&
    !(rowBit rows 0 2 6 && rowBit rows 0 2 8 && rowBit rows 1 4 6 && rowBit rows 1 4 8) &&
    !(rowBit rows 0 2 6 && rowBit rows 0 2 9 && rowBit rows 1 4 6 && rowBit rows 1 4 9) &&
    !(rowBit rows 0 2 6 && rowBit rows 0 2 10 && rowBit rows 1 4 6 && rowBit rows 1 4 10) &&
    !(rowBit rows 0 2 6 && rowBit rows 0 2 11 && rowBit rows 1 4 6 && rowBit rows 1 4 11) &&
    !(rowBit rows 0 2 6 && rowBit rows 0 2 12 && rowBit rows 1 4 6 && rowBit rows 1 4 12) &&
    !(rowBit rows 0 2 7 && rowBit rows 0 2 8 && rowBit rows 1 4 7 && rowBit rows 1 4 8) &&
    !(rowBit rows 0 2 7 && rowBit rows 0 2 9 && rowBit rows 1 4 7 && rowBit rows 1 4 9) &&
    !(rowBit rows 0 2 7 && rowBit rows 0 2 10 && rowBit rows 1 4 7 && rowBit rows 1 4 10) &&
    !(rowBit rows 0 2 7 && rowBit rows 0 2 11 && rowBit rows 1 4 7 && rowBit rows 1 4 11) &&
    !(rowBit rows 0 2 7 && rowBit rows 0 2 12 && rowBit rows 1 4 7 && rowBit rows 1 4 12) &&
    !(rowBit rows 0 2 8 && rowBit rows 0 2 9 && rowBit rows 1 4 8 && rowBit rows 1 4 9) &&
    !(rowBit rows 0 2 8 && rowBit rows 0 2 10 && rowBit rows 1 4 8 && rowBit rows 1 4 10) &&
    !(rowBit rows 0 2 8 && rowBit rows 0 2 11 && rowBit rows 1 4 8 && rowBit rows 1 4 11) &&
    !(rowBit rows 0 2 8 && rowBit rows 0 2 12 && rowBit rows 1 4 8 && rowBit rows 1 4 12) &&
    !(rowBit rows 0 2 9 && rowBit rows 0 2 10 && rowBit rows 1 4 9 && rowBit rows 1 4 10) &&
    !(rowBit rows 0 2 9 && rowBit rows 0 2 11 && rowBit rows 1 4 9 && rowBit rows 1 4 11) &&
    !(rowBit rows 0 2 9 && rowBit rows 0 2 12 && rowBit rows 1 4 9 && rowBit rows 1 4 12) &&
    !(rowBit rows 0 2 10 && rowBit rows 0 2 11 && rowBit rows 1 4 10 && rowBit rows 1 4 11) &&
    !(rowBit rows 0 2 10 && rowBit rows 0 2 12 && rowBit rows 1 4 10 && rowBit rows 1 4 12) &&
    !(rowBit rows 0 2 11 && rowBit rows 0 2 12 && rowBit rows 1 4 11 && rowBit rows 1 4 12) &&
    (((bif (rowBit rows 1 2 0 && rowBit rows 0 4 0) then 1#4 else 0#4) + (bif (rowBit rows 1 2 1 && rowBit rows 0 4 1) then 1#4 else 0#4) + (bif (rowBit rows 1 2 2 && rowBit rows 0 4 2) then 1#4 else 0#4) + (bif (rowBit rows 1 2 3 && rowBit rows 0 4 3) then 1#4 else 0#4) + (bif (rowBit rows 1 2 4 && rowBit rows 0 4 4) then 1#4 else 0#4) + (bif (rowBit rows 1 2 5 && rowBit rows 0 4 5) then 1#4 else 0#4) + (bif (rowBit rows 1 2 6 && rowBit rows 0 4 6) then 1#4 else 0#4) + (bif (rowBit rows 1 2 7 && rowBit rows 0 4 7) then 1#4 else 0#4) + (bif (rowBit rows 1 2 8 && rowBit rows 0 4 8) then 1#4 else 0#4) + (bif (rowBit rows 1 2 9 && rowBit rows 0 4 9) then 1#4 else 0#4) + (bif (rowBit rows 1 2 10 && rowBit rows 0 4 10) then 1#4 else 0#4) + (bif (rowBit rows 1 2 11 && rowBit rows 0 4 11) then 1#4 else 0#4) + (bif (rowBit rows 1 2 12 && rowBit rows 0 4 12) then 1#4 else 0#4))).ule 2#4 &&
    !(rowBit rows 1 2 0 && rowBit rows 1 2 1 && rowBit rows 0 4 0 && rowBit rows 0 4 1) &&
    !(rowBit rows 1 2 0 && rowBit rows 1 2 5 && rowBit rows 0 4 0 && rowBit rows 0 4 5) &&
    !(rowBit rows 1 2 0 && rowBit rows 1 2 6 && rowBit rows 0 4 0 && rowBit rows 0 4 6) &&
    !(rowBit rows 1 2 0 && rowBit rows 1 2 7 && rowBit rows 0 4 0 && rowBit rows 0 4 7) &&
    !(rowBit rows 1 2 0 && rowBit rows 1 2 8 && rowBit rows 0 4 0 && rowBit rows 0 4 8) &&
    !(rowBit rows 1 2 0 && rowBit rows 1 2 9 && rowBit rows 0 4 0 && rowBit rows 0 4 9) &&
    !(rowBit rows 1 2 0 && rowBit rows 1 2 10 && rowBit rows 0 4 0 && rowBit rows 0 4 10) &&
    !(rowBit rows 1 2 0 && rowBit rows 1 2 11 && rowBit rows 0 4 0 && rowBit rows 0 4 11) &&
    !(rowBit rows 1 2 0 && rowBit rows 1 2 12 && rowBit rows 0 4 0 && rowBit rows 0 4 12) &&
    !(rowBit rows 1 2 1 && rowBit rows 1 2 5 && rowBit rows 0 4 1 && rowBit rows 0 4 5) &&
    !(rowBit rows 1 2 1 && rowBit rows 1 2 6 && rowBit rows 0 4 1 && rowBit rows 0 4 6) &&
    !(rowBit rows 1 2 1 && rowBit rows 1 2 7 && rowBit rows 0 4 1 && rowBit rows 0 4 7) &&
    !(rowBit rows 1 2 1 && rowBit rows 1 2 8 && rowBit rows 0 4 1 && rowBit rows 0 4 8) &&
    !(rowBit rows 1 2 1 && rowBit rows 1 2 9 && rowBit rows 0 4 1 && rowBit rows 0 4 9) &&
    !(rowBit rows 1 2 1 && rowBit rows 1 2 10 && rowBit rows 0 4 1 && rowBit rows 0 4 10) &&
    !(rowBit rows 1 2 1 && rowBit rows 1 2 11 && rowBit rows 0 4 1 && rowBit rows 0 4 11) &&
    !(rowBit rows 1 2 1 && rowBit rows 1 2 12 && rowBit rows 0 4 1 && rowBit rows 0 4 12) &&
    !(rowBit rows 1 2 5 && rowBit rows 1 2 6 && rowBit rows 0 4 5 && rowBit rows 0 4 6) &&
    !(rowBit rows 1 2 5 && rowBit rows 1 2 7 && rowBit rows 0 4 5 && rowBit rows 0 4 7) &&
    !(rowBit rows 1 2 5 && rowBit rows 1 2 8 && rowBit rows 0 4 5 && rowBit rows 0 4 8) &&
    !(rowBit rows 1 2 5 && rowBit rows 1 2 9 && rowBit rows 0 4 5 && rowBit rows 0 4 9) &&
    !(rowBit rows 1 2 5 && rowBit rows 1 2 10 && rowBit rows 0 4 5 && rowBit rows 0 4 10) &&
    !(rowBit rows 1 2 5 && rowBit rows 1 2 11 && rowBit rows 0 4 5 && rowBit rows 0 4 11) &&
    !(rowBit rows 1 2 5 && rowBit rows 1 2 12 && rowBit rows 0 4 5 && rowBit rows 0 4 12)

end Problem97.ATailExactFiveCard13BVCircuit
