/- Generated by generate_bv_circuit.py. -/
import ExactFiveCard13BVCircuitChunks.Base

namespace Problem97.ATailExactFiveCard13BVCircuit

set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false

def common143 (rows : RowBits) (blockers : BlockerBits) (shell : ShellBits) (q w : RoleBits) (b1 : FirstRowBits) (ranks : RankBits) : Bool :=
  !(rowBit rows 2 2 6 && rowBit rows 2 2 9 && rowBit rows 2 10 6 && rowBit rows 2 10 9) &&
    !(rowBit rows 2 2 7 && rowBit rows 2 2 8 && rowBit rows 2 10 7 && rowBit rows 2 10 8) &&
    !(rowBit rows 2 2 7 && rowBit rows 2 2 9 && rowBit rows 2 10 7 && rowBit rows 2 10 9) &&
    !(rowBit rows 2 2 8 && rowBit rows 2 2 9 && rowBit rows 2 10 8 && rowBit rows 2 10 9) &&
    !(rowBit rows 2 2 11 && rowBit rows 2 2 12 && rowBit rows 2 10 11 && rowBit rows 2 10 12) &&
    !(rowBit rows 2 2 0 && rowBit rows 2 2 1 && rowBit rows 2 11 0 && rowBit rows 2 11 1) &&
    !(rowBit rows 2 2 0 && rowBit rows 2 2 12 && rowBit rows 2 11 0 && rowBit rows 2 11 12) &&
    !(rowBit rows 2 2 1 && rowBit rows 2 2 12 && rowBit rows 2 11 1 && rowBit rows 2 11 12) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 4 && rowBit rows 2 11 3 && rowBit rows 2 11 4) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 5 && rowBit rows 2 11 3 && rowBit rows 2 11 5) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 6 && rowBit rows 2 11 3 && rowBit rows 2 11 6) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 7 && rowBit rows 2 11 3 && rowBit rows 2 11 7) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 8 && rowBit rows 2 11 3 && rowBit rows 2 11 8) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 9 && rowBit rows 2 11 3 && rowBit rows 2 11 9) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 10 && rowBit rows 2 11 3 && rowBit rows 2 11 10) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 5 && rowBit rows 2 11 4 && rowBit rows 2 11 5) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 6 && rowBit rows 2 11 4 && rowBit rows 2 11 6) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 7 && rowBit rows 2 11 4 && rowBit rows 2 11 7) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 8 && rowBit rows 2 11 4 && rowBit rows 2 11 8) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 9 && rowBit rows 2 11 4 && rowBit rows 2 11 9) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 10 && rowBit rows 2 11 4 && rowBit rows 2 11 10) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 6 && rowBit rows 2 11 5 && rowBit rows 2 11 6) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 7 && rowBit rows 2 11 5 && rowBit rows 2 11 7) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 8 && rowBit rows 2 11 5 && rowBit rows 2 11 8) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 9 && rowBit rows 2 11 5 && rowBit rows 2 11 9) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 10 && rowBit rows 2 11 5 && rowBit rows 2 11 10) &&
    !(rowBit rows 2 2 6 && rowBit rows 2 2 7 && rowBit rows 2 11 6 && rowBit rows 2 11 7) &&
    !(rowBit rows 2 2 6 && rowBit rows 2 2 8 && rowBit rows 2 11 6 && rowBit rows 2 11 8) &&
    !(rowBit rows 2 2 6 && rowBit rows 2 2 9 && rowBit rows 2 11 6 && rowBit rows 2 11 9) &&
    !(rowBit rows 2 2 6 && rowBit rows 2 2 10 && rowBit rows 2 11 6 && rowBit rows 2 11 10) &&
    !(rowBit rows 2 2 7 && rowBit rows 2 2 8 && rowBit rows 2 11 7 && rowBit rows 2 11 8) &&
    !(rowBit rows 2 2 7 && rowBit rows 2 2 9 && rowBit rows 2 11 7 && rowBit rows 2 11 9) &&
    !(rowBit rows 2 2 7 && rowBit rows 2 2 10 && rowBit rows 2 11 7 && rowBit rows 2 11 10) &&
    !(rowBit rows 2 2 8 && rowBit rows 2 2 9 && rowBit rows 2 11 8 && rowBit rows 2 11 9) &&
    !(rowBit rows 2 2 8 && rowBit rows 2 2 10 && rowBit rows 2 11 8 && rowBit rows 2 11 10) &&
    !(rowBit rows 2 2 9 && rowBit rows 2 2 10 && rowBit rows 2 11 9 && rowBit rows 2 11 10) &&
    !(rowBit rows 2 2 0 && rowBit rows 2 2 1 && rowBit rows 2 12 0 && rowBit rows 2 12 1) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 4 && rowBit rows 2 12 3 && rowBit rows 2 12 4) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 5 && rowBit rows 2 12 3 && rowBit rows 2 12 5) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 6 && rowBit rows 2 12 3 && rowBit rows 2 12 6) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 7 && rowBit rows 2 12 3 && rowBit rows 2 12 7) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 8 && rowBit rows 2 12 3 && rowBit rows 2 12 8) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 9 && rowBit rows 2 12 3 && rowBit rows 2 12 9) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 10 && rowBit rows 2 12 3 && rowBit rows 2 12 10) &&
    !(rowBit rows 2 2 3 && rowBit rows 2 2 11 && rowBit rows 2 12 3 && rowBit rows 2 12 11) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 5 && rowBit rows 2 12 4 && rowBit rows 2 12 5) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 6 && rowBit rows 2 12 4 && rowBit rows 2 12 6) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 7 && rowBit rows 2 12 4 && rowBit rows 2 12 7) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 8 && rowBit rows 2 12 4 && rowBit rows 2 12 8) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 9 && rowBit rows 2 12 4 && rowBit rows 2 12 9) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 10 && rowBit rows 2 12 4 && rowBit rows 2 12 10) &&
    !(rowBit rows 2 2 4 && rowBit rows 2 2 11 && rowBit rows 2 12 4 && rowBit rows 2 12 11) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 6 && rowBit rows 2 12 5 && rowBit rows 2 12 6) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 7 && rowBit rows 2 12 5 && rowBit rows 2 12 7) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 8 && rowBit rows 2 12 5 && rowBit rows 2 12 8) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 9 && rowBit rows 2 12 5 && rowBit rows 2 12 9) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 10 && rowBit rows 2 12 5 && rowBit rows 2 12 10) &&
    !(rowBit rows 2 2 5 && rowBit rows 2 2 11 && rowBit rows 2 12 5 && rowBit rows 2 12 11) &&
    !(rowBit rows 2 2 6 && rowBit rows 2 2 7 && rowBit rows 2 12 6 && rowBit rows 2 12 7) &&
    !(rowBit rows 2 2 6 && rowBit rows 2 2 8 && rowBit rows 2 12 6 && rowBit rows 2 12 8) &&
    !(rowBit rows 2 2 6 && rowBit rows 2 2 9 && rowBit rows 2 12 6 && rowBit rows 2 12 9) &&
    !(rowBit rows 2 2 6 && rowBit rows 2 2 10 && rowBit rows 2 12 6 && rowBit rows 2 12 10) &&
    !(rowBit rows 2 2 6 && rowBit rows 2 2 11 && rowBit rows 2 12 6 && rowBit rows 2 12 11) &&
    !(rowBit rows 2 2 7 && rowBit rows 2 2 8 && rowBit rows 2 12 7 && rowBit rows 2 12 8)

end Problem97.ATailExactFiveCard13BVCircuit
