/- Generated by generate_bv_circuit.py. -/
import ExactFiveCard13BVCircuitChunks.Base

namespace Problem97.ATailExactFiveCard13BVCircuit

set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false

def common429 (rows : RowBits) (blockers : BlockerBits) (shell : ShellBits) (q w : RoleBits) (b1 : FirstRowBits) (ranks : RankBits) : Bool :=
  !(rowBit rows 2 0 7 && rowBit rows 2 0 10 && rowBit rows 1 5 7 && rowBit rows 1 5 10) &&
    !(rowBit rows 2 0 7 && rowBit rows 2 0 11 && rowBit rows 1 5 7 && rowBit rows 1 5 11) &&
    !(rowBit rows 2 0 7 && rowBit rows 2 0 12 && rowBit rows 1 5 7 && rowBit rows 1 5 12) &&
    !(rowBit rows 2 0 8 && rowBit rows 2 0 9 && rowBit rows 1 5 8 && rowBit rows 1 5 9) &&
    !(rowBit rows 2 0 8 && rowBit rows 2 0 10 && rowBit rows 1 5 8 && rowBit rows 1 5 10) &&
    !(rowBit rows 2 0 8 && rowBit rows 2 0 11 && rowBit rows 1 5 8 && rowBit rows 1 5 11) &&
    !(rowBit rows 2 0 8 && rowBit rows 2 0 12 && rowBit rows 1 5 8 && rowBit rows 1 5 12) &&
    !(rowBit rows 2 0 9 && rowBit rows 2 0 10 && rowBit rows 1 5 9 && rowBit rows 1 5 10) &&
    !(rowBit rows 2 0 9 && rowBit rows 2 0 11 && rowBit rows 1 5 9 && rowBit rows 1 5 11) &&
    !(rowBit rows 2 0 9 && rowBit rows 2 0 12 && rowBit rows 1 5 9 && rowBit rows 1 5 12) &&
    !(rowBit rows 2 0 10 && rowBit rows 2 0 11 && rowBit rows 1 5 10 && rowBit rows 1 5 11) &&
    !(rowBit rows 2 0 10 && rowBit rows 2 0 12 && rowBit rows 1 5 10 && rowBit rows 1 5 12) &&
    !(rowBit rows 2 0 11 && rowBit rows 2 0 12 && rowBit rows 1 5 11 && rowBit rows 1 5 12) &&
    (((bif (rowBit rows 1 0 0 && rowBit rows 2 6 0) then 1#4 else 0#4) + (bif (rowBit rows 1 0 1 && rowBit rows 2 6 1) then 1#4 else 0#4) + (bif (rowBit rows 1 0 2 && rowBit rows 2 6 2) then 1#4 else 0#4) + (bif (rowBit rows 1 0 3 && rowBit rows 2 6 3) then 1#4 else 0#4) + (bif (rowBit rows 1 0 4 && rowBit rows 2 6 4) then 1#4 else 0#4) + (bif (rowBit rows 1 0 5 && rowBit rows 2 6 5) then 1#4 else 0#4) + (bif (rowBit rows 1 0 6 && rowBit rows 2 6 6) then 1#4 else 0#4) + (bif (rowBit rows 1 0 7 && rowBit rows 2 6 7) then 1#4 else 0#4) + (bif (rowBit rows 1 0 8 && rowBit rows 2 6 8) then 1#4 else 0#4) + (bif (rowBit rows 1 0 9 && rowBit rows 2 6 9) then 1#4 else 0#4) + (bif (rowBit rows 1 0 10 && rowBit rows 2 6 10) then 1#4 else 0#4) + (bif (rowBit rows 1 0 11 && rowBit rows 2 6 11) then 1#4 else 0#4) + (bif (rowBit rows 1 0 12 && rowBit rows 2 6 12) then 1#4 else 0#4))).ule 2#4 &&
    !(rowBit rows 1 0 1 && rowBit rows 1 0 2 && rowBit rows 2 6 1 && rowBit rows 2 6 2) &&
    !(rowBit rows 1 0 1 && rowBit rows 1 0 3 && rowBit rows 2 6 1 && rowBit rows 2 6 3) &&
    !(rowBit rows 1 0 1 && rowBit rows 1 0 4 && rowBit rows 2 6 1 && rowBit rows 2 6 4) &&
    !(rowBit rows 1 0 1 && rowBit rows 1 0 5 && rowBit rows 2 6 1 && rowBit rows 2 6 5) &&
    !(rowBit rows 1 0 2 && rowBit rows 1 0 3 && rowBit rows 2 6 2 && rowBit rows 2 6 3) &&
    !(rowBit rows 1 0 2 && rowBit rows 1 0 4 && rowBit rows 2 6 2 && rowBit rows 2 6 4) &&
    !(rowBit rows 1 0 2 && rowBit rows 1 0 5 && rowBit rows 2 6 2 && rowBit rows 2 6 5) &&
    !(rowBit rows 1 0 3 && rowBit rows 1 0 4 && rowBit rows 2 6 3 && rowBit rows 2 6 4) &&
    !(rowBit rows 1 0 3 && rowBit rows 1 0 5 && rowBit rows 2 6 3 && rowBit rows 2 6 5) &&
    !(rowBit rows 1 0 4 && rowBit rows 1 0 5 && rowBit rows 2 6 4 && rowBit rows 2 6 5) &&
    !(rowBit rows 1 0 7 && rowBit rows 1 0 8 && rowBit rows 2 6 7 && rowBit rows 2 6 8) &&
    !(rowBit rows 1 0 7 && rowBit rows 1 0 9 && rowBit rows 2 6 7 && rowBit rows 2 6 9) &&
    !(rowBit rows 1 0 7 && rowBit rows 1 0 10 && rowBit rows 2 6 7 && rowBit rows 2 6 10) &&
    !(rowBit rows 1 0 7 && rowBit rows 1 0 11 && rowBit rows 2 6 7 && rowBit rows 2 6 11) &&
    !(rowBit rows 1 0 7 && rowBit rows 1 0 12 && rowBit rows 2 6 7 && rowBit rows 2 6 12) &&
    !(rowBit rows 1 0 8 && rowBit rows 1 0 9 && rowBit rows 2 6 8 && rowBit rows 2 6 9) &&
    !(rowBit rows 1 0 8 && rowBit rows 1 0 10 && rowBit rows 2 6 8 && rowBit rows 2 6 10) &&
    !(rowBit rows 1 0 8 && rowBit rows 1 0 11 && rowBit rows 2 6 8 && rowBit rows 2 6 11) &&
    !(rowBit rows 1 0 8 && rowBit rows 1 0 12 && rowBit rows 2 6 8 && rowBit rows 2 6 12) &&
    !(rowBit rows 1 0 9 && rowBit rows 1 0 10 && rowBit rows 2 6 9 && rowBit rows 2 6 10) &&
    !(rowBit rows 1 0 9 && rowBit rows 1 0 11 && rowBit rows 2 6 9 && rowBit rows 2 6 11) &&
    !(rowBit rows 1 0 9 && rowBit rows 1 0 12 && rowBit rows 2 6 9 && rowBit rows 2 6 12) &&
    !(rowBit rows 1 0 10 && rowBit rows 1 0 11 && rowBit rows 2 6 10 && rowBit rows 2 6 11) &&
    !(rowBit rows 1 0 10 && rowBit rows 1 0 12 && rowBit rows 2 6 10 && rowBit rows 2 6 12) &&
    !(rowBit rows 1 0 11 && rowBit rows 1 0 12 && rowBit rows 2 6 11 && rowBit rows 2 6 12) &&
    (((bif (rowBit rows 2 0 0 && rowBit rows 1 6 0) then 1#4 else 0#4) + (bif (rowBit rows 2 0 1 && rowBit rows 1 6 1) then 1#4 else 0#4) + (bif (rowBit rows 2 0 2 && rowBit rows 1 6 2) then 1#4 else 0#4) + (bif (rowBit rows 2 0 3 && rowBit rows 1 6 3) then 1#4 else 0#4) + (bif (rowBit rows 2 0 4 && rowBit rows 1 6 4) then 1#4 else 0#4) + (bif (rowBit rows 2 0 5 && rowBit rows 1 6 5) then 1#4 else 0#4) + (bif (rowBit rows 2 0 6 && rowBit rows 1 6 6) then 1#4 else 0#4) + (bif (rowBit rows 2 0 7 && rowBit rows 1 6 7) then 1#4 else 0#4) + (bif (rowBit rows 2 0 8 && rowBit rows 1 6 8) then 1#4 else 0#4) + (bif (rowBit rows 2 0 9 && rowBit rows 1 6 9) then 1#4 else 0#4) + (bif (rowBit rows 2 0 10 && rowBit rows 1 6 10) then 1#4 else 0#4) + (bif (rowBit rows 2 0 11 && rowBit rows 1 6 11) then 1#4 else 0#4) + (bif (rowBit rows 2 0 12 && rowBit rows 1 6 12) then 1#4 else 0#4))).ule 2#4 &&
    !(rowBit rows 2 0 1 && rowBit rows 2 0 2 && rowBit rows 1 6 1 && rowBit rows 1 6 2) &&
    !(rowBit rows 2 0 1 && rowBit rows 2 0 3 && rowBit rows 1 6 1 && rowBit rows 1 6 3) &&
    !(rowBit rows 2 0 1 && rowBit rows 2 0 4 && rowBit rows 1 6 1 && rowBit rows 1 6 4) &&
    !(rowBit rows 2 0 1 && rowBit rows 2 0 5 && rowBit rows 1 6 1 && rowBit rows 1 6 5) &&
    !(rowBit rows 2 0 2 && rowBit rows 2 0 3 && rowBit rows 1 6 2 && rowBit rows 1 6 3) &&
    !(rowBit rows 2 0 2 && rowBit rows 2 0 4 && rowBit rows 1 6 2 && rowBit rows 1 6 4) &&
    !(rowBit rows 2 0 2 && rowBit rows 2 0 5 && rowBit rows 1 6 2 && rowBit rows 1 6 5) &&
    !(rowBit rows 2 0 3 && rowBit rows 2 0 4 && rowBit rows 1 6 3 && rowBit rows 1 6 4) &&
    !(rowBit rows 2 0 3 && rowBit rows 2 0 5 && rowBit rows 1 6 3 && rowBit rows 1 6 5) &&
    !(rowBit rows 2 0 4 && rowBit rows 2 0 5 && rowBit rows 1 6 4 && rowBit rows 1 6 5) &&
    !(rowBit rows 2 0 7 && rowBit rows 2 0 8 && rowBit rows 1 6 7 && rowBit rows 1 6 8) &&
    !(rowBit rows 2 0 7 && rowBit rows 2 0 9 && rowBit rows 1 6 7 && rowBit rows 1 6 9) &&
    !(rowBit rows 2 0 7 && rowBit rows 2 0 10 && rowBit rows 1 6 7 && rowBit rows 1 6 10) &&
    !(rowBit rows 2 0 7 && rowBit rows 2 0 11 && rowBit rows 1 6 7 && rowBit rows 1 6 11) &&
    !(rowBit rows 2 0 7 && rowBit rows 2 0 12 && rowBit rows 1 6 7 && rowBit rows 1 6 12) &&
    !(rowBit rows 2 0 8 && rowBit rows 2 0 9 && rowBit rows 1 6 8 && rowBit rows 1 6 9) &&
    !(rowBit rows 2 0 8 && rowBit rows 2 0 10 && rowBit rows 1 6 8 && rowBit rows 1 6 10) &&
    !(rowBit rows 2 0 8 && rowBit rows 2 0 11 && rowBit rows 1 6 8 && rowBit rows 1 6 11) &&
    !(rowBit rows 2 0 8 && rowBit rows 2 0 12 && rowBit rows 1 6 8 && rowBit rows 1 6 12) &&
    !(rowBit rows 2 0 9 && rowBit rows 2 0 10 && rowBit rows 1 6 9 && rowBit rows 1 6 10) &&
    !(rowBit rows 2 0 9 && rowBit rows 2 0 11 && rowBit rows 1 6 9 && rowBit rows 1 6 11) &&
    !(rowBit rows 2 0 9 && rowBit rows 2 0 12 && rowBit rows 1 6 9 && rowBit rows 1 6 12) &&
    !(rowBit rows 2 0 10 && rowBit rows 2 0 11 && rowBit rows 1 6 10 && rowBit rows 1 6 11) &&
    !(rowBit rows 2 0 10 && rowBit rows 2 0 12 && rowBit rows 1 6 10 && rowBit rows 1 6 12)

end Problem97.ATailExactFiveCard13BVCircuit
