/- Generated by generate_bv_circuit.py. -/
import ExactFiveCard13BVCircuitChunks.Base

namespace Problem97.ATailExactFiveCard13BVCircuit

set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false

def common009 (rows : RowBits) (blockers : BlockerBits) (shell : ShellBits) (q w : RoleBits) (b1 : FirstRowBits) (ranks : RankBits) : Bool :=
  !(rowBit rows 0 0 1 && rowBit rows 0 0 11 && rowBit rows 0 12 1 && rowBit rows 0 12 11) &&
    !(rowBit rows 0 0 2 && rowBit rows 0 0 3 && rowBit rows 0 12 2 && rowBit rows 0 12 3) &&
    !(rowBit rows 0 0 2 && rowBit rows 0 0 4 && rowBit rows 0 12 2 && rowBit rows 0 12 4) &&
    !(rowBit rows 0 0 2 && rowBit rows 0 0 5 && rowBit rows 0 12 2 && rowBit rows 0 12 5) &&
    !(rowBit rows 0 0 2 && rowBit rows 0 0 6 && rowBit rows 0 12 2 && rowBit rows 0 12 6) &&
    !(rowBit rows 0 0 2 && rowBit rows 0 0 7 && rowBit rows 0 12 2 && rowBit rows 0 12 7) &&
    !(rowBit rows 0 0 2 && rowBit rows 0 0 8 && rowBit rows 0 12 2 && rowBit rows 0 12 8) &&
    !(rowBit rows 0 0 2 && rowBit rows 0 0 9 && rowBit rows 0 12 2 && rowBit rows 0 12 9) &&
    !(rowBit rows 0 0 2 && rowBit rows 0 0 10 && rowBit rows 0 12 2 && rowBit rows 0 12 10) &&
    !(rowBit rows 0 0 2 && rowBit rows 0 0 11 && rowBit rows 0 12 2 && rowBit rows 0 12 11) &&
    !(rowBit rows 0 0 3 && rowBit rows 0 0 4 && rowBit rows 0 12 3 && rowBit rows 0 12 4) &&
    !(rowBit rows 0 0 3 && rowBit rows 0 0 5 && rowBit rows 0 12 3 && rowBit rows 0 12 5) &&
    !(rowBit rows 0 0 3 && rowBit rows 0 0 6 && rowBit rows 0 12 3 && rowBit rows 0 12 6) &&
    !(rowBit rows 0 0 3 && rowBit rows 0 0 7 && rowBit rows 0 12 3 && rowBit rows 0 12 7) &&
    !(rowBit rows 0 0 3 && rowBit rows 0 0 8 && rowBit rows 0 12 3 && rowBit rows 0 12 8) &&
    !(rowBit rows 0 0 3 && rowBit rows 0 0 9 && rowBit rows 0 12 3 && rowBit rows 0 12 9) &&
    !(rowBit rows 0 0 3 && rowBit rows 0 0 10 && rowBit rows 0 12 3 && rowBit rows 0 12 10) &&
    !(rowBit rows 0 0 3 && rowBit rows 0 0 11 && rowBit rows 0 12 3 && rowBit rows 0 12 11) &&
    !(rowBit rows 0 0 4 && rowBit rows 0 0 5 && rowBit rows 0 12 4 && rowBit rows 0 12 5) &&
    !(rowBit rows 0 0 4 && rowBit rows 0 0 6 && rowBit rows 0 12 4 && rowBit rows 0 12 6) &&
    !(rowBit rows 0 0 4 && rowBit rows 0 0 7 && rowBit rows 0 12 4 && rowBit rows 0 12 7) &&
    !(rowBit rows 0 0 4 && rowBit rows 0 0 8 && rowBit rows 0 12 4 && rowBit rows 0 12 8) &&
    !(rowBit rows 0 0 4 && rowBit rows 0 0 9 && rowBit rows 0 12 4 && rowBit rows 0 12 9) &&
    !(rowBit rows 0 0 4 && rowBit rows 0 0 10 && rowBit rows 0 12 4 && rowBit rows 0 12 10) &&
    !(rowBit rows 0 0 4 && rowBit rows 0 0 11 && rowBit rows 0 12 4 && rowBit rows 0 12 11) &&
    !(rowBit rows 0 0 5 && rowBit rows 0 0 6 && rowBit rows 0 12 5 && rowBit rows 0 12 6) &&
    !(rowBit rows 0 0 5 && rowBit rows 0 0 7 && rowBit rows 0 12 5 && rowBit rows 0 12 7) &&
    !(rowBit rows 0 0 5 && rowBit rows 0 0 8 && rowBit rows 0 12 5 && rowBit rows 0 12 8) &&
    !(rowBit rows 0 0 5 && rowBit rows 0 0 9 && rowBit rows 0 12 5 && rowBit rows 0 12 9) &&
    !(rowBit rows 0 0 5 && rowBit rows 0 0 10 && rowBit rows 0 12 5 && rowBit rows 0 12 10) &&
    !(rowBit rows 0 0 5 && rowBit rows 0 0 11 && rowBit rows 0 12 5 && rowBit rows 0 12 11) &&
    !(rowBit rows 0 0 6 && rowBit rows 0 0 7 && rowBit rows 0 12 6 && rowBit rows 0 12 7) &&
    !(rowBit rows 0 0 6 && rowBit rows 0 0 8 && rowBit rows 0 12 6 && rowBit rows 0 12 8) &&
    !(rowBit rows 0 0 6 && rowBit rows 0 0 9 && rowBit rows 0 12 6 && rowBit rows 0 12 9) &&
    !(rowBit rows 0 0 6 && rowBit rows 0 0 10 && rowBit rows 0 12 6 && rowBit rows 0 12 10) &&
    !(rowBit rows 0 0 6 && rowBit rows 0 0 11 && rowBit rows 0 12 6 && rowBit rows 0 12 11) &&
    !(rowBit rows 0 0 7 && rowBit rows 0 0 8 && rowBit rows 0 12 7 && rowBit rows 0 12 8) &&
    !(rowBit rows 0 0 7 && rowBit rows 0 0 9 && rowBit rows 0 12 7 && rowBit rows 0 12 9) &&
    !(rowBit rows 0 0 7 && rowBit rows 0 0 10 && rowBit rows 0 12 7 && rowBit rows 0 12 10) &&
    !(rowBit rows 0 0 7 && rowBit rows 0 0 11 && rowBit rows 0 12 7 && rowBit rows 0 12 11) &&
    !(rowBit rows 0 0 8 && rowBit rows 0 0 9 && rowBit rows 0 12 8 && rowBit rows 0 12 9) &&
    !(rowBit rows 0 0 8 && rowBit rows 0 0 10 && rowBit rows 0 12 8 && rowBit rows 0 12 10) &&
    !(rowBit rows 0 0 8 && rowBit rows 0 0 11 && rowBit rows 0 12 8 && rowBit rows 0 12 11) &&
    !(rowBit rows 0 0 9 && rowBit rows 0 0 10 && rowBit rows 0 12 9 && rowBit rows 0 12 10) &&
    !(rowBit rows 0 0 9 && rowBit rows 0 0 11 && rowBit rows 0 12 9 && rowBit rows 0 12 11) &&
    !(rowBit rows 0 0 10 && rowBit rows 0 0 11 && rowBit rows 0 12 10 && rowBit rows 0 12 11) &&
    !(rowBit rows 0 1 0 && rowBit rows 0 1 3 && rowBit rows 0 2 0 && rowBit rows 0 2 3) &&
    !(rowBit rows 0 1 0 && rowBit rows 0 1 4 && rowBit rows 0 2 0 && rowBit rows 0 2 4) &&
    !(rowBit rows 0 1 0 && rowBit rows 0 1 5 && rowBit rows 0 2 0 && rowBit rows 0 2 5) &&
    !(rowBit rows 0 1 0 && rowBit rows 0 1 6 && rowBit rows 0 2 0 && rowBit rows 0 2 6) &&
    !(rowBit rows 0 1 0 && rowBit rows 0 1 7 && rowBit rows 0 2 0 && rowBit rows 0 2 7) &&
    !(rowBit rows 0 1 0 && rowBit rows 0 1 8 && rowBit rows 0 2 0 && rowBit rows 0 2 8) &&
    !(rowBit rows 0 1 0 && rowBit rows 0 1 9 && rowBit rows 0 2 0 && rowBit rows 0 2 9) &&
    !(rowBit rows 0 1 0 && rowBit rows 0 1 10 && rowBit rows 0 2 0 && rowBit rows 0 2 10) &&
    !(rowBit rows 0 1 0 && rowBit rows 0 1 11 && rowBit rows 0 2 0 && rowBit rows 0 2 11) &&
    !(rowBit rows 0 1 0 && rowBit rows 0 1 12 && rowBit rows 0 2 0 && rowBit rows 0 2 12) &&
    !(rowBit rows 0 1 3 && rowBit rows 0 1 4 && rowBit rows 0 2 3 && rowBit rows 0 2 4) &&
    !(rowBit rows 0 1 3 && rowBit rows 0 1 5 && rowBit rows 0 2 3 && rowBit rows 0 2 5) &&
    !(rowBit rows 0 1 3 && rowBit rows 0 1 6 && rowBit rows 0 2 3 && rowBit rows 0 2 6) &&
    !(rowBit rows 0 1 3 && rowBit rows 0 1 7 && rowBit rows 0 2 3 && rowBit rows 0 2 7) &&
    !(rowBit rows 0 1 3 && rowBit rows 0 1 8 && rowBit rows 0 2 3 && rowBit rows 0 2 8) &&
    !(rowBit rows 0 1 3 && rowBit rows 0 1 9 && rowBit rows 0 2 3 && rowBit rows 0 2 9) &&
    !(rowBit rows 0 1 3 && rowBit rows 0 1 10 && rowBit rows 0 2 3 && rowBit rows 0 2 10) &&
    !(rowBit rows 0 1 3 && rowBit rows 0 1 11 && rowBit rows 0 2 3 && rowBit rows 0 2 11)

end Problem97.ATailExactFiveCard13BVCircuit
