import Mathlib
#check Finset.card_eq_two
#check Finset.card_eq_two.mp
#check Finset.card_eq_two.mpr
#check Finset.card_eq_two_iff
#check Finset.card_eq_two
#check Finset.card_sdiff_of_subset
#check Finset.card_sdiff_add_card_eq_card
#check Finset.card_union_of_disjoint
#check Finset.card_biUnion
#check Finset.card_congr
#check Finset.card_le_card
#check Finset.card_le_three
#check Finset.card_eq_one
#check Finset.card_eq_zero
#check Finset.card_inter_le
#check Finset.card_union_le
#check Finset.card_union_add_card_inter
#check Finset.card_union_of_disjoint
#check Finset.disjoint_left
#check Finset.mem_union
#check Finset.mem_inter
#check Finset.mem_sdiff
#check Finset.subset_iff
#check Finset.ssubset_iff_subset_ne
#check Finset.card_pos
#check Finset.card_le_one
#check Finset.card_le_two
