import Erdos9796Proof.P97.ATail.CapCrossingKalmanson
import Erdos9796Proof.P97.ATail.EndpointFreshFiveRoleKalmanson
import Erdos9796Proof.P97.ATail.FivePointEuclideanObstruction
import Erdos9796Proof.P97.ATail.KalmansonThreeEqualitySchemas
import Erdos9796Proof.P97.ATail.TwoCenterBisectorParity

open Problem97
open Problem97.CapCrossingKalmansonBridge
open Problem97.EndpointFreshFiveRoleKalmanson

#print axioms false_of_five_ccw_three_shell_equalities
#print axioms false_of_six_ccw_three_shell_equalities_013_412_523
#print axioms false_of_six_ccw_three_shell_equalities_012_325_415
#print axioms false_of_five_ccw_three_shell_equalities_012_124_314
#print axioms false_of_six_ccw_three_shell_equalities_013_235_415
#print axioms false_of_five_ccw_three_shell_equalities_043_431_241
#print axioms false_of_five_ccw_three_shell_equalities_302_021_410
#print axioms Problem97.FivePointEuclideanObstruction.false_of_five_ccw_three_row_equalities
#print axioms Problem97.FivePointEuclideanObstruction.false_of_five_ccw_second_three_row_equalities
#print axioms false_of_two_centers_equidistant_pair_after
#print axioms false_of_two_centers_equidistant_pair_enclosed
#print axioms false_of_two_centers_equidistant_pair_split
#print axioms false_of_two_centers_equidistant_pair_before
#print axioms false_of_center_first_two_k2_three_selected_rows_triangle
#print axioms false_of_center_first_two_k2_three_selected_rows_triangle_reflected
#print axioms false_of_support_first_two_k2_three_selected_rows_triangle
#print axioms false_of_support_first_two_k2_three_selected_rows_triangle_reflected
