import Erdos9796Proof.P97.ATail.FiniteN11Frontier

#print axioms Problem97.ATailFiniteN11Frontier.false_of_frontierCommonDeletionPhysicalSecondApex_of_card_eq_eleven
#print axioms Problem97.ATailFiniteN11Frontier.false_of_firstApexUniqueRadiusExactFiveCommonObstructionCenterResidual_of_card_eq_eleven_s2_o0
#print axioms Problem97.ATailFiniteN11Frontier.false_of_firstApexUniqueRadiusExactFiveCommonObstructionCenterResidual_of_card_eq_eleven
#print axioms Problem97.ATailFiniteN11Frontier.false_of_originalFrontierUniqueRadiusArm_of_card_eq_eleven
#print axioms Problem97.ATailFiniteN11Frontier.false_of_criticalPairFrontier_of_card_eq_eleven
#print axioms Problem97.ATailFiniteN11Frontier.false_of_twoLargeCaps_commonCriticalMap_of_card_eq_eleven
