import Erdos9796Proof.P97.ATail.FrontierLiveClosure

open scoped BigOperators

#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.freshThirdCapSourceNonHit_center_ne_of_sourceRowOmission
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.exists_freshThird_retained_minimalDeletionCoreProducer
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.nonempty_freshThird_fixedQ_commonDeletionPacket_of_alignedSurvivals
