import Erdos9796Proof.P97.ATail.FrontierLiveClosure
open Problem97
open Problem97.ATailFrontierLiveClosure
#check Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.freshThirdNormalizedResidualCase_of_crossRowResidual
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.freshThirdNormalizedResidualCase_of_crossRowResidual
#check Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.FreshThirdTwoCapSourceObstruction.residualCase_of_isResidual
#check Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.FreshThirdTwoCapSourceObstruction.isResidual_of_not_hasDistinctCrossRows
