import Erdos9796Proof.P97.ATail.FrontierLiveClosure.TwoSourceFreshThirdResidual

#print axioms Problem97.SelectedFourCapWitnessPacket.isCapWitnessPair
#print axioms Problem97.SelectedFourClass.nonempty_capWitnessPacket_of_two_mem
#print axioms Problem97.SelectedFourClass.cospherical_of_mem
#print axioms Problem97.SelectedFourClass.ptolemy_of_opposite_angles
#print axioms Problem97.Census554.GeneralCarrierBridge.BoundaryIndexing.selectedFourSupportIndices_card
#print axioms Problem97.Census554.GeneralCarrierBridge.BoundaryIndexing.boundary_selectedFourSupportOrder_mem
#print axioms Problem97.Census554.GeneralCarrierBridge.BoundaryIndexing.exists_selectedFourSupportOrder_boundary_eq
#print axioms Problem97.Census554.GeneralCarrierBridge.BoundaryIndexing.image_boundary_selectedFourSupportOrder
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.FreshThirdPinnedEndpointOutsideSeedQueryPacket.firstCapWitnessPacket
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.FreshThirdPinnedEndpointOutsideSeedQueryPacket.firstCapWitnessPacket_or_card_le_one
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.freshThird_commonRadius_sameBlocker_exists_centerCollision_or_commonDeletion
