import Erdos9796Proof.P97.ATail.FrontierLiveClosure
open Problem97
open Problem97.ATailFrontierLiveClosure
open Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal
#check Problem97.ATailFrontierLiveClosure.endpointFresh_exists_criticalRow_escape_or_fullyDeletionRobust_twoShellSeed
#check Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.endpointFresh_escape_with_sourceFaithful_cover_twoShellSeed
#print axioms Problem97.ATailFrontierLiveClosure.endpointFresh_exists_criticalRow_escape_or_fullyDeletionRobust_twoShellSeed
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.endpointFresh_escape_with_sourceFaithful_cover_twoShellSeed
#check Problem97.ATailFrontierLiveClosure.endpointFresh_exists_selectedRow_escape_twoShellSeed
