import Erdos9796Proof.P97.ATail.FrontierLiveClosure.Coordinator
#print axioms Problem97.ATailFrontierLiveClosure.false_of_exactFourCollision_interior_eq_two_secondRadius_and_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.false_of_exactFourCollision_interior_eq_two_secondRadius_and_all_low_hits_coordinator
