import Erdos9796Proof.P97.ATail.FrontierLiveClosure

open scoped EuclideanGeometry
open Problem97

#check Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.freshThirdEqualCenterExactFourRow_of_hits
#check Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_freshThirdEqualCenter_sameCapOppIndex
#check Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_twoCapSources_freshThirdBlockerFiber_normalized_remaining
#check Problem97.CapSelectedRowCounting.selectedFourClass_inter_capByIndex_card_le_two
#check Problem97.Census554.GeneralCarrierBridge.exists_boundaryIndexing
#check Problem97.SurplusCOMPGBank.btw
#check Problem97.SurplusCapPacket.capInteriorByIndex_open_interval_of_global_indices
