import Erdos9796Proof.P97.ATail.FrontierLiveClosure

#check Problem97.ATailFrontierLiveClosure.false_of_exactFourCollision_interior_eq_two_secondRadius_and_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.false_of_exactFourCollision_interior_eq_two_secondRadius_and_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.false_of_retainedInteriorDirectedOmission_and_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_two_exactFourInteriorTwo_distinctRadiusBlockerCollisions_and_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.exists_distinctRadius_commonDeletionParent
#check Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_twoCapSources_freshThirdBlockerFiber_normalized_remaining
#print axioms Problem97.ATailFrontierLiveClosure.false_of_twoCapSources_freshThirdBlockerFiber_core_commonRadius
#print axioms Problem97.ATailFrontierLiveClosure.false_of_twoCapSources_freshThirdBlockerFiber_residual
#print axioms Problem97.ATailFrontierLiveClosure.false_of_twoCapSources_freshThirdBlockerFiber
