import Erdos9796Proof.P97.ATail.FrontierLiveClosure.TwoSourceFirstFiberCollision

open scoped BigOperators
open Problem97
open Problem97.ATailFrontierLiveClosure
open Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal

#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.firstFiberOutsidePair_exactRows_or_crossed
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.firstFiberOutsidePair_exactRows_or_crossedThreeRows
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_capSource_firstFiber_collisionFiveCenterDeletion
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_twoCapSources_sameBlockerAllEndpointOmission
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.exists_freshThird_pinnedCenter_allRows_escape_tripleShellSeed
