import Erdos9796Proof.P97.ATail.FrontierLiveClosure.TwoSourceFreshThirdRetainedProducer

/-! Axiom audit for the source-clean FreshThird retained producer API. -/

#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.freshThird_exists_fourHits_strict_cross_distance
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.firstFiberCapSource_not_mem_firstApex_multiPointRadius_of_aligned
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.oppApex1_rich_exactRetainedRadii_of_aligned
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.freshThird_alignedRetainedConsumerPacket_oppApex1_rich_exactRetainedRadii
