import Erdos9796Proof.P97.ATail.BlockerVExactSeventeenSourceCnfCdefg

#print axioms Problem97.ATailBlockerVExactSeventeenSourceCnfCdefg.sourceAssign_cdefgClauses
#print axioms Problem97.ATailBlockerVExactSeventeenSourceCnfCdefg.sourceAssign_extendedCnf
#print axioms Problem97.ATailBlockerVExactSeventeenSourceCnfCdefg.SourceRealization.extendedCnf_sat
#print axioms Problem97.ATailBlockerVExactSeventeenSourceCnfCdefg.false_of_sourceRealization_of_extendedCnf_unsat
