import Erdos9796Proof.P97.ATail.FrontierLiveClosure.Rigid221SourceHeavy
import Erdos9796Proof.P97.ATail.BlockerVExactSeventeenThirtyFirstModelRefinements

#print axioms Problem97.ATailFrontierLiveClosure.exists_exactSeventeenSourceRealization_of_exactCover
#print axioms Problem97.ATailBlockerVExactSeventeenThirtyFirstModelRefinements.sourceAssign_extendedThirtyFirstModelRefinementsCnf
#print axioms Problem97.ATailBlockerVExactSeventeenThirtyFirstModelRefinements.false_of_sourceRealization_of_extendedThirtyFirstModelRefinementsCnf_unsat
