import Erdos9796Proof.P97.ATail.FrontierLiveClosure.ExactTwelveRigid221FiveOmissionTerminalBankConsumer

#print axioms Problem97.ATailFrontierLiveClosure.GenericRowNogoodCertificate.nonempty_equalK4Core_of_positiveCheck
#print axioms Problem97.ATailFrontierLiveClosure.ExactTwelveRigid221Ingress.FiveOmissionTerminalBankConsumer.SourceOrderPositiveNogood.ofEqualK4Core
#print axioms Problem97.ATailFrontierLiveClosure.ExactTwelveRigid221Ingress.FiveOmissionTerminalBankConsumer.SourceOrderPositiveNogood.ofEqualK4Certificate
