import Erdos9796Proof.P97.ATail.FrontierLiveClosure.ExactTwelveRigid221SurplusPairSecondOppositeApexPairCommonFiveMembershipFamilyCnf

open Problem97 ATailFrontierLiveClosure

#print axioms Problem97.ATailFrontierLiveClosure.ExactTwelveRigid221Ingress.FrozenBoundaryOrder.commonFiveOrientation_surplusPairSecondOppositeApexPair
#print axioms Problem97.ATailFrontierLiveClosure.ExactTwelveRigid221Ingress.SurplusPairSecondOppositeApexPairCommonFiveMembershipFamilyCnf.implicationDimacs_sat
#print axioms Problem97.ATailFrontierLiveClosure.ExactTwelveRigid221Ingress.SurplusPairSecondOppositeApexPairCommonFiveMembershipFamilyCnf.family_shape
#print axioms Problem97.ATailFrontierLiveClosure.ExactTwelveRigid221Ingress.SurplusPairSecondOppositeApexPairCommonFiveMembershipFamilyCnf.false_of_blockingClause_false
