import LambdaKxFine.N088FamilyPart00

/-! Bucket aggregate for lambda Kx node 88. -/

namespace Problem97.ATailBankCleanLambdaKxFine

set_option maxHeartbeats 80000000

set_option maxRecDepth 100000

set_option linter.unusedVariables false

noncomputable section

@[simp] def lambdaKxFineNode88AggL0Part0 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((0 + lambdaKxFineNode88Part1 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part2 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part3 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part4 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part5 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part6 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + 0))) + (((0 + 0) + (lambdaKxFineNode88Part10 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part11 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((0 + lambdaKxFineNode88Part13 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part14 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part15 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode88Part16 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part17 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part18 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part19 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part20 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part21 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part22 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part23 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode88Part24 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part25 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part26 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part27 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part28 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part29 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part30 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part31 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode88AggL0Part1 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode88Part32 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part33 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part34 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part35 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part36 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part37 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part38 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part39 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode88Part40 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part41 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part42 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part43 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part44 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part45 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part46 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part47 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode88Part48 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part49 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part50 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part51 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part52 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part53 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part54 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part55 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode88Part56 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part57 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part58 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part59 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part60 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part61 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part62 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part63 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode88AggL0Part2 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode88Part64 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part65 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part66 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part67 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part68 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part69 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part70 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part71 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode88Part72 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part73 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part74 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part75 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part76 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part77 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part78 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part79 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode88Part80 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part81 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part82 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part83 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part84 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part85 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part86 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part87 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode88Part88 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part89 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part90 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part91 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part92 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part93 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part94 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part95 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode88AggL0Part3 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode88Part96 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part97 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part98 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part99 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part100 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part101 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part102 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part103 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode88Part104 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part105 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part106 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part107 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part108 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part109 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part110 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part111 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode88Part112 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part113 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part114 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part115 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part116 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part117 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part118 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part119 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode88Part120 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part121 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part122 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part123 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part124 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part125 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part126 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part127 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode88AggL0Part4 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  ((((lambdaKxFineNode88Part128 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode88Part129 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part130 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + (lambdaKxFineNode88Part131 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode88Part132 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part133 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + ((lambdaKxFineNode88Part134 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode88Part135 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part136 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode88Part137 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part138 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88Part139 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88Part140 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + (((0 + (0 + 0)) + (0 + (0 + 0))) + ((0 + (0 + 0)) + ((0 + 0) + (0 + 0)))))

@[simp] def lambdaKxFineNode88Value (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  ((lambdaKxFineNode88AggL0Part0 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88AggL0Part1 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode88AggL0Part2 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode88AggL0Part3 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode88AggL0Part4 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))

end

end Problem97.ATailBankCleanLambdaKxFine
