import LambdaKxFine.N095FamilyPart00

/-! Bucket aggregate for lambda Kx node 95. -/

namespace Problem97.ATailBankCleanLambdaKxFine

set_option maxHeartbeats 80000000

set_option maxRecDepth 100000

set_option linter.unusedVariables false

noncomputable section

@[simp] def lambdaKxFineNode95AggL0Part0 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((0 + 0) + (0 + 0)) + ((0 + 0) + (0 + 0))) + (((0 + 0) + (0 + 0)) + ((0 + 0) + (0 + 0)))) + ((((0 + 0) + (0 + 0)) + ((0 + 0) + (0 + 0))) + (((0 + 0) + (lambdaKxFineNode95Part26 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + 0)) + ((lambdaKxFineNode95Part28 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + 0) + (0 + lambdaKxFineNode95Part31 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode95AggL0Part1 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode95Part32 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part33 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part34 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part35 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part36 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + 0) + (lambdaKxFineNode95Part38 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + 0))) + (((0 + 0) + (0 + lambdaKxFineNode95Part43 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part44 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part45 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (0 + 0)))) + ((((lambdaKxFineNode95Part48 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part49 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part50 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part51 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part52 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part53 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part54 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + 0))) + (((lambdaKxFineNode95Part56 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part57 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part58 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part59 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part60 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part61 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part62 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part63 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode95AggL0Part2 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode95Part64 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part65 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part66 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part67 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part68 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part69 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part70 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part71 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode95Part72 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part73 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part74 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part75 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part76 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part77 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part78 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part79 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode95Part80 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part81 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part82 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part83 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part84 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part85 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part86 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part87 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode95Part88 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part89 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part90 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part91 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part92 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part93 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part94 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part95 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode95AggL0Part3 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode95Part96 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part97 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part98 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part99 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part100 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part101 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part102 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part103 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode95Part104 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part105 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part106 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part107 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part108 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part109 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part110 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part111 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode95Part112 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part113 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part114 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part115 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part116 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part117 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part118 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part119 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode95Part120 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part121 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part122 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part123 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part124 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part125 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part126 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part127 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode95AggL0Part4 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  ((((lambdaKxFineNode95Part128 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode95Part129 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part130 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + (lambdaKxFineNode95Part131 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode95Part132 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part133 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + ((lambdaKxFineNode95Part134 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode95Part135 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part136 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part137 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part138 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part139 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part140 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + (((lambdaKxFineNode95Part141 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode95Part142 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part143 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + (lambdaKxFineNode95Part144 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode95Part145 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part146 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + ((lambdaKxFineNode95Part147 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode95Part148 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part149 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode95Part150 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part151 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95Part152 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95Part153 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode95Value (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  ((lambdaKxFineNode95AggL0Part0 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95AggL0Part1 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode95AggL0Part2 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode95AggL0Part3 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode95AggL0Part4 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))

end

end Problem97.ATailBankCleanLambdaKxFine
