import LambdaKxFine.N135FamilyPart00

import LambdaKxFine.N135FamilyPart01

/-! Bucket aggregate for lambda Kx node 135. -/

namespace Problem97.ATailBankCleanLambdaKxFine

set_option maxHeartbeats 80000000

set_option maxRecDepth 100000

set_option linter.unusedVariables false

noncomputable section

@[simp] def lambdaKxFineNode135AggL0Part0 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((0 + lambdaKxFineNode135Part1 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part2 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part3 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part4 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part5 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part6 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + 0))) + (((0 + lambdaKxFineNode135Part9 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part10 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part11 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part12 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part13 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part14 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part15 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode135Part16 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part17 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part18 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part19 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part20 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part21 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part22 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part23 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode135Part24 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part25 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part26 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part27 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part28 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part29 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part30 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part31 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode135AggL0Part1 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode135Part32 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part33 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part34 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part35 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part36 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part37 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part38 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part39 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode135Part40 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part41 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part42 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part43 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part44 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part45 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part46 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part47 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode135Part48 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part49 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part50 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part51 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part52 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part53 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part54 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part55 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode135Part56 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part57 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part58 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part59 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part60 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part61 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part62 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part63 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode135AggL0Part2 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode135Part64 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part65 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part66 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part67 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part68 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part69 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part70 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part71 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode135Part72 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part73 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part74 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part75 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part76 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part77 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part78 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part79 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode135Part80 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part81 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part82 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part83 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part84 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part85 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part86 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part87 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode135Part88 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part89 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part90 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part91 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part92 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part93 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part94 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part95 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode135AggL0Part3 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode135Part96 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part97 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part98 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part99 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part100 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part101 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part102 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part103 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode135Part104 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part105 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part106 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part107 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part108 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part109 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part110 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part111 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode135Part112 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part113 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part114 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part115 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part116 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part117 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part118 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part119 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode135Part120 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part121 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part122 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part123 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part124 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part125 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part126 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part127 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode135AggL0Part4 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  ((((lambdaKxFineNode135Part128 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode135Part129 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part130 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + (lambdaKxFineNode135Part131 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode135Part132 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part133 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + ((lambdaKxFineNode135Part134 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode135Part135 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part136 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part137 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part138 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part139 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part140 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + (((lambdaKxFineNode135Part141 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode135Part142 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part143 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + (lambdaKxFineNode135Part144 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode135Part145 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part146 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + ((lambdaKxFineNode135Part147 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode135Part148 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part149 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode135Part150 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part151 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135Part152 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135Part153 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode135Value (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  ((lambdaKxFineNode135AggL0Part0 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135AggL0Part1 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode135AggL0Part2 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode135AggL0Part3 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode135AggL0Part4 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))

end

end Problem97.ATailBankCleanLambdaKxFine
