import LambdaKxFine.N136FamilyPart00

import LambdaKxFine.N136FamilyPart01

/-! Bucket aggregate for lambda Kx node 136. -/

namespace Problem97.ATailBankCleanLambdaKxFine

set_option maxHeartbeats 80000000

set_option maxRecDepth 100000

set_option linter.unusedVariables false

noncomputable section

@[simp] def lambdaKxFineNode136AggL0Part0 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode136Part0 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part1 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part2 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part3 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part4 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part5 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part6 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part7 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode136Part8 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part9 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part10 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part11 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part12 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part13 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part14 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part15 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode136Part16 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part17 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part18 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part19 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part20 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part21 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part22 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part23 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode136Part24 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part25 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part26 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part27 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part28 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part29 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part30 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part31 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode136AggL0Part1 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode136Part32 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part33 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part34 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part35 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part36 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part37 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part38 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part39 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode136Part40 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part41 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part42 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part43 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part44 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part45 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part46 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part47 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode136Part48 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part49 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part50 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part51 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part52 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part53 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part54 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part55 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode136Part56 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part57 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part58 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part59 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part60 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part61 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part62 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part63 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode136AggL0Part2 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode136Part64 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part65 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part66 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part67 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part68 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part69 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part70 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part71 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode136Part72 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part73 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part74 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part75 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part76 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part77 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part78 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part79 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode136Part80 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part81 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part82 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part83 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part84 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part85 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part86 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part87 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode136Part88 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part89 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part90 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part91 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part92 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part93 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part94 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part95 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode136AggL0Part3 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  (((((lambdaKxFineNode136Part96 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part97 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part98 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part99 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part100 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part101 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part102 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part103 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode136Part104 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part105 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part106 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part107 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part108 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part109 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part110 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part111 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + ((((lambdaKxFineNode136Part112 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part113 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part114 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part115 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part116 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part117 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part118 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part119 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + (((lambdaKxFineNode136Part120 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part121 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part122 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part123 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part124 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part125 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part126 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part127 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode136AggL0Part4 (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  ((((lambdaKxFineNode136Part128 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode136Part129 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part130 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + (lambdaKxFineNode136Part131 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode136Part132 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part133 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + ((lambdaKxFineNode136Part134 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode136Part135 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part136 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part137 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part138 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part139 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part140 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))) + (((lambdaKxFineNode136Part141 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode136Part142 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part143 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + (lambdaKxFineNode136Part144 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode136Part145 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part146 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx))) + ((lambdaKxFineNode136Part147 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode136Part148 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part149 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)) + ((lambdaKxFineNode136Part150 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part151 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136Part152 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136Part153 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))))

@[simp] def lambdaKxFineNode136Value (Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx : ℝ) : ℝ :=
  ((lambdaKxFineNode136AggL0Part0 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136AggL0Part1 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx) + (lambdaKxFineNode136AggL0Part2 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + (lambdaKxFineNode136AggL0Part3 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx + lambdaKxFineNode136AggL0Part4 Ky Fx Fy Xy Zx Kx Yx Yy Zy L Xx)))

end

end Problem97.ATailBankCleanLambdaKxFine
