import Erdos9796Proof.P97.ATail.FivePointEuclideanObstruction
import Erdos9796Proof.P97.ATail.KalmansonRadiusOrderReversal

#check Problem97.FivePointEuclideanObstruction.false_of_five_ccw_second_three_row_equalities
#check Problem97.FivePointEuclideanObstruction.false_of_five_ccw_second_two_selected_rows
#check Problem97.KalmansonRadiusOrderReversal.false_of_seven_ccw_radius_order_reversal_equalities
#check Problem97.KalmansonRadiusOrderReversal.false_of_three_selected_rows_seven_ccw_radius_order_reversal
#print axioms Problem97.FivePointEuclideanObstruction.false_of_five_ccw_second_three_row_equalities
#print axioms Problem97.KalmansonRadiusOrderReversal.false_of_seven_ccw_radius_order_reversal_equalities
