/-
Copyright (c) 2026 Adam McKenna. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam McKenna
-/
import Erdos9796Proof.P97.Census554.CertCheck

/-!
# Census-554 bank certificate replay: `pat_02213`

Auto-generated by `scratch/census-554/gen_lean_certs.py` from
`scratch/census-554/certs/pat_02213.json`.
Schema `census554_pattern_certificate.v1`.  Do not edit by hand.
-/

set_option linter.style.longLine false
set_option linter.style.nativeDecide false
-- Large certificates need headroom over the default 200000-heartbeat
-- budget even with chunked coefficient defs.
set_option maxHeartbeats 1000000

namespace Problem97
namespace Census554
namespace Bank

/-- Pattern of banked certificate `pat_02213` (kill: base). -/
def pat02213 : Pattern := fun c =>
  if c = 0 then {1, 9, 10}
  else if c = 9 then {0, 1}
  else if c = 10 then {0, 1, 9}
  else ∅

/-- Rabinowitsch pairs of `pat_02213`, in certificate order. -/
def rabPairs02213 : List (Fin 11 × Fin 11) :=
  []

/-- Generator tags of `pat_02213`, in bank order. -/
def tags02213 : List CertTag :=
  [.eq 0 1 9, .eq 0 1 10, .eq 9 0 1, .eq 10 0 1, .eq 10 0 9]

/-- Coefficient 0 of `pat_02213`. -/
def coeffs02213_c0 : SPoly :=
  [([], 5/4), ([(15, 1), (17, 1)], -1)]

/-- Coefficient 1 of `pat_02213`. -/
def coeffs02213_c1 : SPoly :=
  [([(15, 2)], 2)]

/-- Coefficient 2 of `pat_02213`. -/
def coeffs02213_c2 : SPoly :=
  [([], 1/4), ([(14, 1)], 3/4), ([(15, 1), (17, 1)], -1/2)]

/-- Coefficient 3 of `pat_02213`. -/
def coeffs02213_c3 : SPoly :=
  [([(14, 1)], -1/4), ([(14, 1), (15, 1), (17, 1)], -1), ([(15, 2)], 1/2),
      ([(15, 2), (16, 1)], 1)]

/-- Coefficient 4 of `pat_02213`. -/
def coeffs02213_c4 : SPoly :=
  [([], 1/4), ([(15, 1), (17, 1)], 1)]

/-- Coefficient polynomials of `pat_02213`, in bank order (flat variable
indices `x{p}x = 2(p-2)`, `x{p}y = 2(p-2)+1`, `t{j} = 18+j`). -/
def coeffs02213 : List SPoly :=
  [coeffs02213_c0, coeffs02213_c1, coeffs02213_c2, coeffs02213_c3, coeffs02213_c4]

/-- Certificate replay: pattern `pat_02213` is dead. -/
theorem isDead_pat02213 : IsDead pat02213 :=
  isDead_of_checkCert pat02213 rabPairs02213 tags02213 coeffs02213
    (by native_decide)

end Bank
end Census554
end Problem97
