/-
Copyright (c) 2026 Adam McKenna. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam McKenna
-/
import Erdos9796Proof.P97.Census554.CertCheck

/-!
# Census-554 bank certificate replay: `pat_02682`

Auto-generated by `scratch/census-554/gen_lean_certs.py` from
`scratch/census-554/certs/pat_02682.json`.
Schema `census554_pattern_certificate.v1`.  Do not edit by hand.
-/

set_option linter.style.longLine false
set_option linter.style.nativeDecide false
-- Large certificates need headroom over the default 200000-heartbeat
-- budget even with chunked coefficient defs.
set_option maxHeartbeats 1000000

namespace Problem97
namespace Census554
namespace Bank

/-- Pattern of banked certificate `pat_02682` (kill: pair:6-7). -/
def pat02682 : Pattern := fun c =>
  if c = 0 then {1, 6, 7}
  else if c = 1 then {3, 6, 7}
  else if c = 3 then {0, 1}
  else if c = 6 then {0, 3}
  else if c = 7 then {0, 3}
  else ∅

/-- Rabinowitsch pairs of `pat_02682`, in certificate order. -/
def rabPairs02682 : List (Fin 11 × Fin 11) :=
  [(6, 7)]

/-- Generator tags of `pat_02682`, in bank order. -/
def tags02682 : List CertTag :=
  [.eq 0 1 6, .eq 0 1 7, .eq 1 3 6, .eq 1 3 7, .eq 3 0 1, .eq 6 0 3, .eq 7 0 3,
   .rab 0 6 7]

/-- Coefficient 0 of `pat_02682`. -/
def coeffs02682_c0 : SPoly :=
  [([(3, 1), (11, 1), (18, 1)], -6/5), ([(10, 1), (18, 1)], 1),
      ([(11, 2), (18, 1)], 8/5), ([(18, 1)], -1)]

/-- Coefficient 1 of `pat_02682`. -/
def coeffs02682_c1 : SPoly :=
  [([(3, 1), (11, 1), (18, 1)], 6/5), ([(9, 1), (11, 1), (18, 1)], -8/5),
      ([(10, 1), (18, 1)], -1), ([(18, 1)], 1)]

/-- Coefficient 2 of `pat_02682`. -/
def coeffs02682_c2 : SPoly :=
  [([(3, 1), (11, 1), (18, 1)], 6/5), ([(10, 1), (18, 1)], -1),
      ([(11, 2), (18, 1)], -8/5)]

/-- Coefficient 3 of `pat_02682`. -/
def coeffs02682_c3 : SPoly :=
  [([(3, 1), (11, 1), (18, 1)], -6/5), ([(9, 1), (11, 1), (18, 1)], 8/5),
      ([(10, 1), (18, 1)], 1)]

/-- Coefficient 4 of `pat_02682`. -/
def coeffs02682_c4 : SPoly :=
  [([(2, 1), (9, 1), (11, 1), (18, 1)], -12/5), ([(2, 1), (11, 2), (18, 1)], 12/5),
      ([(3, 1), (8, 1), (11, 1), (18, 1)], 12/5),
      ([(3, 1), (10, 1), (11, 1), (18, 1)], -12/5), ([(8, 1), (11, 2), (18, 1)], -16/5),
      ([(9, 1), (10, 1), (11, 1), (18, 1)], 16/5), ([(9, 1), (11, 1), (18, 1)], 2/5),
      ([(11, 2), (18, 1)], -2/5)]

/-- Coefficient 5 of `pat_02682`. -/
def coeffs02682_c5 : SPoly :=
  [([(3, 1), (11, 1), (18, 1)], -12/5), ([(11, 2), (18, 1)], 16/5)]

/-- Coefficient 6 of `pat_02682`. -/
def coeffs02682_c6 : SPoly :=
  [([(3, 1), (11, 1), (18, 1)], 12/5), ([(9, 1), (11, 1), (18, 1)], -16/5)]

/-- Coefficient 7 of `pat_02682`. -/
def coeffs02682_c7 : SPoly :=
  [([], -1)]

/-- Coefficient polynomials of `pat_02682`, in bank order (flat variable
indices `x{p}x = 2(p-2)`, `x{p}y = 2(p-2)+1`, `t{j} = 18+j`). -/
def coeffs02682 : List SPoly :=
  [coeffs02682_c0, coeffs02682_c1, coeffs02682_c2, coeffs02682_c3, coeffs02682_c4,
   coeffs02682_c5, coeffs02682_c6, coeffs02682_c7]

/-- Certificate replay: pattern `pat_02682` is dead. -/
theorem isDead_pat02682 : IsDead pat02682 :=
  isDead_of_checkCert pat02682 rabPairs02682 tags02682 coeffs02682
    (by native_decide)

end Bank
end Census554
end Problem97
