import Erdos9796Proof.P97.ATail.CriticalPairFrontier

/-! Axiom audit for the production ATAIL rank-one normal forms. -/

#print axioms Problem97.ATailCriticalPairFrontier.cross_deletion_survives_or_cross_membership
#print axioms Problem97.ATailCriticalPairFrontier.signedArea_product_neg_of_cross_membership
#print axioms Problem97.ATailCriticalPairFrontier.card_five_cross_deletion_survives_or_cross_oppositeSide
#print axioms Problem97.ATailCriticalPairFrontier.cumulative_deletion_blocked_at_source_blocker
#print axioms Problem97.ATailCriticalPairFrontier.cross_deletion_survives_iff_not_mem_selected_support
#print axioms Problem97.ATailCriticalPairFrontier.SurvivorPairRelocationPacket.blocker_dist_ne_of_cross_deletion_survives
#print axioms Problem97.ATailCriticalPairFrontier.cross_survival_unique_radius_and_exact_support
#print axioms Problem97.ATailCriticalPairFrontier.blocker_centers_ne_of_not_mem_other_selected_support
#print axioms Problem97.ATailCriticalPairFrontier.selected_support_inter_card_le_two_of_not_mem_other_selected_support
#print axioms Problem97.ATailCriticalPairFrontier.blocker_centers_eq_of_first_apex_deletion_survives_of_mutual_cross_membership
#print axioms Problem97.ATailCriticalPairFrontier.blocker_centers_eq_iff_mutual_cross_membership_of_first_apex_deletion_survives
#print axioms Problem97.ATailCriticalPairFrontier.blocker_centers_eq_iff_mutual_cross_membership_of_first_apex_double_deletion_survives
#print axioms Problem97.ATailCriticalPairFrontier.blocker_centers_eq_of_five_le_of_mutual_cross_membership
#print axioms Problem97.ATailCriticalPairFrontier.blocker_centers_eq_iff_mutual_cross_membership_of_five_le
