/- Generated by `generate_rank_instances.py`; do not edit. -/
import RankSourceAdapters

/-! Exact generated complete-class rank assertion chunk 001. -/

namespace Problem97
namespace ATailExactFiveCard13DistinctRadiusSourceIngressScratch

open ATailCriticalPairFrontier
open ATailBiApexRobustCapBounds
open ATailExactFiveCard13CnfIngressScratch
open ATailExactFiveCard13CommonLabelTransportScratch
open ATailExactFiveFirstApexCard13ParentRowCouplingScratch
open ATailExactFiveFirstApexCard13Scratch
open ATailExactFiveGlobalCrossDeletionPair
open ATailExactFiveGlobalCoverStarGeometry
open ATailExactFiveMutualOneHitGeometry
open ATailFirstApexShellRole
open ATailKalmansonParentOrderScratch
open ATailLargeCapUniqueFive
open ATailLargeCapUniqueFivePhysicalOmissionCycle
open ATailLargeCapUniqueFivePhysicalOmissionTransitionGlobal
open ATailOrientedPhysicalApexIngress
open ATailParentExactFiveSecondCap
open ATailPhysicalSecondApexCommonDeletion
open CanonicalAsymmetricSemanticRowTable


attribute [local instance] Classical.propDecidable
set_option maxHeartbeats 0
set_option maxRecDepth 1000000
noncomputable section

variable
    {D : CounterexampleData} {S : SurplusCapPacket D.A} {radius : ℝ}
    {H : CriticalShellSystem D.A}
    {F : CriticalPairFrontier D S radius H}
    {R : FrontierCommonDeletionParentResidual F}
    {B : FrontierBiApexRobustResidual R}
    {Q : FrontierBiApexRobustExactFiveSecondCapResidual B}
    {profile : LargeCapUniqueFiveSecondApexRadius D S}
    {M : PhysicalActualCriticalMutualOmissionPair H profile}
    {N : SourceTwoHitNormalForm Q profile M}
    (P : CanonicalAsymmetricRolePrepacket N)
    {star : PhysicalGlobalCrossDeletionStar profile}
    {first : FirstApexShellRolePacket F R}
    {T : CanonicalAsymmetricSemanticRowTable P star first}


structure CompleteClassAssertionsChunk001 (C : CanonicalCoverFamilies T) : Prop where
  h44296 : (!(!(rowBit (directSourceRows C) 0 4 10 == rowBit (directSourceRows C) 0 4 12)) ||
      (!(rankAtom (directSourceRanks P) 47 ==
          rankAtom (directSourceRanks P) 49))) = true
  h44297 : (!(!(rowBit (directSourceRows C) 0 4 11 == rowBit (directSourceRows C) 0 4 12)) ||
      (!(rankAtom (directSourceRanks P) 48 ==
          rankAtom (directSourceRanks P) 49))) = true
  h44298 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 1)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 14))) = true
  h44299 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 2)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 24))) = true
  h44300 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 3)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 33))) = true
  h44301 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 5)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 42))) = true
  h44302 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 6)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 43))) = true
  h44303 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 7)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 44))) = true
  h44304 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 8)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 45))) = true
  h44305 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 9)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 46))) = true
  h44306 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 10)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 47))) = true
  h44307 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 11)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 48))) = true
  h44308 : (!(!(firstRowBit (directSourceFirstRow T) 0 == firstRowBit (directSourceFirstRow T) 12)) ||
      (!(rankAtom (directSourceRanks P) 3 ==
          rankAtom (directSourceRanks P) 49))) = true
  h44309 : (!(!(firstRowBit (directSourceFirstRow T) 1 == firstRowBit (directSourceFirstRow T) 2)) ||
      (!(rankAtom (directSourceRanks P) 14 ==
          rankAtom (directSourceRanks P) 24))) = true
  h44310 : (!(!(firstRowBit (directSourceFirstRow T) 1 == firstRowBit (directSourceFirstRow T) 3)) ||
      (!(rankAtom (directSourceRanks P) 14 ==
          rankAtom (directSourceRanks P) 33))) = true
  h44311 : (!(!(firstRowBit (directSourceFirstRow T) 1 == firstRowBit (directSourceFirstRow T) 5)) ||
      (!(rankAtom (directSourceRanks P) 14 ==
          rankAtom (directSourceRanks P) 42))) = true
  h44312 : (!(!(firstRowBit (directSourceFirstRow T) 1 == firstRowBit (directSourceFirstRow T) 6)) ||
      (!(rankAtom (directSourceRanks P) 14 ==
          rankAtom (directSourceRanks P) 43))) = true
  h44313 : (!(!(firstRowBit (directSourceFirstRow T) 1 == firstRowBit (directSourceFirstRow T) 7)) ||
      (!(rankAtom (directSourceRanks P) 14 ==
          rankAtom (directSourceRanks P) 44))) = true
  h44314 : (!(!(firstRowBit (directSourceFirstRow T) 1 == firstRowBit (directSourceFirstRow T) 8)) ||
      (!(rankAtom (directSourceRanks P) 14 ==
          rankAtom (directSourceRanks P) 45))) = true
  h44315 : (!(!(firstRowBit (directSourceFirstRow T) 1 == firstRowBit (directSourceFirstRow T) 9)) ||
      (!(rankAtom (directSourceRanks P) 14 ==
          rankAtom (directSourceRanks P) 46))) = true
  h44316 : (!(!(firstRowBit (directSourceFirstRow T) 1 == firstRowBit (directSourceFirstRow T) 10)) ||
      (!(rankAtom (directSourceRanks P) 14 ==
          rankAtom (directSourceRanks P) 47))) = true
  h44317 : (!(!(firstRowBit (directSourceFirstRow T) 1 == firstRowBit (directSourceFirstRow T) 11)) ||
      (!(rankAtom (directSourceRanks P) 14 ==
          rankAtom (directSourceRanks P) 48))) = true
  h44318 : (!(!(firstRowBit (directSourceFirstRow T) 1 == firstRowBit (directSourceFirstRow T) 12)) ||
      (!(rankAtom (directSourceRanks P) 14 ==
          rankAtom (directSourceRanks P) 49))) = true
  h44319 : (!(!(firstRowBit (directSourceFirstRow T) 2 == firstRowBit (directSourceFirstRow T) 3)) ||
      (!(rankAtom (directSourceRanks P) 24 ==
          rankAtom (directSourceRanks P) 33))) = true
  h44320 : (!(!(firstRowBit (directSourceFirstRow T) 2 == firstRowBit (directSourceFirstRow T) 5)) ||
      (!(rankAtom (directSourceRanks P) 24 ==
          rankAtom (directSourceRanks P) 42))) = true
  h44321 : (!(!(firstRowBit (directSourceFirstRow T) 2 == firstRowBit (directSourceFirstRow T) 6)) ||
      (!(rankAtom (directSourceRanks P) 24 ==
          rankAtom (directSourceRanks P) 43))) = true
  h44322 : (!(!(firstRowBit (directSourceFirstRow T) 2 == firstRowBit (directSourceFirstRow T) 7)) ||
      (!(rankAtom (directSourceRanks P) 24 ==
          rankAtom (directSourceRanks P) 44))) = true
  h44323 : (!(!(firstRowBit (directSourceFirstRow T) 2 == firstRowBit (directSourceFirstRow T) 8)) ||
      (!(rankAtom (directSourceRanks P) 24 ==
          rankAtom (directSourceRanks P) 45))) = true
  h44324 : (!(!(firstRowBit (directSourceFirstRow T) 2 == firstRowBit (directSourceFirstRow T) 9)) ||
      (!(rankAtom (directSourceRanks P) 24 ==
          rankAtom (directSourceRanks P) 46))) = true
  h44325 : (!(!(firstRowBit (directSourceFirstRow T) 2 == firstRowBit (directSourceFirstRow T) 10)) ||
      (!(rankAtom (directSourceRanks P) 24 ==
          rankAtom (directSourceRanks P) 47))) = true
  h44326 : (!(!(firstRowBit (directSourceFirstRow T) 2 == firstRowBit (directSourceFirstRow T) 11)) ||
      (!(rankAtom (directSourceRanks P) 24 ==
          rankAtom (directSourceRanks P) 48))) = true
  h44327 : (!(!(firstRowBit (directSourceFirstRow T) 2 == firstRowBit (directSourceFirstRow T) 12)) ||
      (!(rankAtom (directSourceRanks P) 24 ==
          rankAtom (directSourceRanks P) 49))) = true
  h44328 : (!(!(firstRowBit (directSourceFirstRow T) 3 == firstRowBit (directSourceFirstRow T) 5)) ||
      (!(rankAtom (directSourceRanks P) 33 ==
          rankAtom (directSourceRanks P) 42))) = true
  h44329 : (!(!(firstRowBit (directSourceFirstRow T) 3 == firstRowBit (directSourceFirstRow T) 6)) ||
      (!(rankAtom (directSourceRanks P) 33 ==
          rankAtom (directSourceRanks P) 43))) = true
  h44330 : (!(!(firstRowBit (directSourceFirstRow T) 3 == firstRowBit (directSourceFirstRow T) 7)) ||
      (!(rankAtom (directSourceRanks P) 33 ==
          rankAtom (directSourceRanks P) 44))) = true
  h44331 : (!(!(firstRowBit (directSourceFirstRow T) 3 == firstRowBit (directSourceFirstRow T) 8)) ||
      (!(rankAtom (directSourceRanks P) 33 ==
          rankAtom (directSourceRanks P) 45))) = true
  h44332 : (!(!(firstRowBit (directSourceFirstRow T) 3 == firstRowBit (directSourceFirstRow T) 9)) ||
      (!(rankAtom (directSourceRanks P) 33 ==
          rankAtom (directSourceRanks P) 46))) = true
  h44333 : (!(!(firstRowBit (directSourceFirstRow T) 3 == firstRowBit (directSourceFirstRow T) 10)) ||
      (!(rankAtom (directSourceRanks P) 33 ==
          rankAtom (directSourceRanks P) 47))) = true
  h44334 : (!(!(firstRowBit (directSourceFirstRow T) 3 == firstRowBit (directSourceFirstRow T) 11)) ||
      (!(rankAtom (directSourceRanks P) 33 ==
          rankAtom (directSourceRanks P) 48))) = true
  h44335 : (!(!(firstRowBit (directSourceFirstRow T) 3 == firstRowBit (directSourceFirstRow T) 12)) ||
      (!(rankAtom (directSourceRanks P) 33 ==
          rankAtom (directSourceRanks P) 49))) = true
  h44336 : (!(!(firstRowBit (directSourceFirstRow T) 5 == firstRowBit (directSourceFirstRow T) 6)) ||
      (!(rankAtom (directSourceRanks P) 42 ==
          rankAtom (directSourceRanks P) 43))) = true
  h44337 : (!(!(firstRowBit (directSourceFirstRow T) 5 == firstRowBit (directSourceFirstRow T) 7)) ||
      (!(rankAtom (directSourceRanks P) 42 ==
          rankAtom (directSourceRanks P) 44))) = true
  h44338 : (!(!(firstRowBit (directSourceFirstRow T) 5 == firstRowBit (directSourceFirstRow T) 8)) ||
      (!(rankAtom (directSourceRanks P) 42 ==
          rankAtom (directSourceRanks P) 45))) = true
  h44339 : (!(!(firstRowBit (directSourceFirstRow T) 5 == firstRowBit (directSourceFirstRow T) 9)) ||
      (!(rankAtom (directSourceRanks P) 42 ==
          rankAtom (directSourceRanks P) 46))) = true
  h44340 : (!(!(firstRowBit (directSourceFirstRow T) 5 == firstRowBit (directSourceFirstRow T) 10)) ||
      (!(rankAtom (directSourceRanks P) 42 ==
          rankAtom (directSourceRanks P) 47))) = true
  h44341 : (!(!(firstRowBit (directSourceFirstRow T) 5 == firstRowBit (directSourceFirstRow T) 11)) ||
      (!(rankAtom (directSourceRanks P) 42 ==
          rankAtom (directSourceRanks P) 48))) = true
  h44342 : (!(!(firstRowBit (directSourceFirstRow T) 5 == firstRowBit (directSourceFirstRow T) 12)) ||
      (!(rankAtom (directSourceRanks P) 42 ==
          rankAtom (directSourceRanks P) 49))) = true
  h44343 : (!(!(firstRowBit (directSourceFirstRow T) 6 == firstRowBit (directSourceFirstRow T) 7)) ||
      (!(rankAtom (directSourceRanks P) 43 ==
          rankAtom (directSourceRanks P) 44))) = true
  h44344 : (!(!(firstRowBit (directSourceFirstRow T) 6 == firstRowBit (directSourceFirstRow T) 8)) ||
      (!(rankAtom (directSourceRanks P) 43 ==
          rankAtom (directSourceRanks P) 45))) = true
  h44345 : (!(!(firstRowBit (directSourceFirstRow T) 6 == firstRowBit (directSourceFirstRow T) 9)) ||
      (!(rankAtom (directSourceRanks P) 43 ==
          rankAtom (directSourceRanks P) 46))) = true
  h44346 : (!(!(firstRowBit (directSourceFirstRow T) 6 == firstRowBit (directSourceFirstRow T) 10)) ||
      (!(rankAtom (directSourceRanks P) 43 ==
          rankAtom (directSourceRanks P) 47))) = true
  h44347 : (!(!(firstRowBit (directSourceFirstRow T) 6 == firstRowBit (directSourceFirstRow T) 11)) ||
      (!(rankAtom (directSourceRanks P) 43 ==
          rankAtom (directSourceRanks P) 48))) = true
  h44348 : (!(!(firstRowBit (directSourceFirstRow T) 6 == firstRowBit (directSourceFirstRow T) 12)) ||
      (!(rankAtom (directSourceRanks P) 43 ==
          rankAtom (directSourceRanks P) 49))) = true
  h44349 : (!(!(firstRowBit (directSourceFirstRow T) 7 == firstRowBit (directSourceFirstRow T) 8)) ||
      (!(rankAtom (directSourceRanks P) 44 ==
          rankAtom (directSourceRanks P) 45))) = true
  h44350 : (!(!(firstRowBit (directSourceFirstRow T) 7 == firstRowBit (directSourceFirstRow T) 9)) ||
      (!(rankAtom (directSourceRanks P) 44 ==
          rankAtom (directSourceRanks P) 46))) = true
  h44351 : (!(!(firstRowBit (directSourceFirstRow T) 7 == firstRowBit (directSourceFirstRow T) 10)) ||
      (!(rankAtom (directSourceRanks P) 44 ==
          rankAtom (directSourceRanks P) 47))) = true
  h44352 : (!(!(firstRowBit (directSourceFirstRow T) 7 == firstRowBit (directSourceFirstRow T) 11)) ||
      (!(rankAtom (directSourceRanks P) 44 ==
          rankAtom (directSourceRanks P) 48))) = true
  h44353 : (!(!(firstRowBit (directSourceFirstRow T) 7 == firstRowBit (directSourceFirstRow T) 12)) ||
      (!(rankAtom (directSourceRanks P) 44 ==
          rankAtom (directSourceRanks P) 49))) = true
  h44354 : (!(!(firstRowBit (directSourceFirstRow T) 8 == firstRowBit (directSourceFirstRow T) 9)) ||
      (!(rankAtom (directSourceRanks P) 45 ==
          rankAtom (directSourceRanks P) 46))) = true
  h44355 : (!(!(firstRowBit (directSourceFirstRow T) 8 == firstRowBit (directSourceFirstRow T) 10)) ||
      (!(rankAtom (directSourceRanks P) 45 ==
          rankAtom (directSourceRanks P) 47))) = true
  h44356 : (!(!(firstRowBit (directSourceFirstRow T) 8 == firstRowBit (directSourceFirstRow T) 11)) ||
      (!(rankAtom (directSourceRanks P) 45 ==
          rankAtom (directSourceRanks P) 48))) = true
  h44357 : (!(!(firstRowBit (directSourceFirstRow T) 8 == firstRowBit (directSourceFirstRow T) 12)) ||
      (!(rankAtom (directSourceRanks P) 45 ==
          rankAtom (directSourceRanks P) 49))) = true
  h44358 : (!(!(firstRowBit (directSourceFirstRow T) 9 == firstRowBit (directSourceFirstRow T) 10)) ||
      (!(rankAtom (directSourceRanks P) 46 ==
          rankAtom (directSourceRanks P) 47))) = true
  h44359 : (!(!(firstRowBit (directSourceFirstRow T) 9 == firstRowBit (directSourceFirstRow T) 11)) ||
      (!(rankAtom (directSourceRanks P) 46 ==
          rankAtom (directSourceRanks P) 48))) = true

theorem canonicalCompleteClassAssertionsChunk001
    (C : CanonicalCoverFamilies T)
    (hcard : D.A.card = 13) (hdistinct : first.doubleRadius ≠ radius) :
    CompleteClassAssertionsChunk001 P C := by
  constructor
  · simpa using directSource_complete_retained_guard P C hcard hdistinct
      (10 : Fin 13) (12 : Fin 13)
      (47 : Fin 78) (49 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_retained_guard P C hcard hdistinct
      (11 : Fin 13) (12 : Fin 13)
      (48 : Fin 78) (49 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (1 : Fin 13)
      (3 : Fin 78) (14 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (2 : Fin 13)
      (3 : Fin 78) (24 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (3 : Fin 13)
      (3 : Fin 78) (33 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (5 : Fin 13)
      (3 : Fin 78) (42 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (6 : Fin 13)
      (3 : Fin 78) (43 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (7 : Fin 13)
      (3 : Fin 78) (44 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (8 : Fin 13)
      (3 : Fin 78) (45 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (9 : Fin 13)
      (3 : Fin 78) (46 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (10 : Fin 13)
      (3 : Fin 78) (47 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (11 : Fin 13)
      (3 : Fin 78) (48 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (0 : Fin 13) (12 : Fin 13)
      (3 : Fin 78) (49 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (1 : Fin 13) (2 : Fin 13)
      (14 : Fin 78) (24 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (1 : Fin 13) (3 : Fin 13)
      (14 : Fin 78) (33 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (1 : Fin 13) (5 : Fin 13)
      (14 : Fin 78) (42 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (1 : Fin 13) (6 : Fin 13)
      (14 : Fin 78) (43 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (1 : Fin 13) (7 : Fin 13)
      (14 : Fin 78) (44 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (1 : Fin 13) (8 : Fin 13)
      (14 : Fin 78) (45 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (1 : Fin 13) (9 : Fin 13)
      (14 : Fin 78) (46 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (1 : Fin 13) (10 : Fin 13)
      (14 : Fin 78) (47 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (1 : Fin 13) (11 : Fin 13)
      (14 : Fin 78) (48 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (1 : Fin 13) (12 : Fin 13)
      (14 : Fin 78) (49 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (2 : Fin 13) (3 : Fin 13)
      (24 : Fin 78) (33 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (2 : Fin 13) (5 : Fin 13)
      (24 : Fin 78) (42 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (2 : Fin 13) (6 : Fin 13)
      (24 : Fin 78) (43 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (2 : Fin 13) (7 : Fin 13)
      (24 : Fin 78) (44 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (2 : Fin 13) (8 : Fin 13)
      (24 : Fin 78) (45 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (2 : Fin 13) (9 : Fin 13)
      (24 : Fin 78) (46 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (2 : Fin 13) (10 : Fin 13)
      (24 : Fin 78) (47 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (2 : Fin 13) (11 : Fin 13)
      (24 : Fin 78) (48 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (2 : Fin 13) (12 : Fin 13)
      (24 : Fin 78) (49 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (3 : Fin 13) (5 : Fin 13)
      (33 : Fin 78) (42 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (3 : Fin 13) (6 : Fin 13)
      (33 : Fin 78) (43 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (3 : Fin 13) (7 : Fin 13)
      (33 : Fin 78) (44 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (3 : Fin 13) (8 : Fin 13)
      (33 : Fin 78) (45 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (3 : Fin 13) (9 : Fin 13)
      (33 : Fin 78) (46 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (3 : Fin 13) (10 : Fin 13)
      (33 : Fin 78) (47 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (3 : Fin 13) (11 : Fin 13)
      (33 : Fin 78) (48 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (3 : Fin 13) (12 : Fin 13)
      (33 : Fin 78) (49 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (5 : Fin 13) (6 : Fin 13)
      (42 : Fin 78) (43 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (5 : Fin 13) (7 : Fin 13)
      (42 : Fin 78) (44 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (5 : Fin 13) (8 : Fin 13)
      (42 : Fin 78) (45 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (5 : Fin 13) (9 : Fin 13)
      (42 : Fin 78) (46 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (5 : Fin 13) (10 : Fin 13)
      (42 : Fin 78) (47 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (5 : Fin 13) (11 : Fin 13)
      (42 : Fin 78) (48 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (5 : Fin 13) (12 : Fin 13)
      (42 : Fin 78) (49 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (6 : Fin 13) (7 : Fin 13)
      (43 : Fin 78) (44 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (6 : Fin 13) (8 : Fin 13)
      (43 : Fin 78) (45 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (6 : Fin 13) (9 : Fin 13)
      (43 : Fin 78) (46 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (6 : Fin 13) (10 : Fin 13)
      (43 : Fin 78) (47 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (6 : Fin 13) (11 : Fin 13)
      (43 : Fin 78) (48 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (6 : Fin 13) (12 : Fin 13)
      (43 : Fin 78) (49 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (7 : Fin 13) (8 : Fin 13)
      (44 : Fin 78) (45 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (7 : Fin 13) (9 : Fin 13)
      (44 : Fin 78) (46 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (7 : Fin 13) (10 : Fin 13)
      (44 : Fin 78) (47 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (7 : Fin 13) (11 : Fin 13)
      (44 : Fin 78) (48 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (7 : Fin 13) (12 : Fin 13)
      (44 : Fin 78) (49 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (8 : Fin 13) (9 : Fin 13)
      (45 : Fin 78) (46 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (8 : Fin 13) (10 : Fin 13)
      (45 : Fin 78) (47 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (8 : Fin 13) (11 : Fin 13)
      (45 : Fin 78) (48 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (8 : Fin 13) (12 : Fin 13)
      (45 : Fin 78) (49 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (9 : Fin 13) (10 : Fin 13)
      (46 : Fin 78) (47 : Fin 78)
      (by decide) (by decide)
  · simpa using directSource_complete_double_guard P hcard hdistinct
      (9 : Fin 13) (11 : Fin 13)
      (46 : Fin 78) (48 : Fin 78)
      (by decide) (by decide)

end
end ATailExactFiveCard13DistinctRadiusSourceIngressScratch
end Problem97
