/- Generated by `generate_unique_k4_instances.py`; do not edit. -/
import RankSourceAdapters

/-! Exact generated unique-K4 rank assertion chunk 105. -/

namespace Problem97
namespace ATailExactFiveCard13DistinctRadiusSourceIngressScratch

open ATailCriticalPairFrontier
open ATailBiApexRobustCapBounds
open ATailExactFiveCard13CnfIngressScratch
open ATailExactFiveCard13CommonLabelTransportScratch
open ATailExactFiveFirstApexCard13ParentRowCouplingScratch
open ATailExactFiveFirstApexCard13Scratch
open ATailExactFiveGlobalCrossDeletionPair
open ATailExactFiveGlobalCoverStarGeometry
open ATailExactFiveMutualOneHitGeometry
open ATailFirstApexShellRole
open ATailKalmansonParentOrderScratch
open ATailLargeCapUniqueFive
open ATailLargeCapUniqueFivePhysicalOmissionCycle
open ATailLargeCapUniqueFivePhysicalOmissionTransitionGlobal
open ATailOrientedPhysicalApexIngress
open ATailParentExactFiveSecondCap
open ATailPhysicalSecondApexCommonDeletion
open CanonicalAsymmetricSemanticRowTable


attribute [local instance] Classical.propDecidable
set_option maxHeartbeats 0
set_option maxRecDepth 1000000
noncomputable section

variable
    {D : CounterexampleData} {S : SurplusCapPacket D.A} {radius : ℝ}
    {H : CriticalShellSystem D.A}
    {F : CriticalPairFrontier D S radius H}
    {R : FrontierCommonDeletionParentResidual F}
    {B : FrontierBiApexRobustResidual R}
    {Q : FrontierBiApexRobustExactFiveSecondCapResidual B}
    {profile : LargeCapUniqueFiveSecondApexRadius D S}
    {M : PhysicalActualCriticalMutualOmissionPair H profile}
    {N : SourceTwoHitNormalForm Q profile M}
    (P : CanonicalAsymmetricRolePrepacket N)
    {star : PhysicalGlobalCrossDeletionStar profile}
    {first : FirstApexShellRolePacket F R}
    {T : CanonicalAsymmetricSemanticRowTable P star first}


structure UniqueK4AssertionsChunk105 (C : CanonicalCoverFamilies T) : Prop where
  h52008 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 5))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55)))) = true
  h52009 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 6))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61)))) = true
  h52010 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 7))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66)))) = true
  h52011 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 8))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70)))) = true
  h52012 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52013 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52014 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52015 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 6))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61)))) = true
  h52016 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 7))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66)))) = true
  h52017 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 8))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70)))) = true
  h52018 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52019 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52020 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52021 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 7))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66)))) = true
  h52022 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 8))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70)))) = true
  h52023 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52024 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52025 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52026 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 8))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70)))) = true
  h52027 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52028 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52029 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52030 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 8 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52031 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 8 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52032 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 8 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52033 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 9 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52034 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 9 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52035 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 3 &&
          rowBit (directSourceRows C) 0 11 10 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 40) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52036 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 6))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61)))) = true
  h52037 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 7))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66)))) = true
  h52038 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 8))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70)))) = true
  h52039 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52040 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52041 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52042 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 7))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66)))) = true
  h52043 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 8))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70)))) = true
  h52044 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52045 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52046 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52047 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 8))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70)))) = true
  h52048 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52049 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52050 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52051 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 8 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52052 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 8 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52053 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 8 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52054 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 9 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52055 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 9 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52056 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 4 &&
          rowBit (directSourceRows C) 0 11 10 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52057 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 7))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66)))) = true
  h52058 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 8))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70)))) = true
  h52059 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52060 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52061 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 6 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 61) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52062 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 8))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70)))) = true
  h52063 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52064 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52065 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 7 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 66) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52066 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 8 &&
          rowBit (directSourceRows C) 0 11 9))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73)))) = true
  h52067 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 8 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52068 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 8 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 70) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52069 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 9 &&
          rowBit (directSourceRows C) 0 11 10))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75)))) = true
  h52070 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 9 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 73) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true
  h52071 : (!((actualBlockerImageBit P T (11 : Fin 13) && !(rowBit (directSourceRows C) 0 11 2 &&
          rowBit (directSourceRows C) 0 11 5 &&
          rowBit (directSourceRows C) 0 11 10 &&
          rowBit (directSourceRows C) 0 11 12))) ||
      (!((rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 55) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 75) &&
          (rankAtom (directSourceRanks P) 31 == rankAtom (directSourceRanks P) 77)))) = true

theorem canonicalUniqueK4AssertionsChunk105
    (C : CanonicalCoverFamilies T) :
    UniqueK4AssertionsChunk105 P C := by
  constructor
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (4 : Fin 13) (5 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (48 : Fin 78) (55 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (4 : Fin 13) (6 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (48 : Fin 78) (61 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (4 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (48 : Fin 78) (66 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (4 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (48 : Fin 78) (70 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (4 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (48 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (4 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (48 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (4 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (48 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (5 : Fin 13) (6 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (55 : Fin 78) (61 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (5 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (55 : Fin 78) (66 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (5 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (55 : Fin 78) (70 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (5 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (55 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (5 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (55 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (5 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (55 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (6 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (61 : Fin 78) (66 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (6 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (61 : Fin 78) (70 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (6 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (61 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (6 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (61 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (6 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (61 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (7 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (66 : Fin 78) (70 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (7 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (66 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (7 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (66 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (7 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (66 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (8 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (70 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (8 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (70 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (8 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (70 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (9 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (73 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (9 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (73 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (3 : Fin 13) (10 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (40 : Fin 78) (75 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (5 : Fin 13) (6 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (55 : Fin 78) (61 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (5 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (55 : Fin 78) (66 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (5 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (55 : Fin 78) (70 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (5 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (55 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (5 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (55 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (5 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (55 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (6 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (61 : Fin 78) (66 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (6 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (61 : Fin 78) (70 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (6 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (61 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (6 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (61 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (6 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (61 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (7 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (66 : Fin 78) (70 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (7 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (66 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (7 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (66 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (7 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (66 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (8 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (70 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (8 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (70 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (8 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (70 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (9 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (73 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (9 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (73 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (4 : Fin 13) (10 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (48 : Fin 78) (75 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (6 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (61 : Fin 78) (66 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (6 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (61 : Fin 78) (70 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (6 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (61 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (6 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (61 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (6 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (61 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (7 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (66 : Fin 78) (70 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (7 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (66 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (7 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (66 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (7 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (66 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (8 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (70 : Fin 78) (73 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (8 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (70 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (8 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (70 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (9 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (73 : Fin 78) (75 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (9 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (73 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (11 : Fin 13)
      (2 : Fin 13) (5 : Fin 13) (10 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (31 : Fin 78) (55 : Fin 78) (75 : Fin 78) (77 : Fin 78) (by decide) (by decide) (by decide) (by decide)

end
end ATailExactFiveCard13DistinctRadiusSourceIngressScratch
end Problem97
