/- Generated by `generate_unique_k4_instances.py`; do not edit. -/
import RankSourceAdapters

/-! Exact generated unique-K4 rank assertion chunk 049. -/

namespace Problem97
namespace ATailExactFiveCard13DistinctRadiusSourceIngressScratch

open ATailCriticalPairFrontier
open ATailBiApexRobustCapBounds
open ATailExactFiveCard13CnfIngressScratch
open ATailExactFiveCard13CommonLabelTransportScratch
open ATailExactFiveFirstApexCard13ParentRowCouplingScratch
open ATailExactFiveFirstApexCard13Scratch
open ATailExactFiveGlobalCrossDeletionPair
open ATailExactFiveGlobalCoverStarGeometry
open ATailExactFiveMutualOneHitGeometry
open ATailFirstApexShellRole
open ATailKalmansonParentOrderScratch
open ATailLargeCapUniqueFive
open ATailLargeCapUniqueFivePhysicalOmissionCycle
open ATailLargeCapUniqueFivePhysicalOmissionTransitionGlobal
open ATailOrientedPhysicalApexIngress
open ATailParentExactFiveSecondCap
open ATailPhysicalSecondApexCommonDeletion
open CanonicalAsymmetricSemanticRowTable


attribute [local instance] Classical.propDecidable
set_option maxHeartbeats 0
set_option maxRecDepth 1000000
noncomputable section

variable
    {D : CounterexampleData} {S : SurplusCapPacket D.A} {radius : ℝ}
    {H : CriticalShellSystem D.A}
    {F : CriticalPairFrontier D S radius H}
    {R : FrontierCommonDeletionParentResidual F}
    {B : FrontierBiApexRobustResidual R}
    {Q : FrontierBiApexRobustExactFiveSecondCapResidual B}
    {profile : LargeCapUniqueFiveSecondApexRadius D S}
    {M : PhysicalActualCriticalMutualOmissionPair H profile}
    {N : SourceTwoHitNormalForm Q profile M}
    (P : CanonicalAsymmetricRolePrepacket N)
    {star : PhysicalGlobalCrossDeletionStar profile}
    {first : FirstApexShellRolePacket F R}
    {T : CanonicalAsymmetricSemanticRowTable P star first}


structure UniqueK4AssertionsChunk049 (C : CanonicalCoverFamilies T) : Prop where
  h48424 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 6))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43)))) = true
  h48425 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 7))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44)))) = true
  h48426 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 8))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45)))) = true
  h48427 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 9))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46)))) = true
  h48428 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48429 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48430 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48431 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 6))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43)))) = true
  h48432 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 7))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44)))) = true
  h48433 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 8))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45)))) = true
  h48434 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 9))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46)))) = true
  h48435 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48436 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48437 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48438 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 7))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44)))) = true
  h48439 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 8))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45)))) = true
  h48440 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 9))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46)))) = true
  h48441 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48442 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48443 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48444 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 7 &&
          rowBit (directSourceRows C) 0 4 8))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45)))) = true
  h48445 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 7 &&
          rowBit (directSourceRows C) 0 4 9))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46)))) = true
  h48446 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 7 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48447 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 7 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48448 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 7 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48449 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 8 &&
          rowBit (directSourceRows C) 0 4 9))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46)))) = true
  h48450 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 8 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48451 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 8 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48452 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 8 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48453 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 9 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48454 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 9 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48455 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 9 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48456 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 10 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48457 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 10 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48458 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 2 &&
          rowBit (directSourceRows C) 0 4 11 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 24) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48459 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 6))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43)))) = true
  h48460 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 7))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44)))) = true
  h48461 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 8))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45)))) = true
  h48462 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 9))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46)))) = true
  h48463 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48464 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48465 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48466 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 7))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44)))) = true
  h48467 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 8))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45)))) = true
  h48468 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 9))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46)))) = true
  h48469 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48470 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48471 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48472 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 7 &&
          rowBit (directSourceRows C) 0 4 8))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45)))) = true
  h48473 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 7 &&
          rowBit (directSourceRows C) 0 4 9))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46)))) = true
  h48474 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 7 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48475 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 7 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48476 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 7 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48477 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 8 &&
          rowBit (directSourceRows C) 0 4 9))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46)))) = true
  h48478 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 8 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48479 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 8 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48480 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 8 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 45) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48481 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 9 &&
          rowBit (directSourceRows C) 0 4 10))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47)))) = true
  h48482 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 9 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48483 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 9 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 46) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48484 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 10 &&
          rowBit (directSourceRows C) 0 4 11))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48)))) = true
  h48485 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 10 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 47) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48486 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 3 &&
          rowBit (directSourceRows C) 0 4 11 &&
          rowBit (directSourceRows C) 0 4 12))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 33) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 48) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 49)))) = true
  h48487 : (!((actualBlockerImageBit P T (4 : Fin 13) && !(rowBit (directSourceRows C) 0 4 1 &&
          rowBit (directSourceRows C) 0 4 5 &&
          rowBit (directSourceRows C) 0 4 6 &&
          rowBit (directSourceRows C) 0 4 7))) ||
      (!((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 42) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 43) &&
          (rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 44)))) = true

theorem canonicalUniqueK4AssertionsChunk049
    (C : CanonicalCoverFamilies T) :
    UniqueK4AssertionsChunk049 P C := by
  constructor
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (3 : Fin 13) (6 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (33 : Fin 78) (43 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (3 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (33 : Fin 78) (44 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (3 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (33 : Fin 78) (45 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (3 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (33 : Fin 78) (46 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (3 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (33 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (3 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (33 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (3 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (33 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (5 : Fin 13) (6 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (42 : Fin 78) (43 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (5 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (42 : Fin 78) (44 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (5 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (42 : Fin 78) (45 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (5 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (42 : Fin 78) (46 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (5 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (42 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (5 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (42 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (5 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (42 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (6 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (43 : Fin 78) (44 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (6 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (43 : Fin 78) (45 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (6 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (43 : Fin 78) (46 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (6 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (43 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (6 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (43 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (6 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (43 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (7 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (44 : Fin 78) (45 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (7 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (44 : Fin 78) (46 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (7 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (44 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (7 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (44 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (7 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (44 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (8 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (45 : Fin 78) (46 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (8 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (45 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (8 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (45 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (8 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (45 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (9 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (46 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (9 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (46 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (9 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (46 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (10 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (47 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (10 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (47 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (2 : Fin 13) (11 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (24 : Fin 78) (48 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (5 : Fin 13) (6 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (42 : Fin 78) (43 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (5 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (42 : Fin 78) (44 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (5 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (42 : Fin 78) (45 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (5 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (42 : Fin 78) (46 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (5 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (42 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (5 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (42 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (5 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (42 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (6 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (43 : Fin 78) (44 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (6 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (43 : Fin 78) (45 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (6 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (43 : Fin 78) (46 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (6 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (43 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (6 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (43 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (6 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (43 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (7 : Fin 13) (8 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (44 : Fin 78) (45 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (7 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (44 : Fin 78) (46 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (7 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (44 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (7 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (44 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (7 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (44 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (8 : Fin 13) (9 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (45 : Fin 78) (46 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (8 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (45 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (8 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (45 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (8 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (45 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (9 : Fin 13) (10 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (46 : Fin 78) (47 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (9 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (46 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (9 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (46 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (10 : Fin 13) (11 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (47 : Fin 78) (48 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (10 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (47 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (3 : Fin 13) (11 : Fin 13) (12 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (33 : Fin 78) (48 : Fin 78) (49 : Fin 78) (by decide) (by decide) (by decide) (by decide)
  · simpa using directSource_unique_actual_guard P C (4 : Fin 13)
      (1 : Fin 13) (5 : Fin 13) (6 : Fin 13) (7 : Fin 13) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
      (14 : Fin 78) (42 : Fin 78) (43 : Fin 78) (44 : Fin 78) (by decide) (by decide) (by decide) (by decide)

end
end ATailExactFiveCard13DistinctRadiusSourceIngressScratch
end Problem97
