/- This file is generated by ../generate.py; do not edit. -/
import P4MirrorOuterOccurrenceBridge.Families

/-!
Lean 4.27-compatible prefixed materialization of generated mirror-outer data.
-/

namespace Problem97.P4MirrorOuterOccurrenceBridgeScratch

open ATailCriticalPairFrontier
open ATailUniqueArmRouteAuditScratch
open ATailUniqueFourClassCapDistributionScratch
open ATailUniqueFourExactTwoBoundaryScratch
open P4DirectOuterArcAdapterScratch

def entry_15853 : MirrorEntry := .noFour (noFourEntry 15853 [-1642, -1444, -950, -1943]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (950, ⟨2, .left, {9}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15854 : MirrorEntry := .noFour (noFourEntry 15854 [-1936, -1642, -950, -1444]
  (1936, ⟨8, .right, {0, 1, 10}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (by native_decide))

def entry_15855 : MirrorEntry := .noFour (noFourEntry 15855 [-1642, -1444, -950, -2183]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (950, ⟨2, .left, {9}⟩) (2183, ⟨9, .left, {2}⟩)
  (by native_decide))

def entry_15856 : MirrorEntry := .noFour (noFourEntry 15856 [-1642, -1444, -950, -2159]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (950, ⟨2, .left, {9}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15857 : MirrorEntry := .noFour (noFourEntry 15857 [-2151, -1642, -950, -1444]
  (2151, ⟨9, .right, {0, 10}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (by native_decide))

def entry_15858 : MirrorEntry := .noFour (noFourEntry 15858 [-1642, -1444, -2395, -950]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (2395, ⟨10, .left, {1}⟩) (950, ⟨2, .left, {9}⟩)
  (by native_decide))

def entry_15859 : MirrorEntry := .noFour (noFourEntry 15859 [-1642, -1444, -950, -2392]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (950, ⟨2, .left, {9}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (by native_decide))

def entry_15860 : MirrorEntry := .noFour (noFourEntry 15860 [-1444, -950, -1647, -1865]
  (1444, ⟨5, .right, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1865, ⟨7, .right, {0, 1, 2, 10}⟩)
  (by native_decide))

def entry_15861 : MirrorEntry := .noFour (noFourEntry 15861 [-1444, -950, -1647, -1971]
  (1444, ⟨5, .right, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1971, ⟨8, .right, {1}⟩)
  (by native_decide))

def entry_15862 : MirrorEntry := .noFour (noFourEntry 15862 [-1444, -950, -1647, -1943]
  (1444, ⟨5, .right, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15863 : MirrorEntry := .noFour (noFourEntry 15863 [-1444, -950, -1647, -1936]
  (1444, ⟨5, .right, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (by native_decide))

def entry_15864 : MirrorEntry := .noFour (noFourEntry 15864 [-1444, -950, -1647, -2183]
  (1444, ⟨5, .right, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2183, ⟨9, .left, {2}⟩)
  (by native_decide))

def entry_15865 : MirrorEntry := .noFour (noFourEntry 15865 [-1444, -950, -1647, -2159]
  (1444, ⟨5, .right, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15866 : MirrorEntry := .noFour (noFourEntry 15866 [-2151, -950, -1647, -1444]
  (2151, ⟨9, .right, {0, 10}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (by native_decide))

def entry_15867 : MirrorEntry := .noFour (noFourEntry 15867 [-1444, -950, -1647, -2395]
  (1444, ⟨5, .right, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2395, ⟨10, .left, {1}⟩)
  (by native_decide))

def entry_15868 : MirrorEntry := .noFour (noFourEntry 15868 [-1444, -950, -1647, -2392]
  (1444, ⟨5, .right, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (by native_decide))

def entry_15869 : MirrorEntry := .noFour (noFourEntry 15869 [-1653, -1446, -950, -1943]
  (1653, ⟨6, .left, {5, 6}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (950, ⟨2, .left, {9}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15870 : MirrorEntry := .noFour (noFourEntry 15870 [-1936, -1653, -950, -1446]
  (1936, ⟨8, .right, {0, 1, 10}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (by native_decide))

def entry_15871 : MirrorEntry := .noFour (noFourEntry 15871 [-1653, -1446, -950, -2159]
  (1653, ⟨6, .left, {5, 6}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (950, ⟨2, .left, {9}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15872 : MirrorEntry := .noFour (noFourEntry 15872 [-1653, -1446, -950, -2151]
  (1653, ⟨6, .left, {5, 6}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (950, ⟨2, .left, {9}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15873 : MirrorEntry := .noFour (noFourEntry 15873 [-1446, -950, -1971, -1642]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1971, ⟨8, .right, {1}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (by native_decide))

def entry_15874 : MirrorEntry := .noFour (noFourEntry 15874 [-1642, -1446, -950, -1943]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (950, ⟨2, .left, {9}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15875 : MirrorEntry := .noFour (noFourEntry 15875 [-1936, -1642, -950, -1446]
  (1936, ⟨8, .right, {0, 1, 10}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (by native_decide))

def entry_15876 : MirrorEntry := .noFour (noFourEntry 15876 [-1642, -1446, -950, -2159]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (950, ⟨2, .left, {9}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15877 : MirrorEntry := .noFour (noFourEntry 15877 [-2151, -1642, -950, -1446]
  (2151, ⟨9, .right, {0, 10}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (by native_decide))

def entry_15878 : MirrorEntry := .noFour (noFourEntry 15878 [-1642, -1446, -2395, -950]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (2395, ⟨10, .left, {1}⟩) (950, ⟨2, .left, {9}⟩)
  (by native_decide))

def entry_15879 : MirrorEntry := .noFour (noFourEntry 15879 [-950, -1971, -1647, -1446]
  (950, ⟨2, .left, {9}⟩) (1971, ⟨8, .right, {1}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (by native_decide))

def entry_15880 : MirrorEntry := .noFour (noFourEntry 15880 [-1446, -950, -1647, -1943]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15881 : MirrorEntry := .noFour (noFourEntry 15881 [-1446, -950, -1647, -1936]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (by native_decide))

def entry_15882 : MirrorEntry := .noFour (noFourEntry 15882 [-1446, -950, -1647, -2159]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15883 : MirrorEntry := .noFour (noFourEntry 15883 [-2151, -950, -1647, -1446]
  (2151, ⟨9, .right, {0, 10}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (by native_decide))

def entry_15884 : MirrorEntry := .noFour (noFourEntry 15884 [-1446, -950, -1647, -2395]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2395, ⟨10, .left, {1}⟩)
  (by native_decide))

def entry_15885 : MirrorEntry := .noFour (noFourEntry 15885 [-1653, -1448, -950, -2159]
  (1653, ⟨6, .left, {5, 6}⟩) (1448, ⟨5, .right, {1, 2, 3, 4}⟩)
  (950, ⟨2, .left, {9}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15886 : MirrorEntry := .noFour (noFourEntry 15886 [-2151, -1653, -950, -1448]
  (2151, ⟨9, .right, {0, 10}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (1448, ⟨5, .right, {1, 2, 3, 4}⟩)
  (by native_decide))

def entry_15887 : MirrorEntry := .noFour (noFourEntry 15887 [-2159, -1642, -1448, -950]
  (2159, ⟨9, .right, {0}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (1448, ⟨5, .right, {1, 2, 3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (by native_decide))

def entry_15888 : MirrorEntry := .noFour (noFourEntry 15888 [-2151, -1642, -950, -1448]
  (2151, ⟨9, .right, {0, 10}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (1448, ⟨5, .right, {1, 2, 3, 4}⟩)
  (by native_decide))

def entry_15889 : MirrorEntry := .noFour (noFourEntry 15889 [-1448, -950, -1647, -2159]
  (1448, ⟨5, .right, {1, 2, 3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15890 : MirrorEntry := .noFour (noFourEntry 15890 [-2151, -950, -1647, -1448]
  (2151, ⟨9, .right, {0, 10}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1448, ⟨5, .right, {1, 2, 3, 4}⟩)
  (by native_decide))

def entry_15891 : MirrorEntry := .noFour (noFourEntry 15891 [-1943, -1671, -950, -1653]
  (1943, ⟨8, .right, {0, 1}⟩) (1671, ⟨6, .right, {3}⟩)
  (950, ⟨2, .left, {9}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (by native_decide))

def entry_15892 : MirrorEntry := .noFour (noFourEntry 15892 [-2159, -1671, -950, -1653]
  (2159, ⟨9, .right, {0}⟩) (1671, ⟨6, .right, {3}⟩)
  (950, ⟨2, .left, {9}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (by native_decide))

def entry_15893 : MirrorEntry := .noFour (noFourEntry 15893 [-1943, -1673, -950, -1653]
  (1943, ⟨8, .right, {0, 1}⟩) (1673, ⟨6, .right, {2, 3}⟩)
  (950, ⟨2, .left, {9}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (by native_decide))

def entry_15894 : MirrorEntry := .noFour (noFourEntry 15894 [-2159, -1673, -950, -1653]
  (2159, ⟨9, .right, {0}⟩) (1673, ⟨6, .right, {2, 3}⟩)
  (950, ⟨2, .left, {9}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (by native_decide))

def entry_15895 : MirrorEntry := .noFour (noFourEntry 15895 [-2159, -1653, -950, -1675]
  (2159, ⟨9, .right, {0}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (1675, ⟨6, .right, {1, 2, 3}⟩)
  (by native_decide))

def entry_15896 : MirrorEntry := .noFour (noFourEntry 15896 [-1653, -950, -1865, -1959]
  (1653, ⟨6, .left, {5, 6}⟩) (950, ⟨2, .left, {9}⟩)
  (1865, ⟨7, .right, {0, 1, 2, 10}⟩) (1959, ⟨8, .left, {3, 4}⟩)
  (by native_decide))

def entry_15897 : MirrorEntry := .noFour (noFourEntry 15897 [-2159, -1653, -950, -1964]
  (2159, ⟨9, .right, {0}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (1964, ⟨8, .left, {3}⟩)
  (by native_decide))

def entry_15898 : MirrorEntry := .noFour (noFourEntry 15898 [-1959, -1653, -950, -1936]
  (1959, ⟨8, .left, {3, 4}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (by native_decide))

def entry_15899 : MirrorEntry := .noFour (noFourEntry 15899 [-1959, -1653, -950, -2159]
  (1959, ⟨8, .left, {3, 4}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15900 : MirrorEntry := .noFour (noFourEntry 15900 [-1959, -1653, -950, -2151]
  (1959, ⟨8, .left, {3, 4}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15901 : MirrorEntry := .noFour (noFourEntry 15901 [-2179, -1653, -950, -1943]
  (2179, ⟨9, .left, {2, 3}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15902 : MirrorEntry := .noFour (noFourEntry 15902 [-2174, -1653, -950, -1943]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15903 : MirrorEntry := .noFour (noFourEntry 15903 [-1936, -1653, -950, -2174]
  (1936, ⟨8, .right, {0, 1, 10}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (2174, ⟨9, .left, {2, 3, 4}⟩)
  (by native_decide))

def entry_15904 : MirrorEntry := .noFour (noFourEntry 15904 [-2174, -1653, -950, -2151]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15905 : MirrorEntry := .noFour (noFourEntry 15905 [-1653, -950, -2392, -2151]
  (1653, ⟨6, .left, {5, 6}⟩) (950, ⟨2, .left, {9}⟩)
  (2392, ⟨10, .left, {1, 2}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15906 : MirrorEntry := .noFour (noFourEntry 15906 [-2383, -1653, -950, -2151]
  (2383, ⟨10, .left, {1, 2, 3, 4}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (950, ⟨2, .left, {9}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15907 : MirrorEntry := .noFour (noFourEntry 15907 [-1642, -950, -1865, -1959]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (950, ⟨2, .left, {9}⟩)
  (1865, ⟨7, .right, {0, 1, 2, 10}⟩) (1959, ⟨8, .left, {3, 4}⟩)
  (by native_decide))

def entry_15908 : MirrorEntry := .noFour (noFourEntry 15908 [-1959, -1642, -950, -1943]
  (1959, ⟨8, .left, {3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15909 : MirrorEntry := .noFour (noFourEntry 15909 [-1959, -1642, -950, -1936]
  (1959, ⟨8, .left, {3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (by native_decide))

def entry_15910 : MirrorEntry := .noFour (noFourEntry 15910 [-1959, -1642, -950, -2183]
  (1959, ⟨8, .left, {3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (2183, ⟨9, .left, {2}⟩)
  (by native_decide))

def entry_15911 : MirrorEntry := .noFour (noFourEntry 15911 [-1959, -1642, -950, -2159]
  (1959, ⟨8, .left, {3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15912 : MirrorEntry := .noFour (noFourEntry 15912 [-1959, -1642, -950, -2151]
  (1959, ⟨8, .left, {3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15913 : MirrorEntry := .noFour (noFourEntry 15913 [-1959, -1642, -2395, -950]
  (1959, ⟨8, .left, {3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (2395, ⟨10, .left, {1}⟩) (950, ⟨2, .left, {9}⟩)
  (by native_decide))

def entry_15914 : MirrorEntry := .noFour (noFourEntry 15914 [-1959, -1642, -2392, -950]
  (1959, ⟨8, .left, {3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (2392, ⟨10, .left, {1, 2}⟩) (950, ⟨2, .left, {9}⟩)
  (by native_decide))

def entry_15915 : MirrorEntry := .noFour (noFourEntry 15915 [-1642, -950, -1971, -2174]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (950, ⟨2, .left, {9}⟩)
  (1971, ⟨8, .right, {1}⟩) (2174, ⟨9, .left, {2, 3, 4}⟩)
  (by native_decide))

def entry_15916 : MirrorEntry := .noFour (noFourEntry 15916 [-2174, -1642, -950, -1943]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15917 : MirrorEntry := .noFour (noFourEntry 15917 [-2174, -1936, -1642, -950]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (1642, ⟨6, .left, {5, 6, 7}⟩) (950, ⟨2, .left, {9}⟩)
  (by native_decide))

def entry_15918 : MirrorEntry := .noFour (noFourEntry 15918 [-2174, -1642, -950, -2151]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15919 : MirrorEntry := .noFour (noFourEntry 15919 [-2174, -1642, -2395, -950]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (2395, ⟨10, .left, {1}⟩) (950, ⟨2, .left, {9}⟩)
  (by native_decide))

def entry_15920 : MirrorEntry := .noFour (noFourEntry 15920 [-2383, -1642, -950, -2159]
  (2383, ⟨10, .left, {1, 2, 3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15921 : MirrorEntry := .noFour (noFourEntry 15921 [-1642, -950, -2392, -2151]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (950, ⟨2, .left, {9}⟩)
  (2392, ⟨10, .left, {1, 2}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15922 : MirrorEntry := .noFour (noFourEntry 15922 [-2383, -1642, -950, -2151]
  (2383, ⟨10, .left, {1, 2, 3, 4}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15923 : MirrorEntry := .noFour (noFourEntry 15923 [-950, -1865, -1647, -1959]
  (950, ⟨2, .left, {9}⟩) (1865, ⟨7, .right, {0, 1, 2, 10}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1959, ⟨8, .left, {3, 4}⟩)
  (by native_decide))

def entry_15924 : MirrorEntry := .noFour (noFourEntry 15924 [-1959, -950, -1647, -1943]
  (1959, ⟨8, .left, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15925 : MirrorEntry := .noFour (noFourEntry 15925 [-1959, -950, -1647, -1936]
  (1959, ⟨8, .left, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (by native_decide))

def entry_15926 : MirrorEntry := .noFour (noFourEntry 15926 [-1959, -950, -1647, -2183]
  (1959, ⟨8, .left, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2183, ⟨9, .left, {2}⟩)
  (by native_decide))

def entry_15927 : MirrorEntry := .noFour (noFourEntry 15927 [-1959, -950, -1647, -2159]
  (1959, ⟨8, .left, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15928 : MirrorEntry := .noFour (noFourEntry 15928 [-1959, -950, -1647, -2151]
  (1959, ⟨8, .left, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15929 : MirrorEntry := .noFour (noFourEntry 15929 [-950, -2395, -1647, -1959]
  (950, ⟨2, .left, {9}⟩) (2395, ⟨10, .left, {1}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (1959, ⟨8, .left, {3, 4}⟩)
  (by native_decide))

def entry_15930 : MirrorEntry := .noFour (noFourEntry 15930 [-1959, -950, -1647, -2392]
  (1959, ⟨8, .left, {3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (by native_decide))

def entry_15931 : MirrorEntry := .noFour (noFourEntry 15931 [-950, -1971, -1647, -2174]
  (950, ⟨2, .left, {9}⟩) (1971, ⟨8, .right, {1}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2174, ⟨9, .left, {2, 3, 4}⟩)
  (by native_decide))

def entry_15932 : MirrorEntry := .noFour (noFourEntry 15932 [-2174, -1647, -950, -1943]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1647, ⟨6, .left, {5, 6, 7, 8}⟩)
  (950, ⟨2, .left, {9}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15933 : MirrorEntry := .noFour (noFourEntry 15933 [-2174, -1936, -1647, -950]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (950, ⟨2, .left, {9}⟩)
  (by native_decide))

def entry_15934 : MirrorEntry := .noFour (noFourEntry 15934 [-2174, -1647, -950, -2151]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1647, ⟨6, .left, {5, 6, 7, 8}⟩)
  (950, ⟨2, .left, {9}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15935 : MirrorEntry := .noFour (noFourEntry 15935 [-2174, -1647, -950, -2395]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1647, ⟨6, .left, {5, 6, 7, 8}⟩)
  (950, ⟨2, .left, {9}⟩) (2395, ⟨10, .left, {1}⟩)
  (by native_decide))

def entry_15936 : MirrorEntry := .noFour (noFourEntry 15936 [-2383, -950, -1647, -2159]
  (2383, ⟨10, .left, {1, 2, 3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15937 : MirrorEntry := .noFour (noFourEntry 15937 [-950, -2392, -1647, -2151]
  (950, ⟨2, .left, {9}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15938 : MirrorEntry := .noFour (noFourEntry 15938 [-2383, -950, -1647, -2151]
  (2383, ⟨10, .left, {1, 2, 3, 4}⟩) (950, ⟨2, .left, {9}⟩)
  (1647, ⟨6, .left, {5, 6, 7, 8}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15939 : MirrorEntry := .noFour (noFourEntry 15939 [-1671, -950, -1865, -1871]
  (1671, ⟨6, .right, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1865, ⟨7, .right, {0, 1, 2, 10}⟩) (1871, ⟨7, .left, {4, 5, 6}⟩)
  (by native_decide))

def entry_15940 : MirrorEntry := .noFour (noFourEntry 15940 [-1671, -950, -1871, -1943]
  (1671, ⟨6, .right, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15941 : MirrorEntry := .noFour (noFourEntry 15941 [-1671, -950, -1871, -1936]
  (1671, ⟨6, .right, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (by native_decide))

def entry_15942 : MirrorEntry := .noFour (noFourEntry 15942 [-1671, -950, -1871, -2159]
  (1671, ⟨6, .right, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15943 : MirrorEntry := .noFour (noFourEntry 15943 [-1671, -950, -1871, -2151]
  (1671, ⟨6, .right, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15944 : MirrorEntry := .noFour (noFourEntry 15944 [-1671, -950, -1865, -1864]
  (1671, ⟨6, .right, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1865, ⟨7, .right, {0, 1, 2, 10}⟩) (1864, ⟨7, .left, {4, 5, 6, 7}⟩)
  (by native_decide))

def entry_15945 : MirrorEntry := .noFour (noFourEntry 15945 [-1673, -950, -1871, -1943]
  (1673, ⟨6, .right, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15946 : MirrorEntry := .noFour (noFourEntry 15946 [-1673, -950, -1871, -1936]
  (1673, ⟨6, .right, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (by native_decide))

def entry_15947 : MirrorEntry := .noFour (noFourEntry 15947 [-1673, -950, -1871, -2159]
  (1673, ⟨6, .right, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15948 : MirrorEntry := .noFour (noFourEntry 15948 [-1673, -950, -1871, -2151]
  (1673, ⟨6, .right, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15949 : MirrorEntry := .noFour (noFourEntry 15949 [-1673, -950, -1864, -1971]
  (1673, ⟨6, .right, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (1971, ⟨8, .right, {1}⟩)
  (by native_decide))

def entry_15950 : MirrorEntry := .noFour (noFourEntry 15950 [-1673, -950, -1864, -1943]
  (1673, ⟨6, .right, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15951 : MirrorEntry := .noFour (noFourEntry 15951 [-1673, -950, -1864, -1936]
  (1673, ⟨6, .right, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (by native_decide))

def entry_15952 : MirrorEntry := .noFour (noFourEntry 15952 [-1673, -950, -1864, -2159]
  (1673, ⟨6, .right, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15953 : MirrorEntry := .noFour (noFourEntry 15953 [-1673, -950, -1864, -2151]
  (1673, ⟨6, .right, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15954 : MirrorEntry := .noFour (noFourEntry 15954 [-1673, -950, -1864, -2395]
  (1673, ⟨6, .right, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (2395, ⟨10, .left, {1}⟩)
  (by native_decide))

def entry_15955 : MirrorEntry := .noFour (noFourEntry 15955 [-2159, -950, -1675, -1871]
  (2159, ⟨9, .right, {0}⟩) (950, ⟨2, .left, {9}⟩)
  (1675, ⟨6, .right, {1, 2, 3}⟩) (1871, ⟨7, .left, {4, 5, 6}⟩)
  (by native_decide))

def entry_15956 : MirrorEntry := .noFour (noFourEntry 15956 [-950, -1871, -1675, -2151]
  (950, ⟨2, .left, {9}⟩) (1871, ⟨7, .left, {4, 5, 6}⟩)
  (1675, ⟨6, .right, {1, 2, 3}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15957 : MirrorEntry := .noFour (noFourEntry 15957 [-950, -1864, -1675, -2159]
  (950, ⟨2, .left, {9}⟩) (1864, ⟨7, .left, {4, 5, 6, 7}⟩)
  (1675, ⟨6, .right, {1, 2, 3}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15958 : MirrorEntry := .noFour (noFourEntry 15958 [-950, -1864, -1675, -2151]
  (950, ⟨2, .left, {9}⟩) (1864, ⟨7, .left, {4, 5, 6, 7}⟩)
  (1675, ⟨6, .right, {1, 2, 3}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15959 : MirrorEntry := .noFour (noFourEntry 15959 [-1964, -950, -1865, -1871]
  (1964, ⟨8, .left, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1865, ⟨7, .right, {0, 1, 2, 10}⟩) (1871, ⟨7, .left, {4, 5, 6}⟩)
  (by native_decide))

def entry_15960 : MirrorEntry := .noFour (noFourEntry 15960 [-1964, -950, -1871, -1936]
  (1964, ⟨8, .left, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (by native_decide))

def entry_15961 : MirrorEntry := .noFour (noFourEntry 15961 [-1964, -950, -1871, -2159]
  (1964, ⟨8, .left, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15962 : MirrorEntry := .noFour (noFourEntry 15962 [-1964, -950, -1871, -2151]
  (1964, ⟨8, .left, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15963 : MirrorEntry := .noFour (noFourEntry 15963 [-1943, -950, -1871, -2179]
  (1943, ⟨8, .right, {0, 1}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (2179, ⟨9, .left, {2, 3}⟩)
  (by native_decide))

def entry_15964 : MirrorEntry := .noFour (noFourEntry 15964 [-1936, -950, -1871, -2179]
  (1936, ⟨8, .right, {0, 1, 10}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (2179, ⟨9, .left, {2, 3}⟩)
  (by native_decide))

def entry_15965 : MirrorEntry := .noFour (noFourEntry 15965 [-2151, -950, -1871, -2179]
  (2151, ⟨9, .right, {0, 10}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (2179, ⟨9, .left, {2, 3}⟩)
  (by native_decide))

def entry_15966 : MirrorEntry := .noFour (noFourEntry 15966 [-2151, -950, -2392, -1871]
  (2151, ⟨9, .right, {0, 10}⟩) (950, ⟨2, .left, {9}⟩)
  (2392, ⟨10, .left, {1, 2}⟩) (1871, ⟨7, .left, {4, 5, 6}⟩)
  (by native_decide))

def entry_15967 : MirrorEntry := .noFour (noFourEntry 15967 [-2388, -950, -1871, -2151]
  (2388, ⟨10, .left, {1, 2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15968 : MirrorEntry := .noFour (noFourEntry 15968 [-1964, -950, -1865, -1864]
  (1964, ⟨8, .left, {3}⟩) (950, ⟨2, .left, {9}⟩)
  (1865, ⟨7, .right, {0, 1, 2, 10}⟩) (1864, ⟨7, .left, {4, 5, 6, 7}⟩)
  (by native_decide))

def entry_15969 : MirrorEntry := .noFour (noFourEntry 15969 [-2179, -950, -1864, -1971]
  (2179, ⟨9, .left, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (1971, ⟨8, .right, {1}⟩)
  (by native_decide))

def entry_15970 : MirrorEntry := .noFour (noFourEntry 15970 [-1943, -950, -1864, -2179]
  (1943, ⟨8, .right, {0, 1}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (2179, ⟨9, .left, {2, 3}⟩)
  (by native_decide))

def entry_15971 : MirrorEntry := .noFour (noFourEntry 15971 [-1936, -950, -1864, -2179]
  (1936, ⟨8, .right, {0, 1, 10}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (2179, ⟨9, .left, {2, 3}⟩)
  (by native_decide))

def entry_15972 : MirrorEntry := .noFour (noFourEntry 15972 [-2179, -950, -1864, -2151]
  (2179, ⟨9, .left, {2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15973 : MirrorEntry := .noFour (noFourEntry 15973 [-2388, -950, -1864, -2159]
  (2388, ⟨10, .left, {1, 2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_15974 : MirrorEntry := .noFour (noFourEntry 15974 [-950, -2392, -1864, -2151]
  (950, ⟨2, .left, {9}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15975 : MirrorEntry := .noFour (noFourEntry 15975 [-2388, -950, -1864, -2151]
  (2388, ⟨10, .left, {1, 2, 3}⟩) (950, ⟨2, .left, {9}⟩)
  (1864, ⟨7, .left, {4, 5, 6, 7}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15976 : MirrorEntry := .noFour (noFourEntry 15976 [-2183, -1943, -950, -1946]
  (2183, ⟨9, .left, {2}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (950, ⟨2, .left, {9}⟩) (1946, ⟨8, .left, {3, 4, 5, 6}⟩)
  (by native_decide))

def entry_15977 : MirrorEntry := .noFour (noFourEntry 15977 [-2183, -1936, -950, -1946]
  (2183, ⟨9, .left, {2}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (950, ⟨2, .left, {9}⟩) (1946, ⟨8, .left, {3, 4, 5, 6}⟩)
  (by native_decide))

def entry_15978 : MirrorEntry := .noFour (noFourEntry 15978 [-950, -2392, -1946, -2151]
  (950, ⟨2, .left, {9}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (1946, ⟨8, .left, {3, 4, 5, 6}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15979 : MirrorEntry := .noFour (noFourEntry 15979 [-2183, -1935, -950, -1943]
  (2183, ⟨9, .left, {2}⟩) (1935, ⟨8, .left, {3, 4, 5, 6, 7}⟩)
  (950, ⟨2, .left, {9}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15980 : MirrorEntry := .noFour (noFourEntry 15980 [-2183, -1936, -950, -1935]
  (2183, ⟨9, .left, {2}⟩) (1936, ⟨8, .right, {0, 1, 10}⟩)
  (950, ⟨2, .left, {9}⟩) (1935, ⟨8, .left, {3, 4, 5, 6, 7}⟩)
  (by native_decide))

def entry_15981 : MirrorEntry := .noFour (noFourEntry 15981 [-1935, -950, -2392, -2151]
  (1935, ⟨8, .left, {3, 4, 5, 6, 7}⟩) (950, ⟨2, .left, {9}⟩)
  (2392, ⟨10, .left, {1, 2}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15982 : MirrorEntry := .noFour (noFourEntry 15982 [-2183, -1942, -950, -1943]
  (2183, ⟨9, .left, {2}⟩) (1942, ⟨8, .left, {3, 4, 5, 6, 7, 8}⟩)
  (950, ⟨2, .left, {9}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_15983 : MirrorEntry := .noFour (noFourEntry 15983 [-1942, -950, -2392, -2151]
  (1942, ⟨8, .left, {3, 4, 5, 6, 7, 8}⟩) (950, ⟨2, .left, {9}⟩)
  (2392, ⟨10, .left, {1, 2}⟩) (2151, ⟨9, .right, {0, 10}⟩)
  (by native_decide))

def entry_15984 : MirrorEntry := .noFour (noFourEntry 15984 [-1943, -2183, -996, -951]
  (1943, ⟨8, .right, {0, 1}⟩) (2183, ⟨9, .left, {2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (951, ⟨2, .right, {7}⟩)
  (by native_decide))

def entry_15985 : MirrorEntry := .noFour (noFourEntry 15985 [-953, -1971, -996, -1369]
  (953, ⟨2, .right, {6, 7}⟩) (1971, ⟨8, .right, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_15986 : MirrorEntry := .noFour (noFourEntry 15986 [-1943, -953, -996, -1369]
  (1943, ⟨8, .right, {0, 1}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_15987 : MirrorEntry := .noFour (noFourEntry 15987 [-2183, -953, -996, -1369]
  (2183, ⟨9, .left, {2}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_15988 : MirrorEntry := .noFour (noFourEntry 15988 [-2159, -996, -1369, -953]
  (2159, ⟨9, .right, {0}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (1369, ⟨4, .right, {3, 4, 5}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_15989 : MirrorEntry := .noFour (noFourEntry 15989 [-2395, -953, -996, -1369]
  (2395, ⟨10, .left, {1}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_15990 : MirrorEntry := .noFour (noFourEntry 15990 [-2392, -953, -996, -1369]
  (2392, ⟨10, .left, {1, 2}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_15991 : MirrorEntry := .noFour (noFourEntry 15991 [-1943, -953, -1370, -996]
  (1943, ⟨8, .right, {0, 1}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (1370, ⟨4, .right, {2, 3, 4, 5}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_15992 : MirrorEntry := .noFour (noFourEntry 15992 [-2159, -1370, -996, -953]
  (2159, ⟨9, .right, {0}⟩) (1370, ⟨4, .right, {2, 3, 4, 5}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_15993 : MirrorEntry := .noFour (noFourEntry 15993 [-2395, -1370, -996, -953]
  (2395, ⟨10, .left, {1}⟩) (1370, ⟨4, .right, {2, 3, 4, 5}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_15994 : MirrorEntry := .noFour (noFourEntry 15994 [-2183, -1444, -996, -953]
  (2183, ⟨9, .left, {2}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_15995 : MirrorEntry := .noFour (noFourEntry 15995 [-1444, -2159, -996, -953]
  (1444, ⟨5, .right, {3, 4}⟩) (2159, ⟨9, .right, {0}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_15996 : MirrorEntry := .noFour (noFourEntry 15996 [-1444, -953, -2392, -996]
  (1444, ⟨5, .right, {3, 4}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (2392, ⟨10, .left, {1, 2}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_15997 : MirrorEntry := .noFour (noFourEntry 15997 [-1446, -2159, -996, -953]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (2159, ⟨9, .right, {0}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_15998 : MirrorEntry := .noFour (noFourEntry 15998 [-2159, -1448, -996, -953]
  (2159, ⟨9, .right, {0}⟩) (1448, ⟨5, .right, {1, 2, 3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_15999 : MirrorEntry := .noFour (noFourEntry 15999 [-1964, -2392, -996, -953]
  (1964, ⟨8, .left, {3}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_16000 : MirrorEntry := .noFour (noFourEntry 16000 [-1959, -2183, -996, -953]
  (1959, ⟨8, .left, {3, 4}⟩) (2183, ⟨9, .left, {2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_16001 : MirrorEntry := .noFour (noFourEntry 16001 [-1959, -2159, -996, -953]
  (1959, ⟨8, .left, {3, 4}⟩) (2159, ⟨9, .right, {0}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_16002 : MirrorEntry := .noFour (noFourEntry 16002 [-1959, -953, -2392, -996]
  (1959, ⟨8, .left, {3, 4}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (2392, ⟨10, .left, {1, 2}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16003 : MirrorEntry := .noFour (noFourEntry 16003 [-2392, -1953, -996, -953]
  (2392, ⟨10, .left, {1, 2}⟩) (1953, ⟨8, .left, {3, 4, 5}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (953, ⟨2, .right, {6, 7}⟩)
  (by native_decide))

def entry_16004 : MirrorEntry := .noFour (noFourEntry 16004 [-2383, -2159, -953, -996]
  (2383, ⟨10, .left, {1, 2, 3, 4}⟩) (2159, ⟨9, .right, {0}⟩)
  (953, ⟨2, .right, {6, 7}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16005 : MirrorEntry := .noFour (noFourEntry 16005 [-1444, -1971, -996, -955]
  (1444, ⟨5, .right, {3, 4}⟩) (1971, ⟨8, .right, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16006 : MirrorEntry := .noFour (noFourEntry 16006 [-1943, -1444, -955, -996]
  (1943, ⟨8, .right, {0, 1}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (955, ⟨2, .right, {5, 6, 7}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16007 : MirrorEntry := .noFour (noFourEntry 16007 [-2183, -1444, -996, -955]
  (2183, ⟨9, .left, {2}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16008 : MirrorEntry := .noFour (noFourEntry 16008 [-2159, -1444, -955, -996]
  (2159, ⟨9, .right, {0}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (955, ⟨2, .right, {5, 6, 7}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16009 : MirrorEntry := .noFour (noFourEntry 16009 [-1444, -2395, -996, -955]
  (1444, ⟨5, .right, {3, 4}⟩) (2395, ⟨10, .left, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16010 : MirrorEntry := .noFour (noFourEntry 16010 [-1444, -955, -2392, -996]
  (1444, ⟨5, .right, {3, 4}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (2392, ⟨10, .left, {1, 2}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16011 : MirrorEntry := .noFour (noFourEntry 16011 [-1446, -1971, -996, -955]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (1971, ⟨8, .right, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16012 : MirrorEntry := .noFour (noFourEntry 16012 [-1943, -1446, -955, -996]
  (1943, ⟨8, .right, {0, 1}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (955, ⟨2, .right, {5, 6, 7}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16013 : MirrorEntry := .noFour (noFourEntry 16013 [-1446, -2159, -996, -955]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (2159, ⟨9, .right, {0}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16014 : MirrorEntry := .noFour (noFourEntry 16014 [-1446, -955, -2395, -996]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (2395, ⟨10, .left, {1}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16015 : MirrorEntry := .noFour (noFourEntry 16015 [-2159, -1448, -996, -955]
  (2159, ⟨9, .right, {0}⟩) (1448, ⟨5, .right, {1, 2, 3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16016 : MirrorEntry := .noFour (noFourEntry 16016 [-1959, -2183, -996, -955]
  (1959, ⟨8, .left, {3, 4}⟩) (2183, ⟨9, .left, {2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16017 : MirrorEntry := .noFour (noFourEntry 16017 [-1959, -2159, -996, -955]
  (1959, ⟨8, .left, {3, 4}⟩) (2159, ⟨9, .right, {0}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16018 : MirrorEntry := .noFour (noFourEntry 16018 [-1959, -2395, -996, -955]
  (1959, ⟨8, .left, {3, 4}⟩) (2395, ⟨10, .left, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16019 : MirrorEntry := .noFour (noFourEntry 16019 [-1959, -2392, -996, -955]
  (1959, ⟨8, .left, {3, 4}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16020 : MirrorEntry := .noFour (noFourEntry 16020 [-2174, -1971, -996, -955]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1971, ⟨8, .right, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16021 : MirrorEntry := .noFour (noFourEntry 16021 [-2174, -1943, -955, -996]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (955, ⟨2, .right, {5, 6, 7}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16022 : MirrorEntry := .noFour (noFourEntry 16022 [-2174, -2395, -996, -955]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (2395, ⟨10, .left, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16023 : MirrorEntry := .noFour (noFourEntry 16023 [-2383, -2159, -996, -955]
  (2383, ⟨10, .left, {1, 2, 3, 4}⟩) (2159, ⟨9, .right, {0}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (955, ⟨2, .right, {5, 6, 7}⟩)
  (by native_decide))

def entry_16024 : MirrorEntry := .noFour (noFourEntry 16024 [-1162, -2392, -996, -957]
  (1162, ⟨3, .left, {8}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (957, ⟨2, .right, {4, 5, 6, 7}⟩)
  (by native_decide))

def entry_16025 : MirrorEntry := .noFour (noFourEntry 16025 [-1162, -2392, -996, -1369]
  (1162, ⟨3, .left, {8}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16026 : MirrorEntry := .noFour (noFourEntry 16026 [-1673, -1162, -1871, -996]
  (1673, ⟨6, .right, {2, 3}⟩) (1162, ⟨3, .left, {8}⟩)
  (1871, ⟨7, .left, {4, 5, 6}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16027 : MirrorEntry := .noFour (noFourEntry 16027 [-1172, -1943, -996, -1369]
  (1172, ⟨3, .right, {6}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16028 : MirrorEntry := .noFour (noFourEntry 16028 [-1172, -2159, -996, -1369]
  (1172, ⟨3, .right, {6}⟩) (2159, ⟨9, .right, {0}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16029 : MirrorEntry := .noFour (noFourEntry 16029 [-1444, -1174, -996, -1943]
  (1444, ⟨5, .right, {3, 4}⟩) (1174, ⟨3, .right, {5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_16030 : MirrorEntry := .noFour (noFourEntry 16030 [-1444, -1174, -996, -2159]
  (1444, ⟨5, .right, {3, 4}⟩) (1174, ⟨3, .right, {5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_16031 : MirrorEntry := .noFour (noFourEntry 16031 [-1943, -1174, -996, -1446]
  (1943, ⟨8, .right, {0, 1}⟩) (1174, ⟨3, .right, {5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (by native_decide))

def entry_16032 : MirrorEntry := .noFour (noFourEntry 16032 [-1446, -1174, -996, -2159]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (1174, ⟨3, .right, {5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_16033 : MirrorEntry := .noFour (noFourEntry 16033 [-2159, -1174, -996, -1448]
  (2159, ⟨9, .right, {0}⟩) (1174, ⟨3, .right, {5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1448, ⟨5, .right, {1, 2, 3, 4}⟩)
  (by native_decide))

def entry_16034 : MirrorEntry := .noFour (noFourEntry 16034 [-2159, -1174, -996, -1673]
  (2159, ⟨9, .right, {0}⟩) (1174, ⟨3, .right, {5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1673, ⟨6, .right, {2, 3}⟩)
  (by native_decide))

def entry_16035 : MirrorEntry := .noFour (noFourEntry 16035 [-2159, -1174, -996, -1964]
  (2159, ⟨9, .right, {0}⟩) (1174, ⟨3, .right, {5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1964, ⟨8, .left, {3}⟩)
  (by native_decide))

def entry_16036 : MirrorEntry := .noFour (noFourEntry 16036 [-1959, -1174, -996, -2159]
  (1959, ⟨8, .left, {3, 4}⟩) (1174, ⟨3, .right, {5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_16037 : MirrorEntry := .noFour (noFourEntry 16037 [-1943, -1174, -996, -2174]
  (1943, ⟨8, .right, {0, 1}⟩) (1174, ⟨3, .right, {5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2174, ⟨9, .left, {2, 3, 4}⟩)
  (by native_decide))

def entry_16038 : MirrorEntry := .noFour (noFourEntry 16038 [-1671, -1176, -996, -1943]
  (1671, ⟨6, .right, {3}⟩) (1176, ⟨3, .right, {4, 5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_16039 : MirrorEntry := .noFour (noFourEntry 16039 [-1671, -1176, -996, -2159]
  (1671, ⟨6, .right, {3}⟩) (1176, ⟨3, .right, {4, 5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_16040 : MirrorEntry := .noFour (noFourEntry 16040 [-1673, -1176, -996, -1943]
  (1673, ⟨6, .right, {2, 3}⟩) (1176, ⟨3, .right, {4, 5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_16041 : MirrorEntry := .noFour (noFourEntry 16041 [-1673, -1176, -996, -2159]
  (1673, ⟨6, .right, {2, 3}⟩) (1176, ⟨3, .right, {4, 5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_16042 : MirrorEntry := .noFour (noFourEntry 16042 [-1176, -1675, -996, -2159]
  (1176, ⟨3, .right, {4, 5, 6}⟩) (1675, ⟨6, .right, {1, 2, 3}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_16043 : MirrorEntry := .noFour (noFourEntry 16043 [-1964, -1176, -996, -2159]
  (1964, ⟨8, .left, {3}⟩) (1176, ⟨3, .right, {4, 5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_16044 : MirrorEntry := .noFour (noFourEntry 16044 [-2179, -1176, -996, -1943]
  (2179, ⟨9, .left, {2, 3}⟩) (1176, ⟨3, .right, {4, 5, 6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_16045 : MirrorEntry := .noFour (noFourEntry 16045 [-1943, -1429, -996, -1369]
  (1943, ⟨8, .right, {0, 1}⟩) (1429, ⟨5, .left, {6}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16046 : MirrorEntry := .noFour (noFourEntry 16046 [-2159, -996, -1369, -1429]
  (2159, ⟨9, .right, {0}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (1369, ⟨4, .right, {3, 4, 5}⟩) (1429, ⟨5, .left, {6}⟩)
  (by native_decide))

def entry_16047 : MirrorEntry := .noFour (noFourEntry 16047 [-1418, -1971, -996, -1369]
  (1418, ⟨5, .left, {6, 7}⟩) (1971, ⟨8, .right, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16048 : MirrorEntry := .noFour (noFourEntry 16048 [-1943, -1418, -1369, -996]
  (1943, ⟨8, .right, {0, 1}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (1369, ⟨4, .right, {3, 4, 5}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16049 : MirrorEntry := .noFour (noFourEntry 16049 [-2183, -1418, -1369, -996]
  (2183, ⟨9, .left, {2}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (1369, ⟨4, .right, {3, 4, 5}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16050 : MirrorEntry := .noFour (noFourEntry 16050 [-2159, -1418, -996, -1369]
  (2159, ⟨9, .right, {0}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16051 : MirrorEntry := .noFour (noFourEntry 16051 [-1418, -2395, -996, -1369]
  (1418, ⟨5, .left, {6, 7}⟩) (2395, ⟨10, .left, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16052 : MirrorEntry := .noFour (noFourEntry 16052 [-1418, -2392, -996, -1369]
  (1418, ⟨5, .left, {6, 7}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16053 : MirrorEntry := .noFour (noFourEntry 16053 [-1971, -1422, -996, -1369]
  (1971, ⟨8, .right, {1}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16054 : MirrorEntry := .noFour (noFourEntry 16054 [-1943, -1422, -1369, -996]
  (1943, ⟨8, .right, {0, 1}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (1369, ⟨4, .right, {3, 4, 5}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16055 : MirrorEntry := .noFour (noFourEntry 16055 [-1422, -2183, -996, -1369]
  (1422, ⟨5, .left, {6, 7, 8}⟩) (2183, ⟨9, .left, {2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16056 : MirrorEntry := .noFour (noFourEntry 16056 [-2159, -996, -1369, -1422]
  (2159, ⟨9, .right, {0}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (1369, ⟨4, .right, {3, 4, 5}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (by native_decide))

def entry_16057 : MirrorEntry := .noFour (noFourEntry 16057 [-1422, -2395, -996, -1369]
  (1422, ⟨5, .left, {6, 7, 8}⟩) (2395, ⟨10, .left, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16058 : MirrorEntry := .noFour (noFourEntry 16058 [-1422, -2392, -996, -1369]
  (1422, ⟨5, .left, {6, 7, 8}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1369, ⟨4, .right, {3, 4, 5}⟩)
  (by native_decide))

def entry_16059 : MirrorEntry := .noFour (noFourEntry 16059 [-1418, -1370, -996, -1943]
  (1418, ⟨5, .left, {6, 7}⟩) (1370, ⟨4, .right, {2, 3, 4, 5}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_16060 : MirrorEntry := .noFour (noFourEntry 16060 [-2159, -1418, -996, -1370]
  (2159, ⟨9, .right, {0}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1370, ⟨4, .right, {2, 3, 4, 5}⟩)
  (by native_decide))

def entry_16061 : MirrorEntry := .noFour (noFourEntry 16061 [-1418, -2395, -996, -1370]
  (1418, ⟨5, .left, {6, 7}⟩) (2395, ⟨10, .left, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1370, ⟨4, .right, {2, 3, 4, 5}⟩)
  (by native_decide))

def entry_16062 : MirrorEntry := .noFour (noFourEntry 16062 [-1370, -1422, -996, -1943]
  (1370, ⟨4, .right, {2, 3, 4, 5}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_16063 : MirrorEntry := .noFour (noFourEntry 16063 [-2159, -1422, -996, -1370]
  (2159, ⟨9, .right, {0}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1370, ⟨4, .right, {2, 3, 4, 5}⟩)
  (by native_decide))

def entry_16064 : MirrorEntry := .noFour (noFourEntry 16064 [-2395, -1422, -996, -1370]
  (2395, ⟨10, .left, {1}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1370, ⟨4, .right, {2, 3, 4, 5}⟩)
  (by native_decide))

def entry_16065 : MirrorEntry := .noFour (noFourEntry 16065 [-1943, -1444, -996, -1418]
  (1943, ⟨8, .right, {0, 1}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (by native_decide))

def entry_16066 : MirrorEntry := .noFour (noFourEntry 16066 [-2183, -1444, -996, -1418]
  (2183, ⟨9, .left, {2}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (by native_decide))

def entry_16067 : MirrorEntry := .noFour (noFourEntry 16067 [-2159, -1444, -996, -1418]
  (2159, ⟨9, .right, {0}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (by native_decide))

def entry_16068 : MirrorEntry := .noFour (noFourEntry 16068 [-1444, -2395, -996, -1418]
  (1444, ⟨5, .right, {3, 4}⟩) (2395, ⟨10, .left, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (by native_decide))

def entry_16069 : MirrorEntry := .noFour (noFourEntry 16069 [-1444, -2392, -996, -1418]
  (1444, ⟨5, .right, {3, 4}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (by native_decide))

def entry_16070 : MirrorEntry := .noFour (noFourEntry 16070 [-1943, -1446, -996, -1418]
  (1943, ⟨8, .right, {0, 1}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (by native_decide))

def entry_16071 : MirrorEntry := .noFour (noFourEntry 16071 [-2159, -1446, -996, -1418]
  (2159, ⟨9, .right, {0}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (by native_decide))

def entry_16072 : MirrorEntry := .noFour (noFourEntry 16072 [-1446, -2395, -996, -1418]
  (1446, ⟨5, .right, {2, 3, 4}⟩) (2395, ⟨10, .left, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (by native_decide))

def entry_16073 : MirrorEntry := .noFour (noFourEntry 16073 [-2159, -1418, -996, -1448]
  (2159, ⟨9, .right, {0}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1448, ⟨5, .right, {1, 2, 3, 4}⟩)
  (by native_decide))

def entry_16074 : MirrorEntry := .noFour (noFourEntry 16074 [-1959, -1418, -996, -2183]
  (1959, ⟨8, .left, {3, 4}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2183, ⟨9, .left, {2}⟩)
  (by native_decide))

def entry_16075 : MirrorEntry := .noFour (noFourEntry 16075 [-1959, -1418, -996, -2159]
  (1959, ⟨8, .left, {3, 4}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_16076 : MirrorEntry := .noFour (noFourEntry 16076 [-1418, -2395, -996, -1959]
  (1418, ⟨5, .left, {6, 7}⟩) (2395, ⟨10, .left, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1959, ⟨8, .left, {3, 4}⟩)
  (by native_decide))

def entry_16077 : MirrorEntry := .noFour (noFourEntry 16077 [-1959, -1418, -2392, -996]
  (1959, ⟨8, .left, {3, 4}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (2392, ⟨10, .left, {1, 2}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16078 : MirrorEntry := .noFour (noFourEntry 16078 [-1418, -1953, -996, -2392]
  (1418, ⟨5, .left, {6, 7}⟩) (1953, ⟨8, .left, {3, 4, 5}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (by native_decide))

def entry_16079 : MirrorEntry := .noFour (noFourEntry 16079 [-2174, -1943, -1418, -996]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (1418, ⟨5, .left, {6, 7}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16080 : MirrorEntry := .noFour (noFourEntry 16080 [-2174, -1418, -2395, -996]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (2395, ⟨10, .left, {1}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16081 : MirrorEntry := .noFour (noFourEntry 16081 [-2383, -1418, -996, -2159]
  (2383, ⟨10, .left, {1, 2, 3, 4}⟩) (1418, ⟨5, .left, {6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_16082 : MirrorEntry := .noFour (noFourEntry 16082 [-1943, -1444, -996, -1422]
  (1943, ⟨8, .right, {0, 1}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (by native_decide))

def entry_16083 : MirrorEntry := .noFour (noFourEntry 16083 [-2183, -1444, -996, -1422]
  (2183, ⟨9, .left, {2}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (by native_decide))

def entry_16084 : MirrorEntry := .noFour (noFourEntry 16084 [-2159, -1444, -996, -1422]
  (2159, ⟨9, .right, {0}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (by native_decide))

def entry_16085 : MirrorEntry := .noFour (noFourEntry 16085 [-1444, -2395, -996, -1422]
  (1444, ⟨5, .right, {3, 4}⟩) (2395, ⟨10, .left, {1}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (by native_decide))

def entry_16086 : MirrorEntry := .noFour (noFourEntry 16086 [-1444, -2392, -996, -1422]
  (1444, ⟨5, .right, {3, 4}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (by native_decide))

def entry_16087 : MirrorEntry := .noFour (noFourEntry 16087 [-1943, -1422, -996, -1446]
  (1943, ⟨8, .right, {0, 1}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (by native_decide))

def entry_16088 : MirrorEntry := .noFour (noFourEntry 16088 [-2159, -1422, -996, -1446]
  (2159, ⟨9, .right, {0}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (by native_decide))

def entry_16089 : MirrorEntry := .noFour (noFourEntry 16089 [-2395, -1422, -996, -1446]
  (2395, ⟨10, .left, {1}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1446, ⟨5, .right, {2, 3, 4}⟩)
  (by native_decide))

def entry_16090 : MirrorEntry := .noFour (noFourEntry 16090 [-2159, -1422, -996, -1448]
  (2159, ⟨9, .right, {0}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1448, ⟨5, .right, {1, 2, 3, 4}⟩)
  (by native_decide))

def entry_16091 : MirrorEntry := .noFour (noFourEntry 16091 [-1959, -1422, -996, -2183]
  (1959, ⟨8, .left, {3, 4}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2183, ⟨9, .left, {2}⟩)
  (by native_decide))

def entry_16092 : MirrorEntry := .noFour (noFourEntry 16092 [-2159, -1959, -1422, -996]
  (2159, ⟨9, .right, {0}⟩) (1959, ⟨8, .left, {3, 4}⟩)
  (1422, ⟨5, .left, {6, 7, 8}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16093 : MirrorEntry := .noFour (noFourEntry 16093 [-2395, -1422, -996, -1959]
  (2395, ⟨10, .left, {1}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1959, ⟨8, .left, {3, 4}⟩)
  (by native_decide))

def entry_16094 : MirrorEntry := .noFour (noFourEntry 16094 [-1959, -2392, -1422, -996]
  (1959, ⟨8, .left, {3, 4}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (1422, ⟨5, .left, {6, 7, 8}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16095 : MirrorEntry := .noFour (noFourEntry 16095 [-2183, -1953, -1422, -996]
  (2183, ⟨9, .left, {2}⟩) (1953, ⟨8, .left, {3, 4, 5}⟩)
  (1422, ⟨5, .left, {6, 7, 8}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16096 : MirrorEntry := .noFour (noFourEntry 16096 [-1953, -1422, -996, -2392]
  (1953, ⟨8, .left, {3, 4, 5}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (by native_decide))

def entry_16097 : MirrorEntry := .noFour (noFourEntry 16097 [-2174, -1943, -1422, -996]
  (2174, ⟨9, .left, {2, 3, 4}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (1422, ⟨5, .left, {6, 7, 8}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16098 : MirrorEntry := .noFour (noFourEntry 16098 [-2395, -1422, -996, -2174]
  (2395, ⟨10, .left, {1}⟩) (1422, ⟨5, .left, {6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2174, ⟨9, .left, {2, 3, 4}⟩)
  (by native_decide))

def entry_16099 : MirrorEntry := .noFour (noFourEntry 16099 [-2383, -2159, -1422, -996]
  (2383, ⟨10, .left, {1, 2, 3, 4}⟩) (2159, ⟨9, .right, {0}⟩)
  (1422, ⟨5, .left, {6, 7, 8}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16100 : MirrorEntry := .noFour (noFourEntry 16100 [-1653, -1444, -996, -1943]
  (1653, ⟨6, .left, {5, 6}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_16101 : MirrorEntry := .noFour (noFourEntry 16101 [-2159, -1653, -1444, -996]
  (2159, ⟨9, .right, {0}⟩) (1653, ⟨6, .left, {5, 6}⟩)
  (1444, ⟨5, .right, {3, 4}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16102 : MirrorEntry := .noFour (noFourEntry 16102 [-1642, -1444, -996, -1971]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1971, ⟨8, .right, {1}⟩)
  (by native_decide))

def entry_16103 : MirrorEntry := .noFour (noFourEntry 16103 [-1642, -1444, -996, -1943]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1943, ⟨8, .right, {0, 1}⟩)
  (by native_decide))

def entry_16104 : MirrorEntry := .noFour (noFourEntry 16104 [-2183, -1642, -996, -1444]
  (2183, ⟨9, .left, {2}⟩) (1642, ⟨6, .left, {5, 6, 7}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (by native_decide))

def entry_16105 : MirrorEntry := .noFour (noFourEntry 16105 [-1642, -1444, -996, -2159]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2159, ⟨9, .right, {0}⟩)
  (by native_decide))

def entry_16106 : MirrorEntry := .noFour (noFourEntry 16106 [-1642, -1444, -2395, -996]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (2395, ⟨10, .left, {1}⟩) (996, ⟨2, .left, {9, 10}⟩)
  (by native_decide))

def entry_16107 : MirrorEntry := .noFour (noFourEntry 16107 [-1642, -1444, -996, -2392]
  (1642, ⟨6, .left, {5, 6, 7}⟩) (1444, ⟨5, .right, {3, 4}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (2392, ⟨10, .left, {1, 2}⟩)
  (by native_decide))

def entry_16108 : MirrorEntry := .noFour (noFourEntry 16108 [-1444, -1647, -996, -1971]
  (1444, ⟨5, .right, {3, 4}⟩) (1647, ⟨6, .left, {5, 6, 7, 8}⟩)
  (996, ⟨2, .left, {9, 10}⟩) (1971, ⟨8, .right, {1}⟩)
  (by native_decide))

def bridgeChunk30 : List MirrorEntry := [
  entry_15853,
  entry_15854,
  entry_15855,
  entry_15856,
  entry_15857,
  entry_15858,
  entry_15859,
  entry_15860,
  entry_15861,
  entry_15862,
  entry_15863,
  entry_15864,
  entry_15865,
  entry_15866,
  entry_15867,
  entry_15868,
  entry_15869,
  entry_15870,
  entry_15871,
  entry_15872,
  entry_15873,
  entry_15874,
  entry_15875,
  entry_15876,
  entry_15877,
  entry_15878,
  entry_15879,
  entry_15880,
  entry_15881,
  entry_15882,
  entry_15883,
  entry_15884,
  entry_15885,
  entry_15886,
  entry_15887,
  entry_15888,
  entry_15889,
  entry_15890,
  entry_15891,
  entry_15892,
  entry_15893,
  entry_15894,
  entry_15895,
  entry_15896,
  entry_15897,
  entry_15898,
  entry_15899,
  entry_15900,
  entry_15901,
  entry_15902,
  entry_15903,
  entry_15904,
  entry_15905,
  entry_15906,
  entry_15907,
  entry_15908,
  entry_15909,
  entry_15910,
  entry_15911,
  entry_15912,
  entry_15913,
  entry_15914,
  entry_15915,
  entry_15916,
  entry_15917,
  entry_15918,
  entry_15919,
  entry_15920,
  entry_15921,
  entry_15922,
  entry_15923,
  entry_15924,
  entry_15925,
  entry_15926,
  entry_15927,
  entry_15928,
  entry_15929,
  entry_15930,
  entry_15931,
  entry_15932,
  entry_15933,
  entry_15934,
  entry_15935,
  entry_15936,
  entry_15937,
  entry_15938,
  entry_15939,
  entry_15940,
  entry_15941,
  entry_15942,
  entry_15943,
  entry_15944,
  entry_15945,
  entry_15946,
  entry_15947,
  entry_15948,
  entry_15949,
  entry_15950,
  entry_15951,
  entry_15952,
  entry_15953,
  entry_15954,
  entry_15955,
  entry_15956,
  entry_15957,
  entry_15958,
  entry_15959,
  entry_15960,
  entry_15961,
  entry_15962,
  entry_15963,
  entry_15964,
  entry_15965,
  entry_15966,
  entry_15967,
  entry_15968,
  entry_15969,
  entry_15970,
  entry_15971,
  entry_15972,
  entry_15973,
  entry_15974,
  entry_15975,
  entry_15976,
  entry_15977,
  entry_15978,
  entry_15979,
  entry_15980,
  entry_15981,
  entry_15982,
  entry_15983,
  entry_15984,
  entry_15985,
  entry_15986,
  entry_15987,
  entry_15988,
  entry_15989,
  entry_15990,
  entry_15991,
  entry_15992,
  entry_15993,
  entry_15994,
  entry_15995,
  entry_15996,
  entry_15997,
  entry_15998,
  entry_15999,
  entry_16000,
  entry_16001,
  entry_16002,
  entry_16003,
  entry_16004,
  entry_16005,
  entry_16006,
  entry_16007,
  entry_16008,
  entry_16009,
  entry_16010,
  entry_16011,
  entry_16012,
  entry_16013,
  entry_16014,
  entry_16015,
  entry_16016,
  entry_16017,
  entry_16018,
  entry_16019,
  entry_16020,
  entry_16021,
  entry_16022,
  entry_16023,
  entry_16024,
  entry_16025,
  entry_16026,
  entry_16027,
  entry_16028,
  entry_16029,
  entry_16030,
  entry_16031,
  entry_16032,
  entry_16033,
  entry_16034,
  entry_16035,
  entry_16036,
  entry_16037,
  entry_16038,
  entry_16039,
  entry_16040,
  entry_16041,
  entry_16042,
  entry_16043,
  entry_16044,
  entry_16045,
  entry_16046,
  entry_16047,
  entry_16048,
  entry_16049,
  entry_16050,
  entry_16051,
  entry_16052,
  entry_16053,
  entry_16054,
  entry_16055,
  entry_16056,
  entry_16057,
  entry_16058,
  entry_16059,
  entry_16060,
  entry_16061,
  entry_16062,
  entry_16063,
  entry_16064,
  entry_16065,
  entry_16066,
  entry_16067,
  entry_16068,
  entry_16069,
  entry_16070,
  entry_16071,
  entry_16072,
  entry_16073,
  entry_16074,
  entry_16075,
  entry_16076,
  entry_16077,
  entry_16078,
  entry_16079,
  entry_16080,
  entry_16081,
  entry_16082,
  entry_16083,
  entry_16084,
  entry_16085,
  entry_16086,
  entry_16087,
  entry_16088,
  entry_16089,
  entry_16090,
  entry_16091,
  entry_16092,
  entry_16093,
  entry_16094,
  entry_16095,
  entry_16096,
  entry_16097,
  entry_16098,
  entry_16099,
  entry_16100,
  entry_16101,
  entry_16102,
  entry_16103,
  entry_16104,
  entry_16105,
  entry_16106,
  entry_16107,
  entry_16108,
]

theorem bridgeChunk30_wf : bridgeChunk30.all MirrorEntry.wf = true := by native_decide

theorem bridgeChunk30_length : bridgeChunk30.length = 256 := by native_decide

end Problem97.P4MirrorOuterOccurrenceBridgeScratch
