import Erdos9796Proof.P97.ATail.FrontierLiveClosure

/-! Trust audit for the source-clean cap-wide contradiction search. -/

#print axioms Problem97.ATailRetainedCollisionCapLocalization.actualRow_center_eq_commonBlocker_of_contains_collisionSources
#print axioms Problem97.ATailRetainedCollisionCapLocalization.actualRow_center_eq_commonBlocker_of_sameCap_outside_sources
#print axioms Problem97.ATailGlobalMinimalDeletion.exists_global_cardMinimal_blocking_subdeletion
#print axioms Problem97.ATailGlobalMinimalDeletion.exists_fresh_sharedRadiusPair_or_minimalDeletionCore
#print axioms Problem97.ATailGlobalMinimalDeletion.five_le_selectedClass_of_restoration_and_sharedRadius
#print axioms Problem97.ATAILStageOneMinimalDeletionCore.MinimalDeletionCore.capByIndex_card_ge_six
#print axioms Problem97.ATailMinimalUniqueFourCover.exists_isUniqueFourCenter_of_minimal
#print axioms Problem97.ATailApexRichClassStructure.criticalShell_inter_oppositeCapClassInterior_card_le_two_of_apexRich
#print axioms Problem97.ATailApexRichClassStructure.uniqueFourCover_of_triApexRobust
#print axioms Problem97.ATailFrontierLiveClosure.false_of_exactFourMutualOmission_fourCenterCommonDeletion
