import Erdos9796Proof.P97.ATail.FrontierLiveClosure

#print axioms Problem97.ATailFrontierLiveClosure.exists_three_hit_or_collision_crossHit_of_two_sourceExactCollisionRows
#print axioms Problem97.ATailFrontierLiveClosure.exists_three_hit_of_two_collisionRows_capCross_normalForm
#print axioms Problem97.ATailFrontierLiveClosure.exists_three_hit_of_two_exactFourInteriorTwo_distinctRadiusBlockerCollisions
#print axioms Problem97.ATailFrontierLiveClosure.false_of_two_exactFourInteriorTwo_distinctRadiusBlockerCollisions_and_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.false_of_exactFourCollision_interior_eq_two_secondRadius_and_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.false_of_exactFourCollision_secondRadius_and_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.false_of_localizedCollisionMutualOmissionCycle_exactTwo_and_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.false_of_retainedInteriorBlockerCollision_and_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsTriApex_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.exists_criticalShell_oppositeCapClassInterior_card_ge_three_of_frontierAllLargeCapsTriApex
#print axioms Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsTriApexUniformMetricResidual
#print axioms Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsTriApexRobustResidual
#print axioms Problem97.ATailFrontierLiveClosure.criticalShellCenter_mem_capInteriorByIndex_of_two_hits
#print axioms Problem97.ATailFrontierLiveClosure.nonempty_retainedInteriorDirectedOmission_of_collision_of_capInterior_card_ge_three
#print axioms Problem97.ATailFrontierLiveClosure.nonempty_retainedInteriorDirectedOmission_of_collision_of_frontierClass_card_ge_five
#print axioms Problem97.ATailApexRichClassStructure.oppositeCapRichClassInteriorPattern_of_apexRichClassStructure
#print axioms Problem97.ATailApexRichClassStructure.fullyDeletionRobustAt_of_apexRichClassStructure
#print axioms Problem97.ATailCapApexRadiusRigidity.capInteriorByIndex_card_add_two

#check @Problem97.ATailFrontierLiveClosure.exists_three_hit_or_collision_crossHit_of_two_sourceExactCollisionRows
#check @Problem97.ATailFrontierLiveClosure.exists_three_hit_of_two_collisionRows_capCross_normalForm
#check @Problem97.ATailFrontierLiveClosure.criticalShellCenter_mem_capInteriorByIndex_of_two_hits
#check @Problem97.ATailFrontierLiveClosure.nonempty_retainedInteriorDirectedOmission_of_collision_of_capInterior_card_ge_three
#check @Problem97.ATailFrontierLiveClosure.nonempty_retainedInteriorDirectedOmission_of_collision_of_frontierClass_card_ge_five
#check @Problem97.ATailApexRichClassStructure.oppositeCapRichClassInteriorPattern_of_apexRichClassStructure
#check @Problem97.ATailApexRichClassStructure.fullyDeletionRobustAt_of_apexRichClassStructure
#check @Problem97.ATailCapApexRadiusRigidity.capInteriorByIndex_card_add_two
