import Erdos9796Proof.P97.ATail.FrontierLiveClosure

#print axioms Problem97.ATailFirstFiberOverlapDescent.exists_two_firstFiber_points_omitted_by_row
#print axioms Problem97.ATailFirstFiberOverlapDescent.false_of_firstFiber_explicit_overlap_card_ge_three
#print axioms Problem97.ATailFirstFiberOverlapDescent.false_of_firstFiber_bothOutsideHits_and_firstPairHit
#print axioms Problem97.ATailFirstFiberOverlapDescent.false_of_firstFiber_twoOutsideHits_of_capCenter
#print axioms Problem97.ATailApexRichClassStructure.oppositeCapRichClassInteriorPattern_of_apexRichClassStructure
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_capSource_freshOutsideFirstBlockerFiber_alignedSingletonRadius
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_capSource_freshOutsideFirstBlockerFiber_alignedRadii
