import Erdos9796Proof.P97.ATail.FrontierLiveClosure

open Problem97

#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_equalBlockers_complementaryMembership
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_twoCapSources_mutualCrossMembership_distinctBlockers
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_twoCapSources_firstFiber
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_capSourceThirdCanonicalRowSurface
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.secondBlocker_dist_ne_of_freshOutsideFirstBlockerFiber
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.firstFiber_shell_eq_explicitFour
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_freshThird_sameCapCrossRowAlignment
#print axioms Problem97.ATailFirstFiberOverlapDescent.false_of_firstFiber_twoOutsideHits_of_capCenter
#print axioms Problem97.ATailFirstFiberOverlapDescent.false_of_firstFiber_explicit_overlap_card_ge_three
#print axioms Problem97.ATailBlockerMultiplicityGeometry.collisionCrossHit_or_geometricMultiplicity
