import Mathlib
#check Finset.card_union_of_disjoint
#check Finset.disjoint_left
#check Finset.card_union_le
#check Finset.mem_image
#check Finset.card_eq_two
#check Finset.card_eq_two.mp
#check Finset.subset_union
#check Finset.inter_subset_left
#check Finset.disjoint_left
