import Erdos9796Proof.P97.ATail.FrontierLiveClosure
open Problem97
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_or_freshCap_ne_opp_of_commonRadius_distinctCaps
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.freshThird_commonRadius_distinctCaps_dual_packet
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.freshThird_canonicalSource_differentFreshCap_sharedPairCyclicPacket
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.freshThird_canonicalDifferentCap_boundary
