import Erdos9796Proof.P97.ATail.FrontierLiveClosure

open scoped BigOperators

#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_capSourceThirdCanonicalRowSurface
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_capSource_alignedSingletonRadius_of_secondBlocker_nonbisector
#print axioms Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsTriApexRobustResidual
#print axioms Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal.false_of_freshThird_sameCapCrossRowAlignment
#print axioms Problem97.ATailFrontierLiveClosure.exists_three_hit_of_two_collisionRows_capCross_normalForm
#print axioms Problem97.ATailFrontierLiveClosure.exists_three_hit_or_collision_crossHit_of_two_sourceExactCollisionRows
#print axioms Problem97.ATailFrontierLiveClosure.exists_three_hit_of_two_exactFourInteriorTwo_distinctRadiusBlockerCollisions
#print axioms Problem97.ATailFrontierLiveClosure.collisionCrossHit_or_geometricMultiplicity
#print axioms Problem97.ATailFrontierLiveClosure.six_interior_or_cross_blocker_coincidence
