import Erdos9796Proof.P97.ATail.FrontierLiveClosure

open scoped EuclideanGeometry

open Problem97
open Problem97.ATailFrontierLiveClosure
open Problem97.ATailCriticalPairFrontier
open Problem97.ATailBlockerMultiplicityGeometry

#check Problem97.ATailFrontierLiveClosure.firstFiberCapSource_firstApexRadius_eq_singleton_of_aligned
#check Problem97.ATailFrontierLiveClosure.false_of_two_freshThirdCrossRowHits_distinctCenters
#check Problem97.ATailFrontierLiveClosure.freshThirdEqualCenterExactFourRow_of_hits
#check Problem97.ATailFrontierLiveClosure.allCollisionEndpointsOmitted_of_equalCenterHits
#check Problem97.ATailFrontierLiveClosure.commonCollisionEndpointOmission_of_equalCenterHits
#check Problem97.ATailFrontierLiveClosure.mutualCrossMembership_or_oneSidedDeletionSurvival
#check Problem97.ATailFrontierLiveClosure.sourceDeletionSurvival_or_blockerVertex_eq_mutualPair
