import Erdos9796Proof.P97.ATail.FrontierLiveClosure

#print axioms Problem97.ATailGlobalMinimalDeletion.exists_global_cardMinimal_blocking_subdeletion
#print axioms Problem97.ATAILStageOnePrescribedApexDichotomy.double_erase_survives_or_two_disjoint_exact_shells
#print axioms Problem97.ATailOrientedPhysicalApexIngress.FrontierCommonDeletionParentResidual.firstApexFullyDeletionRobust
#print axioms Problem97.ATailCriticalPairFrontier.cumulative_deletion_blocked_at_source_blocker
#print axioms Problem97.ATailFirstFiberOverlapDescent.false_of_firstFiber_twoOutsideHits_of_capCenter
#print axioms Problem97.ATailFrontierLiveClosure.exists_three_hit_of_two_exactFourInteriorTwo_distinctRadiusBlockerCollisions
