import Erdos9796Proof.P97.ATail.FrontierLiveClosure

open Problem97
open Problem97.ATailFrontierLiveClosure

#print axioms Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsTriApex_all_low_hits
#print axioms Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsTriApexUniformMetricResidual
#print axioms Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsTriApexRobustResidual
#print axioms Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsBiApexRobustResidual
#print axioms Problem97.ATailFrontierLiveClosure.exists_criticalShell_oppositeCapClassInterior_card_ge_three_of_frontierAllLargeCapsTriApex
#check Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsTriApex_all_low_hits
#check Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsTriApexUniformMetricResidual
#check Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsTriApexRobustResidual
#check Problem97.ATailFrontierLiveClosure.false_of_frontierAllLargeCapsBiApexRobustResidual
