import Erdos9796Proof.P97.ATail.FrontierLiveClosure
open Problem97
open Problem97.ATailFrontierLiveClosure
namespace Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal
#print axioms false_of_crossBlockerCoincidence
#print axioms false_of_capSourceThirdCanonicalRowSurface
#print axioms false_of_freshThird_sameCapCrossRowAlignment
#print axioms false_of_capSource_freshThirdBlockerFiber_without_sameCapCrossRow
#print axioms false_of_capSource_freshThirdBlockerFiber
#print axioms firstFiber_shell_eq_explicitFour
#print axioms secondBlocker_dist_ne_of_freshOutsideFirstBlockerFiber
#print axioms commonCollisionEndpointOmission_or_complementaryMembership
#print axioms false_of_equalBlockers_complementaryMembership
#print axioms mutualCrossMembership_or_oneSidedDeletionSurvival
#print axioms selectedSupports_inter_eq_sources_of_mutualCrossMembership_distinctBlockers
#print axioms blockerVertex_eq_one_of_mutualPair_of_selectedRow_contains_sources
#print axioms sourceDeletionSurvival_or_blockerVertex_eq_mutualPair
#print axioms exists_blockerCenter_mem_capInteriorByIndex
#print axioms exists_mutualBlockerCapIndices_same_only_first
#print axioms false_of_firstPair_complementaryMembership_of_blocker_mem_firstCap
#print axioms exists_mutualBlockerCapIndices_distinct_otherCaps
#print axioms false_of_twoCapSources_complementaryMembership
#print axioms false_of_twoCapSources_mutualCrossMembership_distinctBlockers
#print axioms sixCenterDeletionSurvivalPacket_of_oneSided
#print axioms false_of_twoCapSources_oneSidedDeletionSurvival
#print axioms false_of_twoCapSources_firstFiber
#print axioms exists_selectedRow_escape_criticalTripleShellSeed
#print axioms exists_criticalRow_escape_or_fullyDeletionRobust_criticalTripleShellSeed
#print axioms exists_globalK4Row_and_sourceFaithfulCriticalCover
#print axioms firstFiber_sourceFaithfulCriticalCover_eq_firstShell
#print axioms firstFiber_globalRow_inter_firstShell_card_le_two
#print axioms firstFiber_globalRow_sdiff_firstShell_card_ge_two
#print axioms exists_two_firstFiber_globalRow_points_outside_firstShell
#print axioms false_of_freshCanonicalRowOverride
#print axioms false_of_capSource_alignedSingletonRadius_of_secondBlocker_nonbisector
#print axioms false_of_capSource_freshOutsideFirstBlockerFiber_alignedSingletonRadius
#print axioms false_of_capSource_freshOutsideFirstBlockerFiber_alignedRadii
#print axioms false_of_capSource_freshOutsideFirstBlockerFiber
#print axioms false_of_capSource_freshOutsideSecondBlockerFiber
end Problem97.ATailFrontierLiveClosure.TwoSourceExactCollisionRowsTerminal
