/- Generated by `generate_selected_rank_instances.py`; do not edit. -/
import ParentRowIngressAdapters

/-! Manifest-selected shared rank and Kalmanson source producers. -/

namespace Problem97
namespace ATailExactFiveCard13DistinctRadiusSourceIngressCoordinatorScratch

open ATailCriticalPairFrontier
open ATailBiApexRobustCapBounds
open ATailExactFiveCard13CnfIngressScratch
open ATailExactFiveCard13CommonLabelTransportScratch
open ATailExactFiveGlobalCrossDeletionPair
open ATailExactFiveGlobalCoverStarGeometry
open ATailExactFiveMutualOneHitGeometry
open ATailFirstApexShellRole
open ATailKalmansonParentOrderScratch
open ATailLargeCapUniqueFive
open ATailLargeCapUniqueFivePhysicalOmissionCycle
open ATailLargeCapUniqueFivePhysicalOmissionTransitionGlobal
open ATailOrientedPhysicalApexIngress
open ATailParentExactFiveSecondCap
open ATailPhysicalSecondApexCommonDeletion
open CanonicalAsymmetricSemanticRowTable

attribute [local instance] Classical.propDecidable
set_option maxHeartbeats 0
set_option maxRecDepth 1000000
noncomputable section

variable
    {D : CounterexampleData} {S : SurplusCapPacket D.A} {radius : ℝ}
    {H : CriticalShellSystem D.A}
    {F : CriticalPairFrontier D S radius H}
    {R : FrontierCommonDeletionParentResidual F}
    {B : FrontierBiApexRobustResidual R}
    {Q : FrontierBiApexRobustExactFiveSecondCapResidual B}
    {profile : LargeCapUniqueFiveSecondApexRadius D S}
    {M : PhysicalActualCriticalMutualOmissionPair H profile}
    {N : SourceTwoHitNormalForm Q profile M}
    (P : CanonicalAsymmetricRolePrepacket N)
    {star : PhysicalGlobalCrossDeletionStar profile}
    {first : FirstApexShellRolePacket F R}

/-- Manifest-selected source assertion `h43150` (selected_row). -/
theorem selectedRankSource_h43150
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 5 && rowBit (directSourceRows C) 2 0 8)) || ((rankAtom (directSourceRanks P) 4 == rankAtom (directSourceRanks P) 7)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (5 : Fin 13) (8 : Fin 13)
    (4 : Fin 78) (7 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (4 : Fin 78) (0 : Fin 13) (5 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (7 : Fin 78) (0 : Fin 13) (8 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43151` (selected_row). -/
theorem selectedRankSource_h43151
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 5 && rowBit (directSourceRows C) 2 0 9)) || ((rankAtom (directSourceRanks P) 4 == rankAtom (directSourceRanks P) 8)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (5 : Fin 13) (9 : Fin 13)
    (4 : Fin 78) (8 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (4 : Fin 78) (0 : Fin 13) (5 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (8 : Fin 78) (0 : Fin 13) (9 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43152` (selected_row). -/
theorem selectedRankSource_h43152
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 5 && rowBit (directSourceRows C) 2 0 10)) || ((rankAtom (directSourceRanks P) 4 == rankAtom (directSourceRanks P) 9)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (5 : Fin 13) (10 : Fin 13)
    (4 : Fin 78) (9 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (4 : Fin 78) (0 : Fin 13) (5 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (9 : Fin 78) (0 : Fin 13) (10 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43153` (selected_row). -/
theorem selectedRankSource_h43153
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 5 && rowBit (directSourceRows C) 2 0 11)) || ((rankAtom (directSourceRanks P) 4 == rankAtom (directSourceRanks P) 10)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (5 : Fin 13) (11 : Fin 13)
    (4 : Fin 78) (10 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (4 : Fin 78) (0 : Fin 13) (5 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (10 : Fin 78) (0 : Fin 13) (11 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43154` (selected_row). -/
theorem selectedRankSource_h43154
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 5 && rowBit (directSourceRows C) 2 0 12)) || ((rankAtom (directSourceRanks P) 4 == rankAtom (directSourceRanks P) 11)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (5 : Fin 13) (12 : Fin 13)
    (4 : Fin 78) (11 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (4 : Fin 78) (0 : Fin 13) (5 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (11 : Fin 78) (0 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43155` (selected_row). -/
theorem selectedRankSource_h43155
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 6 && rowBit (directSourceRows C) 2 0 7)) || ((rankAtom (directSourceRanks P) 5 == rankAtom (directSourceRanks P) 6)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (6 : Fin 13) (7 : Fin 13)
    (5 : Fin 78) (6 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (5 : Fin 78) (0 : Fin 13) (6 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (6 : Fin 78) (0 : Fin 13) (7 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43156` (selected_row). -/
theorem selectedRankSource_h43156
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 6 && rowBit (directSourceRows C) 2 0 8)) || ((rankAtom (directSourceRanks P) 5 == rankAtom (directSourceRanks P) 7)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (6 : Fin 13) (8 : Fin 13)
    (5 : Fin 78) (7 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (5 : Fin 78) (0 : Fin 13) (6 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (7 : Fin 78) (0 : Fin 13) (8 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43157` (selected_row). -/
theorem selectedRankSource_h43157
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 6 && rowBit (directSourceRows C) 2 0 9)) || ((rankAtom (directSourceRanks P) 5 == rankAtom (directSourceRanks P) 8)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (6 : Fin 13) (9 : Fin 13)
    (5 : Fin 78) (8 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (5 : Fin 78) (0 : Fin 13) (6 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (8 : Fin 78) (0 : Fin 13) (9 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43158` (selected_row). -/
theorem selectedRankSource_h43158
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 6 && rowBit (directSourceRows C) 2 0 10)) || ((rankAtom (directSourceRanks P) 5 == rankAtom (directSourceRanks P) 9)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (6 : Fin 13) (10 : Fin 13)
    (5 : Fin 78) (9 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (5 : Fin 78) (0 : Fin 13) (6 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (9 : Fin 78) (0 : Fin 13) (10 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43159` (selected_row). -/
theorem selectedRankSource_h43159
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 6 && rowBit (directSourceRows C) 2 0 11)) || ((rankAtom (directSourceRanks P) 5 == rankAtom (directSourceRanks P) 10)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (6 : Fin 13) (11 : Fin 13)
    (5 : Fin 78) (10 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (5 : Fin 78) (0 : Fin 13) (6 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (10 : Fin 78) (0 : Fin 13) (11 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43160` (selected_row). -/
theorem selectedRankSource_h43160
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 6 && rowBit (directSourceRows C) 2 0 12)) || ((rankAtom (directSourceRanks P) 5 == rankAtom (directSourceRanks P) 11)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (6 : Fin 13) (12 : Fin 13)
    (5 : Fin 78) (11 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (5 : Fin 78) (0 : Fin 13) (6 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (11 : Fin 78) (0 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43161` (selected_row). -/
theorem selectedRankSource_h43161
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 7 && rowBit (directSourceRows C) 2 0 8)) || ((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 7)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (7 : Fin 13) (8 : Fin 13)
    (6 : Fin 78) (7 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (6 : Fin 78) (0 : Fin 13) (7 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (7 : Fin 78) (0 : Fin 13) (8 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43162` (selected_row). -/
theorem selectedRankSource_h43162
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 7 && rowBit (directSourceRows C) 2 0 9)) || ((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 8)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (7 : Fin 13) (9 : Fin 13)
    (6 : Fin 78) (8 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (6 : Fin 78) (0 : Fin 13) (7 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (8 : Fin 78) (0 : Fin 13) (9 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43163` (selected_row). -/
theorem selectedRankSource_h43163
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 7 && rowBit (directSourceRows C) 2 0 10)) || ((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 9)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (7 : Fin 13) (10 : Fin 13)
    (6 : Fin 78) (9 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (6 : Fin 78) (0 : Fin 13) (7 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (9 : Fin 78) (0 : Fin 13) (10 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43164` (selected_row). -/
theorem selectedRankSource_h43164
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 7 && rowBit (directSourceRows C) 2 0 11)) || ((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 10)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (7 : Fin 13) (11 : Fin 13)
    (6 : Fin 78) (10 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (6 : Fin 78) (0 : Fin 13) (7 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (10 : Fin 78) (0 : Fin 13) (11 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43165` (selected_row). -/
theorem selectedRankSource_h43165
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 7 && rowBit (directSourceRows C) 2 0 12)) || ((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 11)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (7 : Fin 13) (12 : Fin 13)
    (6 : Fin 78) (11 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (6 : Fin 78) (0 : Fin 13) (7 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (11 : Fin 78) (0 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43166` (selected_row). -/
theorem selectedRankSource_h43166
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 8 && rowBit (directSourceRows C) 2 0 9)) || ((rankAtom (directSourceRanks P) 7 == rankAtom (directSourceRanks P) 8)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (8 : Fin 13) (9 : Fin 13)
    (7 : Fin 78) (8 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (7 : Fin 78) (0 : Fin 13) (8 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (8 : Fin 78) (0 : Fin 13) (9 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43167` (selected_row). -/
theorem selectedRankSource_h43167
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 8 && rowBit (directSourceRows C) 2 0 10)) || ((rankAtom (directSourceRanks P) 7 == rankAtom (directSourceRanks P) 9)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (8 : Fin 13) (10 : Fin 13)
    (7 : Fin 78) (9 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (7 : Fin 78) (0 : Fin 13) (8 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (9 : Fin 78) (0 : Fin 13) (10 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43168` (selected_row). -/
theorem selectedRankSource_h43168
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 8 && rowBit (directSourceRows C) 2 0 11)) || ((rankAtom (directSourceRanks P) 7 == rankAtom (directSourceRanks P) 10)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (8 : Fin 13) (11 : Fin 13)
    (7 : Fin 78) (10 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (7 : Fin 78) (0 : Fin 13) (8 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (10 : Fin 78) (0 : Fin 13) (11 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43169` (selected_row). -/
theorem selectedRankSource_h43169
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 8 && rowBit (directSourceRows C) 2 0 12)) || ((rankAtom (directSourceRanks P) 7 == rankAtom (directSourceRanks P) 11)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (8 : Fin 13) (12 : Fin 13)
    (7 : Fin 78) (11 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (7 : Fin 78) (0 : Fin 13) (8 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (11 : Fin 78) (0 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43170` (selected_row). -/
theorem selectedRankSource_h43170
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 9 && rowBit (directSourceRows C) 2 0 10)) || ((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 9)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (9 : Fin 13) (10 : Fin 13)
    (8 : Fin 78) (9 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (8 : Fin 78) (0 : Fin 13) (9 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (9 : Fin 78) (0 : Fin 13) (10 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43171` (selected_row). -/
theorem selectedRankSource_h43171
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 9 && rowBit (directSourceRows C) 2 0 11)) || ((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 10)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (9 : Fin 13) (11 : Fin 13)
    (8 : Fin 78) (10 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (8 : Fin 78) (0 : Fin 13) (9 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (10 : Fin 78) (0 : Fin 13) (11 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43172` (selected_row). -/
theorem selectedRankSource_h43172
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 9 && rowBit (directSourceRows C) 2 0 12)) || ((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 11)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (9 : Fin 13) (12 : Fin 13)
    (8 : Fin 78) (11 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (8 : Fin 78) (0 : Fin 13) (9 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (11 : Fin 78) (0 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43173` (selected_row). -/
theorem selectedRankSource_h43173
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 10 && rowBit (directSourceRows C) 2 0 11)) || ((rankAtom (directSourceRanks P) 9 == rankAtom (directSourceRanks P) 10)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (10 : Fin 13) (11 : Fin 13)
    (9 : Fin 78) (10 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (9 : Fin 78) (0 : Fin 13) (10 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (10 : Fin 78) (0 : Fin 13) (11 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43174` (selected_row). -/
theorem selectedRankSource_h43174
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 10 && rowBit (directSourceRows C) 2 0 12)) || ((rankAtom (directSourceRanks P) 9 == rankAtom (directSourceRanks P) 11)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (10 : Fin 13) (12 : Fin 13)
    (9 : Fin 78) (11 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (9 : Fin 78) (0 : Fin 13) (10 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (11 : Fin 78) (0 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43175` (selected_row). -/
theorem selectedRankSource_h43175
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 0 11 && rowBit (directSourceRows C) 2 0 12)) || ((rankAtom (directSourceRanks P) 10 == rankAtom (directSourceRanks P) 11)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (0 : Fin 13)
    (11 : Fin 13) (12 : Fin 13)
    (10 : Fin 78) (11 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (10 : Fin 78) (0 : Fin 13) (11 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (11 : Fin 78) (0 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43176` (selected_row). -/
theorem selectedRankSource_h43176
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 2)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 12)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (2 : Fin 13)
    (0 : Fin 78) (12 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (12 : Fin 78) (1 : Fin 13) (2 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43177` (selected_row). -/
theorem selectedRankSource_h43177
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 3)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 13)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (3 : Fin 13)
    (0 : Fin 78) (13 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (13 : Fin 78) (1 : Fin 13) (3 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43178` (selected_row). -/
theorem selectedRankSource_h43178
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 4)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 14)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (4 : Fin 13)
    (0 : Fin 78) (14 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43179` (selected_row). -/
theorem selectedRankSource_h43179
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 5)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 15)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (5 : Fin 13)
    (0 : Fin 78) (15 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (15 : Fin 78) (1 : Fin 13) (5 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43180` (selected_row). -/
theorem selectedRankSource_h43180
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 6)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 16)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (6 : Fin 13)
    (0 : Fin 78) (16 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (16 : Fin 78) (1 : Fin 13) (6 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43181` (selected_row). -/
theorem selectedRankSource_h43181
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 7)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 17)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (7 : Fin 13)
    (0 : Fin 78) (17 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (17 : Fin 78) (1 : Fin 13) (7 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43182` (selected_row). -/
theorem selectedRankSource_h43182
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 8)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 18)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (8 : Fin 13)
    (0 : Fin 78) (18 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (18 : Fin 78) (1 : Fin 13) (8 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43183` (selected_row). -/
theorem selectedRankSource_h43183
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 9)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 19)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (9 : Fin 13)
    (0 : Fin 78) (19 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (19 : Fin 78) (1 : Fin 13) (9 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43184` (selected_row). -/
theorem selectedRankSource_h43184
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 10)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 20)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (10 : Fin 13)
    (0 : Fin 78) (20 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (20 : Fin 78) (1 : Fin 13) (10 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43185` (selected_row). -/
theorem selectedRankSource_h43185
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 11)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 21)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (11 : Fin 13)
    (0 : Fin 78) (21 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (21 : Fin 78) (1 : Fin 13) (11 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43186` (selected_row). -/
theorem selectedRankSource_h43186
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 0 && rowBit (directSourceRows C) 2 1 12)) || ((rankAtom (directSourceRanks P) 0 == rankAtom (directSourceRanks P) 22)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (0 : Fin 13) (12 : Fin 13)
    (0 : Fin 78) (22 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (0 : Fin 78) (1 : Fin 13) (0 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (22 : Fin 78) (1 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43188` (selected_row). -/
theorem selectedRankSource_h43188
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 2 && rowBit (directSourceRows C) 2 1 4)) || ((rankAtom (directSourceRanks P) 12 == rankAtom (directSourceRanks P) 14)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (2 : Fin 13) (4 : Fin 13)
    (12 : Fin 78) (14 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (12 : Fin 78) (1 : Fin 13) (2 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43189` (selected_row). -/
theorem selectedRankSource_h43189
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 2 && rowBit (directSourceRows C) 2 1 5)) || ((rankAtom (directSourceRanks P) 12 == rankAtom (directSourceRanks P) 15)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (2 : Fin 13) (5 : Fin 13)
    (12 : Fin 78) (15 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (12 : Fin 78) (1 : Fin 13) (2 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (15 : Fin 78) (1 : Fin 13) (5 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43190` (selected_row). -/
theorem selectedRankSource_h43190
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 2 && rowBit (directSourceRows C) 2 1 6)) || ((rankAtom (directSourceRanks P) 12 == rankAtom (directSourceRanks P) 16)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (2 : Fin 13) (6 : Fin 13)
    (12 : Fin 78) (16 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (12 : Fin 78) (1 : Fin 13) (2 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (16 : Fin 78) (1 : Fin 13) (6 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43191` (selected_row). -/
theorem selectedRankSource_h43191
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 2 && rowBit (directSourceRows C) 2 1 7)) || ((rankAtom (directSourceRanks P) 12 == rankAtom (directSourceRanks P) 17)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (2 : Fin 13) (7 : Fin 13)
    (12 : Fin 78) (17 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (12 : Fin 78) (1 : Fin 13) (2 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (17 : Fin 78) (1 : Fin 13) (7 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43192` (selected_row). -/
theorem selectedRankSource_h43192
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 2 && rowBit (directSourceRows C) 2 1 8)) || ((rankAtom (directSourceRanks P) 12 == rankAtom (directSourceRanks P) 18)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (2 : Fin 13) (8 : Fin 13)
    (12 : Fin 78) (18 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (12 : Fin 78) (1 : Fin 13) (2 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (18 : Fin 78) (1 : Fin 13) (8 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43193` (selected_row). -/
theorem selectedRankSource_h43193
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 2 && rowBit (directSourceRows C) 2 1 9)) || ((rankAtom (directSourceRanks P) 12 == rankAtom (directSourceRanks P) 19)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (2 : Fin 13) (9 : Fin 13)
    (12 : Fin 78) (19 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (12 : Fin 78) (1 : Fin 13) (2 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (19 : Fin 78) (1 : Fin 13) (9 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43194` (selected_row). -/
theorem selectedRankSource_h43194
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 2 && rowBit (directSourceRows C) 2 1 10)) || ((rankAtom (directSourceRanks P) 12 == rankAtom (directSourceRanks P) 20)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (2 : Fin 13) (10 : Fin 13)
    (12 : Fin 78) (20 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (12 : Fin 78) (1 : Fin 13) (2 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (20 : Fin 78) (1 : Fin 13) (10 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43195` (selected_row). -/
theorem selectedRankSource_h43195
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 2 && rowBit (directSourceRows C) 2 1 11)) || ((rankAtom (directSourceRanks P) 12 == rankAtom (directSourceRanks P) 21)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (2 : Fin 13) (11 : Fin 13)
    (12 : Fin 78) (21 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (12 : Fin 78) (1 : Fin 13) (2 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (21 : Fin 78) (1 : Fin 13) (11 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43196` (selected_row). -/
theorem selectedRankSource_h43196
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 2 && rowBit (directSourceRows C) 2 1 12)) || ((rankAtom (directSourceRanks P) 12 == rankAtom (directSourceRanks P) 22)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (2 : Fin 13) (12 : Fin 13)
    (12 : Fin 78) (22 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (12 : Fin 78) (1 : Fin 13) (2 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (22 : Fin 78) (1 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43197` (selected_row). -/
theorem selectedRankSource_h43197
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 3 && rowBit (directSourceRows C) 2 1 4)) || ((rankAtom (directSourceRanks P) 13 == rankAtom (directSourceRanks P) 14)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (3 : Fin 13) (4 : Fin 13)
    (13 : Fin 78) (14 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (13 : Fin 78) (1 : Fin 13) (3 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43198` (selected_row). -/
theorem selectedRankSource_h43198
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 3 && rowBit (directSourceRows C) 2 1 5)) || ((rankAtom (directSourceRanks P) 13 == rankAtom (directSourceRanks P) 15)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (3 : Fin 13) (5 : Fin 13)
    (13 : Fin 78) (15 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (13 : Fin 78) (1 : Fin 13) (3 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (15 : Fin 78) (1 : Fin 13) (5 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43199` (selected_row). -/
theorem selectedRankSource_h43199
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 3 && rowBit (directSourceRows C) 2 1 6)) || ((rankAtom (directSourceRanks P) 13 == rankAtom (directSourceRanks P) 16)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (3 : Fin 13) (6 : Fin 13)
    (13 : Fin 78) (16 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (13 : Fin 78) (1 : Fin 13) (3 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (16 : Fin 78) (1 : Fin 13) (6 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43200` (selected_row). -/
theorem selectedRankSource_h43200
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 3 && rowBit (directSourceRows C) 2 1 7)) || ((rankAtom (directSourceRanks P) 13 == rankAtom (directSourceRanks P) 17)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (3 : Fin 13) (7 : Fin 13)
    (13 : Fin 78) (17 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (13 : Fin 78) (1 : Fin 13) (3 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (17 : Fin 78) (1 : Fin 13) (7 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43201` (selected_row). -/
theorem selectedRankSource_h43201
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 3 && rowBit (directSourceRows C) 2 1 8)) || ((rankAtom (directSourceRanks P) 13 == rankAtom (directSourceRanks P) 18)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (3 : Fin 13) (8 : Fin 13)
    (13 : Fin 78) (18 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (13 : Fin 78) (1 : Fin 13) (3 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (18 : Fin 78) (1 : Fin 13) (8 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43202` (selected_row). -/
theorem selectedRankSource_h43202
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 3 && rowBit (directSourceRows C) 2 1 9)) || ((rankAtom (directSourceRanks P) 13 == rankAtom (directSourceRanks P) 19)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (3 : Fin 13) (9 : Fin 13)
    (13 : Fin 78) (19 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (13 : Fin 78) (1 : Fin 13) (3 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (19 : Fin 78) (1 : Fin 13) (9 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43203` (selected_row). -/
theorem selectedRankSource_h43203
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 3 && rowBit (directSourceRows C) 2 1 10)) || ((rankAtom (directSourceRanks P) 13 == rankAtom (directSourceRanks P) 20)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (3 : Fin 13) (10 : Fin 13)
    (13 : Fin 78) (20 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (13 : Fin 78) (1 : Fin 13) (3 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (20 : Fin 78) (1 : Fin 13) (10 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43204` (selected_row). -/
theorem selectedRankSource_h43204
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 3 && rowBit (directSourceRows C) 2 1 11)) || ((rankAtom (directSourceRanks P) 13 == rankAtom (directSourceRanks P) 21)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (3 : Fin 13) (11 : Fin 13)
    (13 : Fin 78) (21 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (13 : Fin 78) (1 : Fin 13) (3 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (21 : Fin 78) (1 : Fin 13) (11 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43205` (selected_row). -/
theorem selectedRankSource_h43205
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 3 && rowBit (directSourceRows C) 2 1 12)) || ((rankAtom (directSourceRanks P) 13 == rankAtom (directSourceRanks P) 22)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (3 : Fin 13) (12 : Fin 13)
    (13 : Fin 78) (22 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (13 : Fin 78) (1 : Fin 13) (3 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (22 : Fin 78) (1 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43206` (selected_row). -/
theorem selectedRankSource_h43206
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 4 && rowBit (directSourceRows C) 2 1 5)) || ((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 15)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (4 : Fin 13) (5 : Fin 13)
    (14 : Fin 78) (15 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (15 : Fin 78) (1 : Fin 13) (5 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43207` (selected_row). -/
theorem selectedRankSource_h43207
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 4 && rowBit (directSourceRows C) 2 1 6)) || ((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 16)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (4 : Fin 13) (6 : Fin 13)
    (14 : Fin 78) (16 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (16 : Fin 78) (1 : Fin 13) (6 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43208` (selected_row). -/
theorem selectedRankSource_h43208
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 4 && rowBit (directSourceRows C) 2 1 7)) || ((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 17)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (4 : Fin 13) (7 : Fin 13)
    (14 : Fin 78) (17 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (17 : Fin 78) (1 : Fin 13) (7 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43209` (selected_row). -/
theorem selectedRankSource_h43209
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 4 && rowBit (directSourceRows C) 2 1 8)) || ((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 18)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (4 : Fin 13) (8 : Fin 13)
    (14 : Fin 78) (18 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (18 : Fin 78) (1 : Fin 13) (8 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43210` (selected_row). -/
theorem selectedRankSource_h43210
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 4 && rowBit (directSourceRows C) 2 1 9)) || ((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 19)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (4 : Fin 13) (9 : Fin 13)
    (14 : Fin 78) (19 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (19 : Fin 78) (1 : Fin 13) (9 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43211` (selected_row). -/
theorem selectedRankSource_h43211
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 4 && rowBit (directSourceRows C) 2 1 10)) || ((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 20)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (4 : Fin 13) (10 : Fin 13)
    (14 : Fin 78) (20 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (20 : Fin 78) (1 : Fin 13) (10 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43212` (selected_row). -/
theorem selectedRankSource_h43212
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 4 && rowBit (directSourceRows C) 2 1 11)) || ((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 21)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (4 : Fin 13) (11 : Fin 13)
    (14 : Fin 78) (21 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (21 : Fin 78) (1 : Fin 13) (11 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43213` (selected_row). -/
theorem selectedRankSource_h43213
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 4 && rowBit (directSourceRows C) 2 1 12)) || ((rankAtom (directSourceRanks P) 14 == rankAtom (directSourceRanks P) 22)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (4 : Fin 13) (12 : Fin 13)
    (14 : Fin 78) (22 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (14 : Fin 78) (1 : Fin 13) (4 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (22 : Fin 78) (1 : Fin 13) (12 : Fin 13) (by decide))

/-- Manifest-selected source assertion `h43214` (selected_row). -/
theorem selectedRankSource_h43214
    (T : CanonicalAsymmetricSemanticRowTable P star first)
    (C : CanonicalCoverFamilies T) :
    ((!((rowBit (directSourceRows C) 2 1 5 && rowBit (directSourceRows C) 2 1 6)) || ((rankAtom (directSourceRanks P) 15 == rankAtom (directSourceRanks P) 16)))) = true := by
  exact directSource_row_rank_guard C (2 : Fin 3) (1 : Fin 13)
    (5 : Fin 13) (6 : Fin 13)
    (15 : Fin 78) (16 : Fin 78)
    (cardThirteenPairDistance_eq_centerDistance P
      (15 : Fin 78) (1 : Fin 13) (5 : Fin 13) (by decide))
    (cardThirteenPairDistance_eq_centerDistance P
      (16 : Fin 78) (1 : Fin 13) (6 : Fin 13) (by decide))

end
end ATailExactFiveCard13DistinctRadiusSourceIngressCoordinatorScratch
end Problem97
