/- Generated by `generate_selected_rank_instances.py`; do not edit. -/
import ParentRowIngressAdapters

/-! Manifest-selected shared rank and Kalmanson source producers. -/

namespace Problem97
namespace ATailExactFiveCard13DistinctRadiusSourceIngressCoordinatorScratch

open ATailCriticalPairFrontier
open ATailBiApexRobustCapBounds
open ATailExactFiveCard13CnfIngressScratch
open ATailExactFiveCard13CommonLabelTransportScratch
open ATailExactFiveGlobalCrossDeletionPair
open ATailExactFiveGlobalCoverStarGeometry
open ATailExactFiveMutualOneHitGeometry
open ATailFirstApexShellRole
open ATailKalmansonParentOrderScratch
open ATailLargeCapUniqueFive
open ATailLargeCapUniqueFivePhysicalOmissionCycle
open ATailLargeCapUniqueFivePhysicalOmissionTransitionGlobal
open ATailOrientedPhysicalApexIngress
open ATailParentExactFiveSecondCap
open ATailPhysicalSecondApexCommonDeletion
open CanonicalAsymmetricSemanticRowTable

attribute [local instance] Classical.propDecidable
set_option maxHeartbeats 0
set_option maxRecDepth 1000000
noncomputable section

variable
    {D : CounterexampleData} {S : SurplusCapPacket D.A} {radius : ℝ}
    {H : CriticalShellSystem D.A}
    {F : CriticalPairFrontier D S radius H}
    {R : FrontierCommonDeletionParentResidual F}
    {B : FrontierBiApexRobustResidual R}
    {Q : FrontierBiApexRobustExactFiveSecondCapResidual B}
    {profile : LargeCapUniqueFiveSecondApexRadius D S}
    {M : PhysicalActualCriticalMutualOmissionPair H profile}
    {N : SourceTwoHitNormalForm Q profile M}
    (P : CanonicalAsymmetricRolePrepacket N)
    {star : PhysicalGlobalCrossDeletionStar profile}
    {first : FirstApexShellRolePacket F R}

/-- Manifest-selected source assertion `h54149` (kalmanson). -/
theorem selectedRankSource_h54149 :
    ((!((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 9)) || ((rankAtom (directSourceRanks P) 53).ult (rankAtom (directSourceRanks P) 54)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (54 : Fin 78) (8 : Fin 78)
    (53 : Fin 78) (9 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (10 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (9 : Fin 78) (8 : Fin 78)
    (54 : Fin 78) (4 : Fin 78) (72 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54150` (kalmanson). -/
theorem selectedRankSource_h54150 :
    ((!((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 53)) || ((rankAtom (directSourceRanks P) 9).ult (rankAtom (directSourceRanks P) 54)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (54 : Fin 78) (8 : Fin 78)
    (9 : Fin 78) (53 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (10 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (9 : Fin 78) (8 : Fin 78)
    (54 : Fin 78) (4 : Fin 78) (72 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54151` (kalmanson). -/
theorem selectedRankSource_h54151 :
    ((!((rankAtom (directSourceRanks P) 54 == rankAtom (directSourceRanks P) 9)) || ((rankAtom (directSourceRanks P) 53).ult (rankAtom (directSourceRanks P) 8)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (8 : Fin 78) (54 : Fin 78)
    (53 : Fin 78) (9 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (10 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (9 : Fin 78) (8 : Fin 78)
    (54 : Fin 78) (4 : Fin 78) (72 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54152` (kalmanson). -/
theorem selectedRankSource_h54152 :
    ((!((rankAtom (directSourceRanks P) 54 == rankAtom (directSourceRanks P) 53)) || ((rankAtom (directSourceRanks P) 9).ult (rankAtom (directSourceRanks P) 8)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (8 : Fin 78) (54 : Fin 78)
    (9 : Fin 78) (53 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (10 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (9 : Fin 78) (8 : Fin 78)
    (54 : Fin 78) (4 : Fin 78) (72 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54153` (kalmanson). -/
theorem selectedRankSource_h54153 :
    ((!((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 4)) || ((rankAtom (directSourceRanks P) 73).ult (rankAtom (directSourceRanks P) 55)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (55 : Fin 78) (8 : Fin 78)
    (73 : Fin 78) (4 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (10 : Fin 78) (8 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (73 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54154` (kalmanson). -/
theorem selectedRankSource_h54154 :
    ((!((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 73)) || ((rankAtom (directSourceRanks P) 4).ult (rankAtom (directSourceRanks P) 55)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (55 : Fin 78) (8 : Fin 78)
    (4 : Fin 78) (73 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (10 : Fin 78) (8 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (73 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54155` (kalmanson). -/
theorem selectedRankSource_h54155 :
    ((!((rankAtom (directSourceRanks P) 55 == rankAtom (directSourceRanks P) 4)) || ((rankAtom (directSourceRanks P) 73).ult (rankAtom (directSourceRanks P) 8)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (8 : Fin 78) (55 : Fin 78)
    (73 : Fin 78) (4 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (10 : Fin 78) (8 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (73 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54156` (kalmanson). -/
theorem selectedRankSource_h54156 :
    ((!((rankAtom (directSourceRanks P) 55 == rankAtom (directSourceRanks P) 73)) || ((rankAtom (directSourceRanks P) 4).ult (rankAtom (directSourceRanks P) 8)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (8 : Fin 78) (55 : Fin 78)
    (4 : Fin 78) (73 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (10 : Fin 78) (8 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (73 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54157` (kalmanson). -/
theorem selectedRankSource_h54157 :
    ((!((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 10)) || ((rankAtom (directSourceRanks P) 53).ult (rankAtom (directSourceRanks P) 55)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (55 : Fin 78) (8 : Fin 78)
    (53 : Fin 78) (10 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (10 : Fin 78) (8 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (73 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54158` (kalmanson). -/
theorem selectedRankSource_h54158 :
    ((!((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 53)) || ((rankAtom (directSourceRanks P) 10).ult (rankAtom (directSourceRanks P) 55)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (55 : Fin 78) (8 : Fin 78)
    (10 : Fin 78) (53 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (10 : Fin 78) (8 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (73 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54159` (kalmanson). -/
theorem selectedRankSource_h54159 :
    ((!((rankAtom (directSourceRanks P) 55 == rankAtom (directSourceRanks P) 10)) || ((rankAtom (directSourceRanks P) 53).ult (rankAtom (directSourceRanks P) 8)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (8 : Fin 78) (55 : Fin 78)
    (53 : Fin 78) (10 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (10 : Fin 78) (8 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (73 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54160` (kalmanson). -/
theorem selectedRankSource_h54160 :
    ((!((rankAtom (directSourceRanks P) 55 == rankAtom (directSourceRanks P) 53)) || ((rankAtom (directSourceRanks P) 10).ult (rankAtom (directSourceRanks P) 8)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (8 : Fin 78) (55 : Fin 78)
    (10 : Fin 78) (53 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (10 : Fin 78) (8 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (73 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54161` (kalmanson). -/
theorem selectedRankSource_h54161 :
    ((!((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 4)) || ((rankAtom (directSourceRanks P) 74).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (8 : Fin 78)
    (74 : Fin 78) (4 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (11 : Fin 78) (8 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (74 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54162` (kalmanson). -/
theorem selectedRankSource_h54162 :
    ((!((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 74)) || ((rankAtom (directSourceRanks P) 4).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (8 : Fin 78)
    (4 : Fin 78) (74 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (11 : Fin 78) (8 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (74 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54163` (kalmanson). -/
theorem selectedRankSource_h54163 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 4)) || ((rankAtom (directSourceRanks P) 74).ult (rankAtom (directSourceRanks P) 8)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (8 : Fin 78) (56 : Fin 78)
    (74 : Fin 78) (4 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (11 : Fin 78) (8 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (74 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54164` (kalmanson). -/
theorem selectedRankSource_h54164 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 74)) || ((rankAtom (directSourceRanks P) 4).ult (rankAtom (directSourceRanks P) 8)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (8 : Fin 78) (56 : Fin 78)
    (4 : Fin 78) (74 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (11 : Fin 78) (8 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (74 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54165` (kalmanson). -/
theorem selectedRankSource_h54165 :
    ((!((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 11)) || ((rankAtom (directSourceRanks P) 53).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (8 : Fin 78)
    (53 : Fin 78) (11 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (11 : Fin 78) (8 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (74 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54166` (kalmanson). -/
theorem selectedRankSource_h54166 :
    ((!((rankAtom (directSourceRanks P) 8 == rankAtom (directSourceRanks P) 53)) || ((rankAtom (directSourceRanks P) 11).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (8 : Fin 78)
    (11 : Fin 78) (53 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (11 : Fin 78) (8 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (74 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54167` (kalmanson). -/
theorem selectedRankSource_h54167 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 11)) || ((rankAtom (directSourceRanks P) 53).ult (rankAtom (directSourceRanks P) 8)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (8 : Fin 78) (56 : Fin 78)
    (53 : Fin 78) (11 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (11 : Fin 78) (8 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (74 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54168` (kalmanson). -/
theorem selectedRankSource_h54168 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 53)) || ((rankAtom (directSourceRanks P) 11).ult (rankAtom (directSourceRanks P) 8)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (8 : Fin 78) (56 : Fin 78)
    (11 : Fin 78) (53 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (9 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (53 : Fin 78) (11 : Fin 78) (8 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (74 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54169` (kalmanson). -/
theorem selectedRankSource_h54169 :
    ((!((rankAtom (directSourceRanks P) 9 == rankAtom (directSourceRanks P) 4)) || ((rankAtom (directSourceRanks P) 75).ult (rankAtom (directSourceRanks P) 55)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (55 : Fin 78) (9 : Fin 78)
    (75 : Fin 78) (4 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (10 : Fin 78) (9 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (75 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54170` (kalmanson). -/
theorem selectedRankSource_h54170 :
    ((!((rankAtom (directSourceRanks P) 9 == rankAtom (directSourceRanks P) 75)) || ((rankAtom (directSourceRanks P) 4).ult (rankAtom (directSourceRanks P) 55)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (55 : Fin 78) (9 : Fin 78)
    (4 : Fin 78) (75 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (10 : Fin 78) (9 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (75 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54171` (kalmanson). -/
theorem selectedRankSource_h54171 :
    ((!((rankAtom (directSourceRanks P) 55 == rankAtom (directSourceRanks P) 4)) || ((rankAtom (directSourceRanks P) 75).ult (rankAtom (directSourceRanks P) 9)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (9 : Fin 78) (55 : Fin 78)
    (75 : Fin 78) (4 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (10 : Fin 78) (9 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (75 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54172` (kalmanson). -/
theorem selectedRankSource_h54172 :
    ((!((rankAtom (directSourceRanks P) 55 == rankAtom (directSourceRanks P) 75)) || ((rankAtom (directSourceRanks P) 4).ult (rankAtom (directSourceRanks P) 9)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (9 : Fin 78) (55 : Fin 78)
    (4 : Fin 78) (75 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (10 : Fin 78) (9 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (75 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54173` (kalmanson). -/
theorem selectedRankSource_h54173 :
    ((!((rankAtom (directSourceRanks P) 9 == rankAtom (directSourceRanks P) 10)) || ((rankAtom (directSourceRanks P) 54).ult (rankAtom (directSourceRanks P) 55)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (55 : Fin 78) (9 : Fin 78)
    (54 : Fin 78) (10 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (10 : Fin 78) (9 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (75 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54174` (kalmanson). -/
theorem selectedRankSource_h54174 :
    ((!((rankAtom (directSourceRanks P) 9 == rankAtom (directSourceRanks P) 54)) || ((rankAtom (directSourceRanks P) 10).ult (rankAtom (directSourceRanks P) 55)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (55 : Fin 78) (9 : Fin 78)
    (10 : Fin 78) (54 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (10 : Fin 78) (9 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (75 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54175` (kalmanson). -/
theorem selectedRankSource_h54175 :
    ((!((rankAtom (directSourceRanks P) 55 == rankAtom (directSourceRanks P) 10)) || ((rankAtom (directSourceRanks P) 54).ult (rankAtom (directSourceRanks P) 9)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (9 : Fin 78) (55 : Fin 78)
    (54 : Fin 78) (10 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (10 : Fin 78) (9 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (75 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54176` (kalmanson). -/
theorem selectedRankSource_h54176 :
    ((!((rankAtom (directSourceRanks P) 55 == rankAtom (directSourceRanks P) 54)) || ((rankAtom (directSourceRanks P) 10).ult (rankAtom (directSourceRanks P) 9)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (9 : Fin 78) (55 : Fin 78)
    (10 : Fin 78) (54 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (11 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (10 : Fin 78) (9 : Fin 78)
    (55 : Fin 78) (4 : Fin 78) (75 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54177` (kalmanson). -/
theorem selectedRankSource_h54177 :
    ((!((rankAtom (directSourceRanks P) 9 == rankAtom (directSourceRanks P) 4)) || ((rankAtom (directSourceRanks P) 76).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (9 : Fin 78)
    (76 : Fin 78) (4 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (11 : Fin 78) (9 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (76 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54178` (kalmanson). -/
theorem selectedRankSource_h54178 :
    ((!((rankAtom (directSourceRanks P) 9 == rankAtom (directSourceRanks P) 76)) || ((rankAtom (directSourceRanks P) 4).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (9 : Fin 78)
    (4 : Fin 78) (76 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (11 : Fin 78) (9 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (76 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54179` (kalmanson). -/
theorem selectedRankSource_h54179 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 4)) || ((rankAtom (directSourceRanks P) 76).ult (rankAtom (directSourceRanks P) 9)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (9 : Fin 78) (56 : Fin 78)
    (76 : Fin 78) (4 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (11 : Fin 78) (9 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (76 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54180` (kalmanson). -/
theorem selectedRankSource_h54180 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 76)) || ((rankAtom (directSourceRanks P) 4).ult (rankAtom (directSourceRanks P) 9)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (9 : Fin 78) (56 : Fin 78)
    (4 : Fin 78) (76 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (11 : Fin 78) (9 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (76 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54181` (kalmanson). -/
theorem selectedRankSource_h54181 :
    ((!((rankAtom (directSourceRanks P) 9 == rankAtom (directSourceRanks P) 11)) || ((rankAtom (directSourceRanks P) 54).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (9 : Fin 78)
    (54 : Fin 78) (11 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (11 : Fin 78) (9 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (76 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54182` (kalmanson). -/
theorem selectedRankSource_h54182 :
    ((!((rankAtom (directSourceRanks P) 9 == rankAtom (directSourceRanks P) 54)) || ((rankAtom (directSourceRanks P) 11).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (9 : Fin 78)
    (11 : Fin 78) (54 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (11 : Fin 78) (9 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (76 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54183` (kalmanson). -/
theorem selectedRankSource_h54183 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 11)) || ((rankAtom (directSourceRanks P) 54).ult (rankAtom (directSourceRanks P) 9)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (9 : Fin 78) (56 : Fin 78)
    (54 : Fin 78) (11 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (11 : Fin 78) (9 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (76 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54184` (kalmanson). -/
theorem selectedRankSource_h54184 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 54)) || ((rankAtom (directSourceRanks P) 11).ult (rankAtom (directSourceRanks P) 9)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (9 : Fin 78) (56 : Fin 78)
    (11 : Fin 78) (54 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (10 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (54 : Fin 78) (11 : Fin 78) (9 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (76 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54185` (kalmanson). -/
theorem selectedRankSource_h54185 :
    ((!((rankAtom (directSourceRanks P) 10 == rankAtom (directSourceRanks P) 4)) || ((rankAtom (directSourceRanks P) 77).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (10 : Fin 78)
    (77 : Fin 78) (4 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (11 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (55 : Fin 78) (11 : Fin 78) (10 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (77 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54186` (kalmanson). -/
theorem selectedRankSource_h54186 :
    ((!((rankAtom (directSourceRanks P) 10 == rankAtom (directSourceRanks P) 77)) || ((rankAtom (directSourceRanks P) 4).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (10 : Fin 78)
    (4 : Fin 78) (77 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (11 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (55 : Fin 78) (11 : Fin 78) (10 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (77 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54187` (kalmanson). -/
theorem selectedRankSource_h54187 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 4)) || ((rankAtom (directSourceRanks P) 77).ult (rankAtom (directSourceRanks P) 10)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (10 : Fin 78) (56 : Fin 78)
    (77 : Fin 78) (4 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (11 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (55 : Fin 78) (11 : Fin 78) (10 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (77 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54188` (kalmanson). -/
theorem selectedRankSource_h54188 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 77)) || ((rankAtom (directSourceRanks P) 4).ult (rankAtom (directSourceRanks P) 10)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (10 : Fin 78) (56 : Fin 78)
    (4 : Fin 78) (77 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (11 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (55 : Fin 78) (11 : Fin 78) (10 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (77 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54189` (kalmanson). -/
theorem selectedRankSource_h54189 :
    ((!((rankAtom (directSourceRanks P) 10 == rankAtom (directSourceRanks P) 11)) || ((rankAtom (directSourceRanks P) 55).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (10 : Fin 78)
    (55 : Fin 78) (11 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (11 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (55 : Fin 78) (11 : Fin 78) (10 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (77 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54190` (kalmanson). -/
theorem selectedRankSource_h54190 :
    ((!((rankAtom (directSourceRanks P) 10 == rankAtom (directSourceRanks P) 55)) || ((rankAtom (directSourceRanks P) 11).ult (rankAtom (directSourceRanks P) 56)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (56 : Fin 78) (10 : Fin 78)
    (11 : Fin 78) (55 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (11 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (55 : Fin 78) (11 : Fin 78) (10 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (77 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54191` (kalmanson). -/
theorem selectedRankSource_h54191 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 11)) || ((rankAtom (directSourceRanks P) 55).ult (rankAtom (directSourceRanks P) 10)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (10 : Fin 78) (56 : Fin 78)
    (55 : Fin 78) (11 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (11 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (55 : Fin 78) (11 : Fin 78) (10 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (77 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54192` (kalmanson). -/
theorem selectedRankSource_h54192 :
    ((!((rankAtom (directSourceRanks P) 56 == rankAtom (directSourceRanks P) 55)) || ((rankAtom (directSourceRanks P) 11).ult (rankAtom (directSourceRanks P) 10)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (10 : Fin 78) (56 : Fin 78)
    (11 : Fin 78) (55 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (5 : Fin 13) (11 : Fin 13) (12 : Fin 13)
    (by decide) (by decide) (by decide)
    (55 : Fin 78) (11 : Fin 78) (10 : Fin 78)
    (56 : Fin 78) (4 : Fin 78) (77 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54193` (kalmanson). -/
theorem selectedRankSource_h54193 :
    ((!((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 5)) || ((rankAtom (directSourceRanks P) 63).ult (rankAtom (directSourceRanks P) 58)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (58 : Fin 78) (6 : Fin 78)
    (63 : Fin 78) (5 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (8 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (7 : Fin 78) (6 : Fin 78)
    (58 : Fin 78) (5 : Fin 78) (63 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54194` (kalmanson). -/
theorem selectedRankSource_h54194 :
    ((!((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 63)) || ((rankAtom (directSourceRanks P) 5).ult (rankAtom (directSourceRanks P) 58)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (58 : Fin 78) (6 : Fin 78)
    (5 : Fin 78) (63 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (8 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (7 : Fin 78) (6 : Fin 78)
    (58 : Fin 78) (5 : Fin 78) (63 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54195` (kalmanson). -/
theorem selectedRankSource_h54195 :
    ((!((rankAtom (directSourceRanks P) 58 == rankAtom (directSourceRanks P) 5)) || ((rankAtom (directSourceRanks P) 63).ult (rankAtom (directSourceRanks P) 6)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (6 : Fin 78) (58 : Fin 78)
    (63 : Fin 78) (5 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (8 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (7 : Fin 78) (6 : Fin 78)
    (58 : Fin 78) (5 : Fin 78) (63 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54196` (kalmanson). -/
theorem selectedRankSource_h54196 :
    ((!((rankAtom (directSourceRanks P) 58 == rankAtom (directSourceRanks P) 63)) || ((rankAtom (directSourceRanks P) 5).ult (rankAtom (directSourceRanks P) 6)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (6 : Fin 78) (58 : Fin 78)
    (5 : Fin 78) (63 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (8 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (7 : Fin 78) (6 : Fin 78)
    (58 : Fin 78) (5 : Fin 78) (63 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54197` (kalmanson). -/
theorem selectedRankSource_h54197 :
    ((!((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 7)) || ((rankAtom (directSourceRanks P) 57).ult (rankAtom (directSourceRanks P) 58)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (58 : Fin 78) (6 : Fin 78)
    (57 : Fin 78) (7 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (8 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (7 : Fin 78) (6 : Fin 78)
    (58 : Fin 78) (5 : Fin 78) (63 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54198` (kalmanson). -/
theorem selectedRankSource_h54198 :
    ((!((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 57)) || ((rankAtom (directSourceRanks P) 7).ult (rankAtom (directSourceRanks P) 58)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (58 : Fin 78) (6 : Fin 78)
    (7 : Fin 78) (57 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (8 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (7 : Fin 78) (6 : Fin 78)
    (58 : Fin 78) (5 : Fin 78) (63 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54199` (kalmanson). -/
theorem selectedRankSource_h54199 :
    ((!((rankAtom (directSourceRanks P) 58 == rankAtom (directSourceRanks P) 7)) || ((rankAtom (directSourceRanks P) 57).ult (rankAtom (directSourceRanks P) 6)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (6 : Fin 78) (58 : Fin 78)
    (57 : Fin 78) (7 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (8 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (7 : Fin 78) (6 : Fin 78)
    (58 : Fin 78) (5 : Fin 78) (63 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54200` (kalmanson). -/
theorem selectedRankSource_h54200 :
    ((!((rankAtom (directSourceRanks P) 58 == rankAtom (directSourceRanks P) 57)) || ((rankAtom (directSourceRanks P) 7).ult (rankAtom (directSourceRanks P) 6)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (6 : Fin 78) (58 : Fin 78)
    (7 : Fin 78) (57 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (8 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (7 : Fin 78) (6 : Fin 78)
    (58 : Fin 78) (5 : Fin 78) (63 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54201` (kalmanson). -/
theorem selectedRankSource_h54201 :
    ((!((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 5)) || ((rankAtom (directSourceRanks P) 64).ult (rankAtom (directSourceRanks P) 59)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (59 : Fin 78) (6 : Fin 78)
    (64 : Fin 78) (5 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (9 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (8 : Fin 78) (6 : Fin 78)
    (59 : Fin 78) (5 : Fin 78) (64 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54202` (kalmanson). -/
theorem selectedRankSource_h54202 :
    ((!((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 64)) || ((rankAtom (directSourceRanks P) 5).ult (rankAtom (directSourceRanks P) 59)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (59 : Fin 78) (6 : Fin 78)
    (5 : Fin 78) (64 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (9 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (8 : Fin 78) (6 : Fin 78)
    (59 : Fin 78) (5 : Fin 78) (64 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54203` (kalmanson). -/
theorem selectedRankSource_h54203 :
    ((!((rankAtom (directSourceRanks P) 59 == rankAtom (directSourceRanks P) 5)) || ((rankAtom (directSourceRanks P) 64).ult (rankAtom (directSourceRanks P) 6)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (6 : Fin 78) (59 : Fin 78)
    (64 : Fin 78) (5 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (9 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (8 : Fin 78) (6 : Fin 78)
    (59 : Fin 78) (5 : Fin 78) (64 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54204` (kalmanson). -/
theorem selectedRankSource_h54204 :
    ((!((rankAtom (directSourceRanks P) 59 == rankAtom (directSourceRanks P) 64)) || ((rankAtom (directSourceRanks P) 5).ult (rankAtom (directSourceRanks P) 6)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (6 : Fin 78) (59 : Fin 78)
    (5 : Fin 78) (64 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (9 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (8 : Fin 78) (6 : Fin 78)
    (59 : Fin 78) (5 : Fin 78) (64 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54205` (kalmanson). -/
theorem selectedRankSource_h54205 :
    ((!((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 8)) || ((rankAtom (directSourceRanks P) 57).ult (rankAtom (directSourceRanks P) 59)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (59 : Fin 78) (6 : Fin 78)
    (57 : Fin 78) (8 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (9 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (8 : Fin 78) (6 : Fin 78)
    (59 : Fin 78) (5 : Fin 78) (64 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54206` (kalmanson). -/
theorem selectedRankSource_h54206 :
    ((!((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 57)) || ((rankAtom (directSourceRanks P) 8).ult (rankAtom (directSourceRanks P) 59)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (59 : Fin 78) (6 : Fin 78)
    (8 : Fin 78) (57 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (9 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (8 : Fin 78) (6 : Fin 78)
    (59 : Fin 78) (5 : Fin 78) (64 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54207` (kalmanson). -/
theorem selectedRankSource_h54207 :
    ((!((rankAtom (directSourceRanks P) 59 == rankAtom (directSourceRanks P) 8)) || ((rankAtom (directSourceRanks P) 57).ult (rankAtom (directSourceRanks P) 6)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (6 : Fin 78) (59 : Fin 78)
    (57 : Fin 78) (8 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (9 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (8 : Fin 78) (6 : Fin 78)
    (59 : Fin 78) (5 : Fin 78) (64 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54208` (kalmanson). -/
theorem selectedRankSource_h54208 :
    ((!((rankAtom (directSourceRanks P) 59 == rankAtom (directSourceRanks P) 57)) || ((rankAtom (directSourceRanks P) 8).ult (rankAtom (directSourceRanks P) 6)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (6 : Fin 78) (59 : Fin 78)
    (8 : Fin 78) (57 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (9 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (8 : Fin 78) (6 : Fin 78)
    (59 : Fin 78) (5 : Fin 78) (64 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.1

/-- Manifest-selected source assertion `h54209` (kalmanson). -/
theorem selectedRankSource_h54209 :
    ((!((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 5)) || ((rankAtom (directSourceRanks P) 65).ult (rankAtom (directSourceRanks P) 60)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (60 : Fin 78) (6 : Fin 78)
    (65 : Fin 78) (5 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (10 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (9 : Fin 78) (6 : Fin 78)
    (60 : Fin 78) (5 : Fin 78) (65 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54210` (kalmanson). -/
theorem selectedRankSource_h54210 :
    ((!((rankAtom (directSourceRanks P) 6 == rankAtom (directSourceRanks P) 65)) || ((rankAtom (directSourceRanks P) 5).ult (rankAtom (directSourceRanks P) 60)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (60 : Fin 78) (6 : Fin 78)
    (5 : Fin 78) (65 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (10 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (9 : Fin 78) (6 : Fin 78)
    (60 : Fin 78) (5 : Fin 78) (65 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54211` (kalmanson). -/
theorem selectedRankSource_h54211 :
    ((!((rankAtom (directSourceRanks P) 60 == rankAtom (directSourceRanks P) 5)) || ((rankAtom (directSourceRanks P) 65).ult (rankAtom (directSourceRanks P) 6)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (6 : Fin 78) (60 : Fin 78)
    (65 : Fin 78) (5 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (10 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (9 : Fin 78) (6 : Fin 78)
    (60 : Fin 78) (5 : Fin 78) (65 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

/-- Manifest-selected source assertion `h54212` (kalmanson). -/
theorem selectedRankSource_h54212 :
    ((!((rankAtom (directSourceRanks P) 60 == rankAtom (directSourceRanks P) 65)) || ((rankAtom (directSourceRanks P) 5).ult (rankAtom (directSourceRanks P) 6)))) = true := by
  apply directSource_kalmanson_rank_guard P
    (6 : Fin 78) (60 : Fin 78)
    (5 : Fin 78) (65 : Fin 78)
  have hk := strictKalmanson_pairDistances (P := P)
    (0 : Fin 13) (6 : Fin 13) (7 : Fin 13) (10 : Fin 13)
    (by decide) (by decide) (by decide)
    (57 : Fin 78) (9 : Fin 78) (6 : Fin 78)
    (60 : Fin 78) (5 : Fin 78) (65 : Fin 78)
    (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)
  simpa only [add_comm] using hk.2

end
end ATailExactFiveCard13DistinctRadiusSourceIngressCoordinatorScratch
end Problem97
